// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewAddRmrRouteParams creates a new AddRmrRouteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddRmrRouteParams() *AddRmrRouteParams {
	return &AddRmrRouteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddRmrRouteParamsWithTimeout creates a new AddRmrRouteParams object
// with the ability to set a timeout on a request.
func NewAddRmrRouteParamsWithTimeout(timeout time.Duration) *AddRmrRouteParams {
	return &AddRmrRouteParams{
		timeout: timeout,
	}
}

// NewAddRmrRouteParamsWithContext creates a new AddRmrRouteParams object
// with the ability to set a context for a request.
func NewAddRmrRouteParamsWithContext(ctx context.Context) *AddRmrRouteParams {
	return &AddRmrRouteParams{
		Context: ctx,
	}
}

// NewAddRmrRouteParamsWithHTTPClient creates a new AddRmrRouteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddRmrRouteParamsWithHTTPClient(client *http.Client) *AddRmrRouteParams {
	return &AddRmrRouteParams{
		HTTPClient: client,
	}
}

/*
AddRmrRouteParams contains all the parameters to send to the API endpoint

	for the add rmr route operation.

	Typically these are written to a http.Request.
*/
type AddRmrRouteParams struct {

	/* RoutesList.

	   list of routes to add
	*/
	RoutesList rtmgr_models.Routelist

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add rmr route params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddRmrRouteParams) WithDefaults() *AddRmrRouteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add rmr route params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddRmrRouteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add rmr route params
func (o *AddRmrRouteParams) WithTimeout(timeout time.Duration) *AddRmrRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add rmr route params
func (o *AddRmrRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add rmr route params
func (o *AddRmrRouteParams) WithContext(ctx context.Context) *AddRmrRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add rmr route params
func (o *AddRmrRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add rmr route params
func (o *AddRmrRouteParams) WithHTTPClient(client *http.Client) *AddRmrRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add rmr route params
func (o *AddRmrRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoutesList adds the routesList to the add rmr route params
func (o *AddRmrRouteParams) WithRoutesList(routesList rtmgr_models.Routelist) *AddRmrRouteParams {
	o.SetRoutesList(routesList)
	return o
}

// SetRoutesList adds the routesList to the add rmr route params
func (o *AddRmrRouteParams) SetRoutesList(routesList rtmgr_models.Routelist) {
	o.RoutesList = routesList
}

// WriteToRequest writes these params to a swagger request
func (o *AddRmrRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RoutesList != nil {
		if err := r.SetBodyParam(o.RoutesList); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
