// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddRmrRouteReader is a Reader for the AddRmrRoute structure.
type AddRmrRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddRmrRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddRmrRouteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddRmrRouteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /handles/addrmrroute] add_rmr_route", response, response.Code())
	}
}

// NewAddRmrRouteCreated creates a AddRmrRouteCreated with default headers values
func NewAddRmrRouteCreated() *AddRmrRouteCreated {
	return &AddRmrRouteCreated{}
}

/*
AddRmrRouteCreated describes a response with status code 201, with default header values.

rmr routes added
*/
type AddRmrRouteCreated struct {
}

// IsSuccess returns true when this add rmr route created response has a 2xx status code
func (o *AddRmrRouteCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add rmr route created response has a 3xx status code
func (o *AddRmrRouteCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add rmr route created response has a 4xx status code
func (o *AddRmrRouteCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this add rmr route created response has a 5xx status code
func (o *AddRmrRouteCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this add rmr route created response a status code equal to that given
func (o *AddRmrRouteCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the add rmr route created response
func (o *AddRmrRouteCreated) Code() int {
	return 201
}

func (o *AddRmrRouteCreated) Error() string {
	return fmt.Sprintf("[POST /handles/addrmrroute][%d] addRmrRouteCreated ", 201)
}

func (o *AddRmrRouteCreated) String() string {
	return fmt.Sprintf("[POST /handles/addrmrroute][%d] addRmrRouteCreated ", 201)
}

func (o *AddRmrRouteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddRmrRouteBadRequest creates a AddRmrRouteBadRequest with default headers values
func NewAddRmrRouteBadRequest() *AddRmrRouteBadRequest {
	return &AddRmrRouteBadRequest{}
}

/*
AddRmrRouteBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type AddRmrRouteBadRequest struct {
}

// IsSuccess returns true when this add rmr route bad request response has a 2xx status code
func (o *AddRmrRouteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add rmr route bad request response has a 3xx status code
func (o *AddRmrRouteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add rmr route bad request response has a 4xx status code
func (o *AddRmrRouteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this add rmr route bad request response has a 5xx status code
func (o *AddRmrRouteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this add rmr route bad request response a status code equal to that given
func (o *AddRmrRouteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the add rmr route bad request response
func (o *AddRmrRouteBadRequest) Code() int {
	return 400
}

func (o *AddRmrRouteBadRequest) Error() string {
	return fmt.Sprintf("[POST /handles/addrmrroute][%d] addRmrRouteBadRequest ", 400)
}

func (o *AddRmrRouteBadRequest) String() string {
	return fmt.Sprintf("[POST /handles/addrmrroute][%d] addRmrRouteBadRequest ", 400)
}

func (o *AddRmrRouteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
