// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewAssociateRanToE2tHandleParams creates a new AssociateRanToE2tHandleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssociateRanToE2tHandleParams() *AssociateRanToE2tHandleParams {
	return &AssociateRanToE2tHandleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssociateRanToE2tHandleParamsWithTimeout creates a new AssociateRanToE2tHandleParams object
// with the ability to set a timeout on a request.
func NewAssociateRanToE2tHandleParamsWithTimeout(timeout time.Duration) *AssociateRanToE2tHandleParams {
	return &AssociateRanToE2tHandleParams{
		timeout: timeout,
	}
}

// NewAssociateRanToE2tHandleParamsWithContext creates a new AssociateRanToE2tHandleParams object
// with the ability to set a context for a request.
func NewAssociateRanToE2tHandleParamsWithContext(ctx context.Context) *AssociateRanToE2tHandleParams {
	return &AssociateRanToE2tHandleParams{
		Context: ctx,
	}
}

// NewAssociateRanToE2tHandleParamsWithHTTPClient creates a new AssociateRanToE2tHandleParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssociateRanToE2tHandleParamsWithHTTPClient(client *http.Client) *AssociateRanToE2tHandleParams {
	return &AssociateRanToE2tHandleParams{
		HTTPClient: client,
	}
}

/*
AssociateRanToE2tHandleParams contains all the parameters to send to the API endpoint

	for the associate ran to e2t handle operation.

	Typically these are written to a http.Request.
*/
type AssociateRanToE2tHandleParams struct {

	/* RanE2tList.

	   ran to e2t mapping
	*/
	RanE2tList rtmgr_models.RanE2tMap

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the associate ran to e2t handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssociateRanToE2tHandleParams) WithDefaults() *AssociateRanToE2tHandleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the associate ran to e2t handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssociateRanToE2tHandleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) WithTimeout(timeout time.Duration) *AssociateRanToE2tHandleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) WithContext(ctx context.Context) *AssociateRanToE2tHandleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) WithHTTPClient(client *http.Client) *AssociateRanToE2tHandleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRanE2tList adds the ranE2tList to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) WithRanE2tList(ranE2tList rtmgr_models.RanE2tMap) *AssociateRanToE2tHandleParams {
	o.SetRanE2tList(ranE2tList)
	return o
}

// SetRanE2tList adds the ranE2tList to the associate ran to e2t handle params
func (o *AssociateRanToE2tHandleParams) SetRanE2tList(ranE2tList rtmgr_models.RanE2tMap) {
	o.RanE2tList = ranE2tList
}

// WriteToRequest writes these params to a swagger request
func (o *AssociateRanToE2tHandleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RanE2tList != nil {
		if err := r.SetBodyParam(o.RanE2tList); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
