// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AssociateRanToE2tHandleReader is a Reader for the AssociateRanToE2tHandle structure.
type AssociateRanToE2tHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssociateRanToE2tHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAssociateRanToE2tHandleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAssociateRanToE2tHandleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /handles/associate-ran-to-e2t] associate_ran_to_e2t_handle", response, response.Code())
	}
}

// NewAssociateRanToE2tHandleCreated creates a AssociateRanToE2tHandleCreated with default headers values
func NewAssociateRanToE2tHandleCreated() *AssociateRanToE2tHandleCreated {
	return &AssociateRanToE2tHandleCreated{}
}

/*
AssociateRanToE2tHandleCreated describes a response with status code 201, with default header values.

e2t ran mapping recieved, platform routes
*/
type AssociateRanToE2tHandleCreated struct {
}

// IsSuccess returns true when this associate ran to e2t handle created response has a 2xx status code
func (o *AssociateRanToE2tHandleCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this associate ran to e2t handle created response has a 3xx status code
func (o *AssociateRanToE2tHandleCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this associate ran to e2t handle created response has a 4xx status code
func (o *AssociateRanToE2tHandleCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this associate ran to e2t handle created response has a 5xx status code
func (o *AssociateRanToE2tHandleCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this associate ran to e2t handle created response a status code equal to that given
func (o *AssociateRanToE2tHandleCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the associate ran to e2t handle created response
func (o *AssociateRanToE2tHandleCreated) Code() int {
	return 201
}

func (o *AssociateRanToE2tHandleCreated) Error() string {
	return fmt.Sprintf("[POST /handles/associate-ran-to-e2t][%d] associateRanToE2tHandleCreated ", 201)
}

func (o *AssociateRanToE2tHandleCreated) String() string {
	return fmt.Sprintf("[POST /handles/associate-ran-to-e2t][%d] associateRanToE2tHandleCreated ", 201)
}

func (o *AssociateRanToE2tHandleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAssociateRanToE2tHandleBadRequest creates a AssociateRanToE2tHandleBadRequest with default headers values
func NewAssociateRanToE2tHandleBadRequest() *AssociateRanToE2tHandleBadRequest {
	return &AssociateRanToE2tHandleBadRequest{}
}

/*
AssociateRanToE2tHandleBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type AssociateRanToE2tHandleBadRequest struct {
}

// IsSuccess returns true when this associate ran to e2t handle bad request response has a 2xx status code
func (o *AssociateRanToE2tHandleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this associate ran to e2t handle bad request response has a 3xx status code
func (o *AssociateRanToE2tHandleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this associate ran to e2t handle bad request response has a 4xx status code
func (o *AssociateRanToE2tHandleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this associate ran to e2t handle bad request response has a 5xx status code
func (o *AssociateRanToE2tHandleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this associate ran to e2t handle bad request response a status code equal to that given
func (o *AssociateRanToE2tHandleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the associate ran to e2t handle bad request response
func (o *AssociateRanToE2tHandleBadRequest) Code() int {
	return 400
}

func (o *AssociateRanToE2tHandleBadRequest) Error() string {
	return fmt.Sprintf("[POST /handles/associate-ran-to-e2t][%d] associateRanToE2tHandleBadRequest ", 400)
}

func (o *AssociateRanToE2tHandleBadRequest) String() string {
	return fmt.Sprintf("[POST /handles/associate-ran-to-e2t][%d] associateRanToE2tHandleBadRequest ", 400)
}

func (o *AssociateRanToE2tHandleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
