// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewCreateNewE2tHandleParams creates a new CreateNewE2tHandleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateNewE2tHandleParams() *CreateNewE2tHandleParams {
	return &CreateNewE2tHandleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNewE2tHandleParamsWithTimeout creates a new CreateNewE2tHandleParams object
// with the ability to set a timeout on a request.
func NewCreateNewE2tHandleParamsWithTimeout(timeout time.Duration) *CreateNewE2tHandleParams {
	return &CreateNewE2tHandleParams{
		timeout: timeout,
	}
}

// NewCreateNewE2tHandleParamsWithContext creates a new CreateNewE2tHandleParams object
// with the ability to set a context for a request.
func NewCreateNewE2tHandleParamsWithContext(ctx context.Context) *CreateNewE2tHandleParams {
	return &CreateNewE2tHandleParams{
		Context: ctx,
	}
}

// NewCreateNewE2tHandleParamsWithHTTPClient creates a new CreateNewE2tHandleParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateNewE2tHandleParamsWithHTTPClient(client *http.Client) *CreateNewE2tHandleParams {
	return &CreateNewE2tHandleParams{
		HTTPClient: client,
	}
}

/*
CreateNewE2tHandleParams contains all the parameters to send to the API endpoint

	for the create new e2t handle operation.

	Typically these are written to a http.Request.
*/
type CreateNewE2tHandleParams struct {

	/* E2tData.

	   FQDN of the newly joined E2T instance
	*/
	E2tData *rtmgr_models.E2tData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create new e2t handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNewE2tHandleParams) WithDefaults() *CreateNewE2tHandleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create new e2t handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNewE2tHandleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create new e2t handle params
func (o *CreateNewE2tHandleParams) WithTimeout(timeout time.Duration) *CreateNewE2tHandleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create new e2t handle params
func (o *CreateNewE2tHandleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create new e2t handle params
func (o *CreateNewE2tHandleParams) WithContext(ctx context.Context) *CreateNewE2tHandleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create new e2t handle params
func (o *CreateNewE2tHandleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create new e2t handle params
func (o *CreateNewE2tHandleParams) WithHTTPClient(client *http.Client) *CreateNewE2tHandleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create new e2t handle params
func (o *CreateNewE2tHandleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithE2tData adds the e2tData to the create new e2t handle params
func (o *CreateNewE2tHandleParams) WithE2tData(e2tData *rtmgr_models.E2tData) *CreateNewE2tHandleParams {
	o.SetE2tData(e2tData)
	return o
}

// SetE2tData adds the e2tData to the create new e2t handle params
func (o *CreateNewE2tHandleParams) SetE2tData(e2tData *rtmgr_models.E2tData) {
	o.E2tData = e2tData
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNewE2tHandleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.E2tData != nil {
		if err := r.SetBodyParam(o.E2tData); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
