// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateNewE2tHandleReader is a Reader for the CreateNewE2tHandle structure.
type CreateNewE2tHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNewE2tHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNewE2tHandleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateNewE2tHandleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /handles/e2t] create_new_e2t_handle", response, response.Code())
	}
}

// NewCreateNewE2tHandleCreated creates a CreateNewE2tHandleCreated with default headers values
func NewCreateNewE2tHandleCreated() *CreateNewE2tHandleCreated {
	return &CreateNewE2tHandleCreated{}
}

/*
CreateNewE2tHandleCreated describes a response with status code 201, with default header values.

new e2t instance is considered and platform routes are established
*/
type CreateNewE2tHandleCreated struct {
}

// IsSuccess returns true when this create new e2t handle created response has a 2xx status code
func (o *CreateNewE2tHandleCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create new e2t handle created response has a 3xx status code
func (o *CreateNewE2tHandleCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new e2t handle created response has a 4xx status code
func (o *CreateNewE2tHandleCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new e2t handle created response has a 5xx status code
func (o *CreateNewE2tHandleCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create new e2t handle created response a status code equal to that given
func (o *CreateNewE2tHandleCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create new e2t handle created response
func (o *CreateNewE2tHandleCreated) Code() int {
	return 201
}

func (o *CreateNewE2tHandleCreated) Error() string {
	return fmt.Sprintf("[POST /handles/e2t][%d] createNewE2tHandleCreated ", 201)
}

func (o *CreateNewE2tHandleCreated) String() string {
	return fmt.Sprintf("[POST /handles/e2t][%d] createNewE2tHandleCreated ", 201)
}

func (o *CreateNewE2tHandleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNewE2tHandleBadRequest creates a CreateNewE2tHandleBadRequest with default headers values
func NewCreateNewE2tHandleBadRequest() *CreateNewE2tHandleBadRequest {
	return &CreateNewE2tHandleBadRequest{}
}

/*
CreateNewE2tHandleBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type CreateNewE2tHandleBadRequest struct {
}

// IsSuccess returns true when this create new e2t handle bad request response has a 2xx status code
func (o *CreateNewE2tHandleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new e2t handle bad request response has a 3xx status code
func (o *CreateNewE2tHandleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new e2t handle bad request response has a 4xx status code
func (o *CreateNewE2tHandleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new e2t handle bad request response has a 5xx status code
func (o *CreateNewE2tHandleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create new e2t handle bad request response a status code equal to that given
func (o *CreateNewE2tHandleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create new e2t handle bad request response
func (o *CreateNewE2tHandleBadRequest) Code() int {
	return 400
}

func (o *CreateNewE2tHandleBadRequest) Error() string {
	return fmt.Sprintf("[POST /handles/e2t][%d] createNewE2tHandleBadRequest ", 400)
}

func (o *CreateNewE2tHandleBadRequest) String() string {
	return fmt.Sprintf("[POST /handles/e2t][%d] createNewE2tHandleBadRequest ", 400)
}

func (o *CreateNewE2tHandleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
