// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewDelRmrRouteParams creates a new DelRmrRouteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelRmrRouteParams() *DelRmrRouteParams {
	return &DelRmrRouteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelRmrRouteParamsWithTimeout creates a new DelRmrRouteParams object
// with the ability to set a timeout on a request.
func NewDelRmrRouteParamsWithTimeout(timeout time.Duration) *DelRmrRouteParams {
	return &DelRmrRouteParams{
		timeout: timeout,
	}
}

// NewDelRmrRouteParamsWithContext creates a new DelRmrRouteParams object
// with the ability to set a context for a request.
func NewDelRmrRouteParamsWithContext(ctx context.Context) *DelRmrRouteParams {
	return &DelRmrRouteParams{
		Context: ctx,
	}
}

// NewDelRmrRouteParamsWithHTTPClient creates a new DelRmrRouteParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelRmrRouteParamsWithHTTPClient(client *http.Client) *DelRmrRouteParams {
	return &DelRmrRouteParams{
		HTTPClient: client,
	}
}

/*
DelRmrRouteParams contains all the parameters to send to the API endpoint

	for the del rmr route operation.

	Typically these are written to a http.Request.
*/
type DelRmrRouteParams struct {

	/* RoutesList.

	   list of routes to delete
	*/
	RoutesList rtmgr_models.Routelist

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the del rmr route params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelRmrRouteParams) WithDefaults() *DelRmrRouteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the del rmr route params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelRmrRouteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the del rmr route params
func (o *DelRmrRouteParams) WithTimeout(timeout time.Duration) *DelRmrRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the del rmr route params
func (o *DelRmrRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the del rmr route params
func (o *DelRmrRouteParams) WithContext(ctx context.Context) *DelRmrRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the del rmr route params
func (o *DelRmrRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the del rmr route params
func (o *DelRmrRouteParams) WithHTTPClient(client *http.Client) *DelRmrRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the del rmr route params
func (o *DelRmrRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoutesList adds the routesList to the del rmr route params
func (o *DelRmrRouteParams) WithRoutesList(routesList rtmgr_models.Routelist) *DelRmrRouteParams {
	o.SetRoutesList(routesList)
	return o
}

// SetRoutesList adds the routesList to the del rmr route params
func (o *DelRmrRouteParams) SetRoutesList(routesList rtmgr_models.Routelist) {
	o.RoutesList = routesList
}

// WriteToRequest writes these params to a swagger request
func (o *DelRmrRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RoutesList != nil {
		if err := r.SetBodyParam(o.RoutesList); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
