// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DelRmrRouteReader is a Reader for the DelRmrRoute structure.
type DelRmrRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelRmrRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDelRmrRouteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDelRmrRouteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /handles/delrmrroute] del_rmr_route", response, response.Code())
	}
}

// NewDelRmrRouteCreated creates a DelRmrRouteCreated with default headers values
func NewDelRmrRouteCreated() *DelRmrRouteCreated {
	return &DelRmrRouteCreated{}
}

/*
DelRmrRouteCreated describes a response with status code 201, with default header values.

rmr routes added
*/
type DelRmrRouteCreated struct {
}

// IsSuccess returns true when this del rmr route created response has a 2xx status code
func (o *DelRmrRouteCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this del rmr route created response has a 3xx status code
func (o *DelRmrRouteCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del rmr route created response has a 4xx status code
func (o *DelRmrRouteCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this del rmr route created response has a 5xx status code
func (o *DelRmrRouteCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this del rmr route created response a status code equal to that given
func (o *DelRmrRouteCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the del rmr route created response
func (o *DelRmrRouteCreated) Code() int {
	return 201
}

func (o *DelRmrRouteCreated) Error() string {
	return fmt.Sprintf("[DELETE /handles/delrmrroute][%d] delRmrRouteCreated ", 201)
}

func (o *DelRmrRouteCreated) String() string {
	return fmt.Sprintf("[DELETE /handles/delrmrroute][%d] delRmrRouteCreated ", 201)
}

func (o *DelRmrRouteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDelRmrRouteBadRequest creates a DelRmrRouteBadRequest with default headers values
func NewDelRmrRouteBadRequest() *DelRmrRouteBadRequest {
	return &DelRmrRouteBadRequest{}
}

/*
DelRmrRouteBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type DelRmrRouteBadRequest struct {
}

// IsSuccess returns true when this del rmr route bad request response has a 2xx status code
func (o *DelRmrRouteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this del rmr route bad request response has a 3xx status code
func (o *DelRmrRouteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this del rmr route bad request response has a 4xx status code
func (o *DelRmrRouteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this del rmr route bad request response has a 5xx status code
func (o *DelRmrRouteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this del rmr route bad request response a status code equal to that given
func (o *DelRmrRouteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the del rmr route bad request response
func (o *DelRmrRouteBadRequest) Code() int {
	return 400
}

func (o *DelRmrRouteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /handles/delrmrroute][%d] delRmrRouteBadRequest ", 400)
}

func (o *DelRmrRouteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /handles/delrmrroute][%d] delRmrRouteBadRequest ", 400)
}

func (o *DelRmrRouteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
