// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewDeleteXappSubscriptionHandleParams creates a new DeleteXappSubscriptionHandleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteXappSubscriptionHandleParams() *DeleteXappSubscriptionHandleParams {
	return &DeleteXappSubscriptionHandleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteXappSubscriptionHandleParamsWithTimeout creates a new DeleteXappSubscriptionHandleParams object
// with the ability to set a timeout on a request.
func NewDeleteXappSubscriptionHandleParamsWithTimeout(timeout time.Duration) *DeleteXappSubscriptionHandleParams {
	return &DeleteXappSubscriptionHandleParams{
		timeout: timeout,
	}
}

// NewDeleteXappSubscriptionHandleParamsWithContext creates a new DeleteXappSubscriptionHandleParams object
// with the ability to set a context for a request.
func NewDeleteXappSubscriptionHandleParamsWithContext(ctx context.Context) *DeleteXappSubscriptionHandleParams {
	return &DeleteXappSubscriptionHandleParams{
		Context: ctx,
	}
}

// NewDeleteXappSubscriptionHandleParamsWithHTTPClient creates a new DeleteXappSubscriptionHandleParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteXappSubscriptionHandleParamsWithHTTPClient(client *http.Client) *DeleteXappSubscriptionHandleParams {
	return &DeleteXappSubscriptionHandleParams{
		HTTPClient: client,
	}
}

/*
DeleteXappSubscriptionHandleParams contains all the parameters to send to the API endpoint

	for the delete xapp subscription handle operation.

	Typically these are written to a http.Request.
*/
type DeleteXappSubscriptionHandleParams struct {

	/* XappSubscriptionData.

	   xApp related subscription data
	*/
	XappSubscriptionData *rtmgr_models.XappSubscriptionData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete xapp subscription handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteXappSubscriptionHandleParams) WithDefaults() *DeleteXappSubscriptionHandleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete xapp subscription handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteXappSubscriptionHandleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) WithTimeout(timeout time.Duration) *DeleteXappSubscriptionHandleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) WithContext(ctx context.Context) *DeleteXappSubscriptionHandleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) WithHTTPClient(client *http.Client) *DeleteXappSubscriptionHandleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXappSubscriptionData adds the xappSubscriptionData to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) WithXappSubscriptionData(xappSubscriptionData *rtmgr_models.XappSubscriptionData) *DeleteXappSubscriptionHandleParams {
	o.SetXappSubscriptionData(xappSubscriptionData)
	return o
}

// SetXappSubscriptionData adds the xappSubscriptionData to the delete xapp subscription handle params
func (o *DeleteXappSubscriptionHandleParams) SetXappSubscriptionData(xappSubscriptionData *rtmgr_models.XappSubscriptionData) {
	o.XappSubscriptionData = xappSubscriptionData
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteXappSubscriptionHandleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.XappSubscriptionData != nil {
		if err := r.SetBodyParam(o.XappSubscriptionData); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
