// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteE2tHandleReader is a Reader for the DeleteE2tHandle structure.
type DeleteE2tHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteE2tHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteE2tHandleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteE2tHandleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /handles/e2t] delete_e2t_handle", response, response.Code())
	}
}

// NewDeleteE2tHandleCreated creates a DeleteE2tHandleCreated with default headers values
func NewDeleteE2tHandleCreated() *DeleteE2tHandleCreated {
	return &DeleteE2tHandleCreated{}
}

/*
DeleteE2tHandleCreated describes a response with status code 201, with default header values.

new e2t instance is considered and platform routes are established
*/
type DeleteE2tHandleCreated struct {
}

// IsSuccess returns true when this delete e2t handle created response has a 2xx status code
func (o *DeleteE2tHandleCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete e2t handle created response has a 3xx status code
func (o *DeleteE2tHandleCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete e2t handle created response has a 4xx status code
func (o *DeleteE2tHandleCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete e2t handle created response has a 5xx status code
func (o *DeleteE2tHandleCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this delete e2t handle created response a status code equal to that given
func (o *DeleteE2tHandleCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the delete e2t handle created response
func (o *DeleteE2tHandleCreated) Code() int {
	return 201
}

func (o *DeleteE2tHandleCreated) Error() string {
	return fmt.Sprintf("[DELETE /handles/e2t][%d] deleteE2tHandleCreated ", 201)
}

func (o *DeleteE2tHandleCreated) String() string {
	return fmt.Sprintf("[DELETE /handles/e2t][%d] deleteE2tHandleCreated ", 201)
}

func (o *DeleteE2tHandleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteE2tHandleBadRequest creates a DeleteE2tHandleBadRequest with default headers values
func NewDeleteE2tHandleBadRequest() *DeleteE2tHandleBadRequest {
	return &DeleteE2tHandleBadRequest{}
}

/*
DeleteE2tHandleBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type DeleteE2tHandleBadRequest struct {
}

// IsSuccess returns true when this delete e2t handle bad request response has a 2xx status code
func (o *DeleteE2tHandleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete e2t handle bad request response has a 3xx status code
func (o *DeleteE2tHandleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete e2t handle bad request response has a 4xx status code
func (o *DeleteE2tHandleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete e2t handle bad request response has a 5xx status code
func (o *DeleteE2tHandleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete e2t handle bad request response a status code equal to that given
func (o *DeleteE2tHandleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete e2t handle bad request response
func (o *DeleteE2tHandleBadRequest) Code() int {
	return 400
}

func (o *DeleteE2tHandleBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /handles/e2t][%d] deleteE2tHandleBadRequest ", 400)
}

func (o *DeleteE2tHandleBadRequest) String() string {
	return fmt.Sprintf("[DELETE /handles/e2t][%d] deleteE2tHandleBadRequest ", 400)
}

func (o *DeleteE2tHandleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
