// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteXappSubscriptionHandleReader is a Reader for the DeleteXappSubscriptionHandle structure.
type DeleteXappSubscriptionHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteXappSubscriptionHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteXappSubscriptionHandleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteXappSubscriptionHandleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /handles/xapp-subscription-handle] delete_xapp_subscription_handle", response, response.Code())
	}
}

// NewDeleteXappSubscriptionHandleOK creates a DeleteXappSubscriptionHandleOK with default headers values
func NewDeleteXappSubscriptionHandleOK() *DeleteXappSubscriptionHandleOK {
	return &DeleteXappSubscriptionHandleOK{}
}

/*
DeleteXappSubscriptionHandleOK describes a response with status code 200, with default header values.

Xapp Subscription deleted
*/
type DeleteXappSubscriptionHandleOK struct {
}

// IsSuccess returns true when this delete xapp subscription handle o k response has a 2xx status code
func (o *DeleteXappSubscriptionHandleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete xapp subscription handle o k response has a 3xx status code
func (o *DeleteXappSubscriptionHandleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete xapp subscription handle o k response has a 4xx status code
func (o *DeleteXappSubscriptionHandleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete xapp subscription handle o k response has a 5xx status code
func (o *DeleteXappSubscriptionHandleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete xapp subscription handle o k response a status code equal to that given
func (o *DeleteXappSubscriptionHandleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete xapp subscription handle o k response
func (o *DeleteXappSubscriptionHandleOK) Code() int {
	return 200
}

func (o *DeleteXappSubscriptionHandleOK) Error() string {
	return fmt.Sprintf("[DELETE /handles/xapp-subscription-handle][%d] deleteXappSubscriptionHandleOK ", 200)
}

func (o *DeleteXappSubscriptionHandleOK) String() string {
	return fmt.Sprintf("[DELETE /handles/xapp-subscription-handle][%d] deleteXappSubscriptionHandleOK ", 200)
}

func (o *DeleteXappSubscriptionHandleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteXappSubscriptionHandleNoContent creates a DeleteXappSubscriptionHandleNoContent with default headers values
func NewDeleteXappSubscriptionHandleNoContent() *DeleteXappSubscriptionHandleNoContent {
	return &DeleteXappSubscriptionHandleNoContent{}
}

/*
DeleteXappSubscriptionHandleNoContent describes a response with status code 204, with default header values.

Content not found
*/
type DeleteXappSubscriptionHandleNoContent struct {
}

// IsSuccess returns true when this delete xapp subscription handle no content response has a 2xx status code
func (o *DeleteXappSubscriptionHandleNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete xapp subscription handle no content response has a 3xx status code
func (o *DeleteXappSubscriptionHandleNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete xapp subscription handle no content response has a 4xx status code
func (o *DeleteXappSubscriptionHandleNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete xapp subscription handle no content response has a 5xx status code
func (o *DeleteXappSubscriptionHandleNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete xapp subscription handle no content response a status code equal to that given
func (o *DeleteXappSubscriptionHandleNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete xapp subscription handle no content response
func (o *DeleteXappSubscriptionHandleNoContent) Code() int {
	return 204
}

func (o *DeleteXappSubscriptionHandleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /handles/xapp-subscription-handle][%d] deleteXappSubscriptionHandleNoContent ", 204)
}

func (o *DeleteXappSubscriptionHandleNoContent) String() string {
	return fmt.Sprintf("[DELETE /handles/xapp-subscription-handle][%d] deleteXappSubscriptionHandleNoContent ", 204)
}

func (o *DeleteXappSubscriptionHandleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
