// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewDissociateRanParams creates a new DissociateRanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDissociateRanParams() *DissociateRanParams {
	return &DissociateRanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDissociateRanParamsWithTimeout creates a new DissociateRanParams object
// with the ability to set a timeout on a request.
func NewDissociateRanParamsWithTimeout(timeout time.Duration) *DissociateRanParams {
	return &DissociateRanParams{
		timeout: timeout,
	}
}

// NewDissociateRanParamsWithContext creates a new DissociateRanParams object
// with the ability to set a context for a request.
func NewDissociateRanParamsWithContext(ctx context.Context) *DissociateRanParams {
	return &DissociateRanParams{
		Context: ctx,
	}
}

// NewDissociateRanParamsWithHTTPClient creates a new DissociateRanParams object
// with the ability to set a custom HTTPClient for a request.
func NewDissociateRanParamsWithHTTPClient(client *http.Client) *DissociateRanParams {
	return &DissociateRanParams{
		HTTPClient: client,
	}
}

/*
DissociateRanParams contains all the parameters to send to the API endpoint

	for the dissociate ran operation.

	Typically these are written to a http.Request.
*/
type DissociateRanParams struct {

	/* DissociateList.

	   list of RAN to dissociate
	*/
	DissociateList rtmgr_models.RanE2tMap

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dissociate ran params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DissociateRanParams) WithDefaults() *DissociateRanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dissociate ran params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DissociateRanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dissociate ran params
func (o *DissociateRanParams) WithTimeout(timeout time.Duration) *DissociateRanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dissociate ran params
func (o *DissociateRanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dissociate ran params
func (o *DissociateRanParams) WithContext(ctx context.Context) *DissociateRanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dissociate ran params
func (o *DissociateRanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dissociate ran params
func (o *DissociateRanParams) WithHTTPClient(client *http.Client) *DissociateRanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dissociate ran params
func (o *DissociateRanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDissociateList adds the dissociateList to the dissociate ran params
func (o *DissociateRanParams) WithDissociateList(dissociateList rtmgr_models.RanE2tMap) *DissociateRanParams {
	o.SetDissociateList(dissociateList)
	return o
}

// SetDissociateList adds the dissociateList to the dissociate ran params
func (o *DissociateRanParams) SetDissociateList(dissociateList rtmgr_models.RanE2tMap) {
	o.DissociateList = dissociateList
}

// WriteToRequest writes these params to a swagger request
func (o *DissociateRanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.DissociateList != nil {
		if err := r.SetBodyParam(o.DissociateList); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
