// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DissociateRanReader is a Reader for the DissociateRan structure.
type DissociateRanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DissociateRanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDissociateRanCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDissociateRanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /handles/dissociate-ran] dissociate_ran", response, response.Code())
	}
}

// NewDissociateRanCreated creates a DissociateRanCreated with default headers values
func NewDissociateRanCreated() *DissociateRanCreated {
	return &DissociateRanCreated{}
}

/*
DissociateRanCreated describes a response with status code 201, with default header values.

ran instances disociated
*/
type DissociateRanCreated struct {
}

// IsSuccess returns true when this dissociate ran created response has a 2xx status code
func (o *DissociateRanCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dissociate ran created response has a 3xx status code
func (o *DissociateRanCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dissociate ran created response has a 4xx status code
func (o *DissociateRanCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dissociate ran created response has a 5xx status code
func (o *DissociateRanCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dissociate ran created response a status code equal to that given
func (o *DissociateRanCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dissociate ran created response
func (o *DissociateRanCreated) Code() int {
	return 201
}

func (o *DissociateRanCreated) Error() string {
	return fmt.Sprintf("[POST /handles/dissociate-ran][%d] dissociateRanCreated ", 201)
}

func (o *DissociateRanCreated) String() string {
	return fmt.Sprintf("[POST /handles/dissociate-ran][%d] dissociateRanCreated ", 201)
}

func (o *DissociateRanCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDissociateRanBadRequest creates a DissociateRanBadRequest with default headers values
func NewDissociateRanBadRequest() *DissociateRanBadRequest {
	return &DissociateRanBadRequest{}
}

/*
DissociateRanBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type DissociateRanBadRequest struct {
}

// IsSuccess returns true when this dissociate ran bad request response has a 2xx status code
func (o *DissociateRanBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dissociate ran bad request response has a 3xx status code
func (o *DissociateRanBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dissociate ran bad request response has a 4xx status code
func (o *DissociateRanBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this dissociate ran bad request response has a 5xx status code
func (o *DissociateRanBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this dissociate ran bad request response a status code equal to that given
func (o *DissociateRanBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the dissociate ran bad request response
func (o *DissociateRanBadRequest) Code() int {
	return 400
}

func (o *DissociateRanBadRequest) Error() string {
	return fmt.Sprintf("[POST /handles/dissociate-ran][%d] dissociateRanBadRequest ", 400)
}

func (o *DissociateRanBadRequest) String() string {
	return fmt.Sprintf("[POST /handles/dissociate-ran][%d] dissociateRanBadRequest ", 400)
}

func (o *DissociateRanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
