// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHandlesReader is a Reader for the GetHandles structure.
type GetHandlesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHandlesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHandlesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /handles] get_handles", response, response.Code())
	}
}

// NewGetHandlesOK creates a GetHandlesOK with default headers values
func NewGetHandlesOK() *GetHandlesOK {
	return &GetHandlesOK{}
}

/*
GetHandlesOK describes a response with status code 200, with default header values.

Dummy response
*/
type GetHandlesOK struct {
}

// IsSuccess returns true when this get handles o k response has a 2xx status code
func (o *GetHandlesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get handles o k response has a 3xx status code
func (o *GetHandlesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get handles o k response has a 4xx status code
func (o *GetHandlesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get handles o k response has a 5xx status code
func (o *GetHandlesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get handles o k response a status code equal to that given
func (o *GetHandlesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get handles o k response
func (o *GetHandlesOK) Code() int {
	return 200
}

func (o *GetHandlesOK) Error() string {
	return fmt.Sprintf("[GET /handles][%d] getHandlesOK ", 200)
}

func (o *GetHandlesOK) String() string {
	return fmt.Sprintf("[GET /handles][%d] getHandlesOK ", 200)
}

func (o *GetHandlesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
