// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new handle API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for handle API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AddRmrRoute(params *AddRmrRouteParams, opts ...ClientOption) (*AddRmrRouteCreated, error)

	AssociateRanToE2tHandle(params *AssociateRanToE2tHandleParams, opts ...ClientOption) (*AssociateRanToE2tHandleCreated, error)

	CreateNewE2tHandle(params *CreateNewE2tHandleParams, opts ...ClientOption) (*CreateNewE2tHandleCreated, error)

	DelRmrRoute(params *DelRmrRouteParams, opts ...ClientOption) (*DelRmrRouteCreated, error)

	DeleteE2tHandle(params *DeleteE2tHandleParams, opts ...ClientOption) (*DeleteE2tHandleCreated, error)

	DeleteXappSubscriptionHandle(params *DeleteXappSubscriptionHandleParams, opts ...ClientOption) (*DeleteXappSubscriptionHandleOK, *DeleteXappSubscriptionHandleNoContent, error)

	DissociateRan(params *DissociateRanParams, opts ...ClientOption) (*DissociateRanCreated, error)

	GetHandles(params *GetHandlesParams, opts ...ClientOption) (*GetHandlesOK, error)

	ProvideXappHandle(params *ProvideXappHandleParams, opts ...ClientOption) (*ProvideXappHandleCreated, error)

	ProvideXappSubscriptionHandle(params *ProvideXappSubscriptionHandleParams, opts ...ClientOption) (*ProvideXappSubscriptionHandleCreated, error)

	UpdateXappSubscriptionHandle(params *UpdateXappSubscriptionHandleParams, opts ...ClientOption) (*UpdateXappSubscriptionHandleCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AddRmrRoute APIs to add r m r routes

By performing a POST method to add RMR routes
*/
func (a *Client) AddRmrRoute(params *AddRmrRouteParams, opts ...ClientOption) (*AddRmrRouteCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddRmrRouteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "add_rmr_route",
		Method:             "POST",
		PathPattern:        "/handles/addrmrroute",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AddRmrRouteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AddRmrRouteCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for add_rmr_route: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
AssociateRanToE2tHandle APIs for associating a ran to e2t instance

By performing a POST method on rane2tmapping, the API caller is able to update the Routing manager about the ran to e2t mapping which would be finally used to distribute routes to corresponding xApp and E2T instance
*/
func (a *Client) AssociateRanToE2tHandle(params *AssociateRanToE2tHandleParams, opts ...ClientOption) (*AssociateRanToE2tHandleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAssociateRanToE2tHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "associate_ran_to_e2t_handle",
		Method:             "POST",
		PathPattern:        "/handles/associate-ran-to-e2t",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AssociateRanToE2tHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AssociateRanToE2tHandleCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for associate_ran_to_e2t_handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CreateNewE2tHandle APIs for establishing platform routes when a new e2t instance gets added to platform

E2T updates its FQDN to E2M  during its initialisation, hence after E2M informs routing manager about new E2T instances FQDN. At this point Routing Mgr would establish platform routes
*/
func (a *Client) CreateNewE2tHandle(params *CreateNewE2tHandleParams, opts ...ClientOption) (*CreateNewE2tHandleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateNewE2tHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "create_new_e2t_handle",
		Method:             "POST",
		PathPattern:        "/handles/e2t",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateNewE2tHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateNewE2tHandleCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for create_new_e2t_handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DelRmrRoute APIs to delete r m r routes

By performing a DELETE method to add RMR routes
*/
func (a *Client) DelRmrRoute(params *DelRmrRouteParams, opts ...ClientOption) (*DelRmrRouteCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDelRmrRouteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "del_rmr_route",
		Method:             "DELETE",
		PathPattern:        "/handles/delrmrroute",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DelRmrRouteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DelRmrRouteCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for del_rmr_route: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteE2tHandle APIs for clearing routes specific to a particular e2 t instance

E2M would monitor E2T instances using its keep alive based mechanism during this time if an E2T instance is detected to be dead, E2M would distribute already associated ran's to other available/healthy E2T instances. Here E2M would share E2T instance address to be removed OR which is unhealthy and list of RAN instances to be dissociated and an association list which contains E2T FQDN and associated RAN names
*/
func (a *Client) DeleteE2tHandle(params *DeleteE2tHandleParams, opts ...ClientOption) (*DeleteE2tHandleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteE2tHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete_e2t_handle",
		Method:             "DELETE",
		PathPattern:        "/handles/e2t",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteE2tHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteE2tHandleCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete_e2t_handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteXappSubscriptionHandle APIs for deleting an xapp subscription

By performing the delete operation on xapp-subscription-handle resource, the API caller will be able to update routing manager about the deletion of an xapp's subscription
*/
func (a *Client) DeleteXappSubscriptionHandle(params *DeleteXappSubscriptionHandleParams, opts ...ClientOption) (*DeleteXappSubscriptionHandleOK, *DeleteXappSubscriptionHandleNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteXappSubscriptionHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete_xapp_subscription_handle",
		Method:             "DELETE",
		PathPattern:        "/handles/xapp-subscription-handle",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteXappSubscriptionHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *DeleteXappSubscriptionHandleOK:
		return value, nil, nil
	case *DeleteXappSubscriptionHandleNoContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DissociateRan APIs to dissociate ran from e2t

By performing a POST method on rane2tmapping, routing manager will dissociate ran name from e2t instance by updating or clearing routes
*/
func (a *Client) DissociateRan(params *DissociateRanParams, opts ...ClientOption) (*DissociateRanCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDissociateRanParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "dissociate_ran",
		Method:             "POST",
		PathPattern:        "/handles/dissociate-ran",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DissociateRanReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DissociateRanCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for dissociate_ran: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetHandles placeholders for further usage

Placeholder for further usage.
*/
func (a *Client) GetHandles(params *GetHandlesParams, opts ...ClientOption) (*GetHandlesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHandlesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_handles",
		Method:             "GET",
		PathPattern:        "/handles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetHandlesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetHandlesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_handles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ProvideXappHandle provides callback

By performing a POST method on the xapp-handle resource, the API caller is able to perform a callback on Routing Manager.
*/
func (a *Client) ProvideXappHandle(params *ProvideXappHandleParams, opts ...ClientOption) (*ProvideXappHandleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProvideXappHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "provide_xapp_handle",
		Method:             "POST",
		PathPattern:        "/handles/xapp-handle",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ProvideXappHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProvideXappHandleCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for provide_xapp_handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ProvideXappSubscriptionHandle APIs for updating about new xapp subscription

By performing a POST method on the xapp-subscription-handle resource, the API caller is able to update the Routing manager about the creation of new subscription by an Xapp instance.
*/
func (a *Client) ProvideXappSubscriptionHandle(params *ProvideXappSubscriptionHandleParams, opts ...ClientOption) (*ProvideXappSubscriptionHandleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewProvideXappSubscriptionHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "provide_xapp_subscription_handle",
		Method:             "POST",
		PathPattern:        "/handles/xapp-subscription-handle",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ProvideXappSubscriptionHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ProvideXappSubscriptionHandleCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for provide_xapp_subscription_handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateXappSubscriptionHandle APIs for updating the subscriber x app list

By performing a PUT method on a xapp-subscription-handle/{subscription_id} resource, the API caller is able to update the Routing manager about the list of subscriber xApps related to the subscription denoted by the {subsription_id}.
*/
func (a *Client) UpdateXappSubscriptionHandle(params *UpdateXappSubscriptionHandleParams, opts ...ClientOption) (*UpdateXappSubscriptionHandleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateXappSubscriptionHandleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "update_xapp_subscription_handle",
		Method:             "PUT",
		PathPattern:        "/handles/xapp-subscription-handle/{subscription_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateXappSubscriptionHandleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateXappSubscriptionHandleCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for update_xapp_subscription_handle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
