// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewProvideXappHandleParams creates a new ProvideXappHandleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProvideXappHandleParams() *ProvideXappHandleParams {
	return &ProvideXappHandleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProvideXappHandleParamsWithTimeout creates a new ProvideXappHandleParams object
// with the ability to set a timeout on a request.
func NewProvideXappHandleParamsWithTimeout(timeout time.Duration) *ProvideXappHandleParams {
	return &ProvideXappHandleParams{
		timeout: timeout,
	}
}

// NewProvideXappHandleParamsWithContext creates a new ProvideXappHandleParams object
// with the ability to set a context for a request.
func NewProvideXappHandleParamsWithContext(ctx context.Context) *ProvideXappHandleParams {
	return &ProvideXappHandleParams{
		Context: ctx,
	}
}

// NewProvideXappHandleParamsWithHTTPClient creates a new ProvideXappHandleParams object
// with the ability to set a custom HTTPClient for a request.
func NewProvideXappHandleParamsWithHTTPClient(client *http.Client) *ProvideXappHandleParams {
	return &ProvideXappHandleParams{
		HTTPClient: client,
	}
}

/*
ProvideXappHandleParams contains all the parameters to send to the API endpoint

	for the provide xapp handle operation.

	Typically these are written to a http.Request.
*/
type ProvideXappHandleParams struct {

	/* XappCallbackData.

	   xApp related callback data
	*/
	XappCallbackData *rtmgr_models.XappCallbackData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the provide xapp handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProvideXappHandleParams) WithDefaults() *ProvideXappHandleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the provide xapp handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProvideXappHandleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the provide xapp handle params
func (o *ProvideXappHandleParams) WithTimeout(timeout time.Duration) *ProvideXappHandleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the provide xapp handle params
func (o *ProvideXappHandleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the provide xapp handle params
func (o *ProvideXappHandleParams) WithContext(ctx context.Context) *ProvideXappHandleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the provide xapp handle params
func (o *ProvideXappHandleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the provide xapp handle params
func (o *ProvideXappHandleParams) WithHTTPClient(client *http.Client) *ProvideXappHandleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the provide xapp handle params
func (o *ProvideXappHandleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXappCallbackData adds the xappCallbackData to the provide xapp handle params
func (o *ProvideXappHandleParams) WithXappCallbackData(xappCallbackData *rtmgr_models.XappCallbackData) *ProvideXappHandleParams {
	o.SetXappCallbackData(xappCallbackData)
	return o
}

// SetXappCallbackData adds the xappCallbackData to the provide xapp handle params
func (o *ProvideXappHandleParams) SetXappCallbackData(xappCallbackData *rtmgr_models.XappCallbackData) {
	o.XappCallbackData = xappCallbackData
}

// WriteToRequest writes these params to a swagger request
func (o *ProvideXappHandleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.XappCallbackData != nil {
		if err := r.SetBodyParam(o.XappCallbackData); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
