// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProvideXappHandleReader is a Reader for the ProvideXappHandle structure.
type ProvideXappHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProvideXappHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProvideXappHandleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewProvideXappHandleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /handles/xapp-handle] provide_xapp_handle", response, response.Code())
	}
}

// NewProvideXappHandleCreated creates a ProvideXappHandleCreated with default headers values
func NewProvideXappHandleCreated() *ProvideXappHandleCreated {
	return &ProvideXappHandleCreated{}
}

/*
ProvideXappHandleCreated describes a response with status code 201, with default header values.

Callback received
*/
type ProvideXappHandleCreated struct {
}

// IsSuccess returns true when this provide xapp handle created response has a 2xx status code
func (o *ProvideXappHandleCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this provide xapp handle created response has a 3xx status code
func (o *ProvideXappHandleCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provide xapp handle created response has a 4xx status code
func (o *ProvideXappHandleCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this provide xapp handle created response has a 5xx status code
func (o *ProvideXappHandleCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this provide xapp handle created response a status code equal to that given
func (o *ProvideXappHandleCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the provide xapp handle created response
func (o *ProvideXappHandleCreated) Code() int {
	return 201
}

func (o *ProvideXappHandleCreated) Error() string {
	return fmt.Sprintf("[POST /handles/xapp-handle][%d] provideXappHandleCreated ", 201)
}

func (o *ProvideXappHandleCreated) String() string {
	return fmt.Sprintf("[POST /handles/xapp-handle][%d] provideXappHandleCreated ", 201)
}

func (o *ProvideXappHandleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProvideXappHandleBadRequest creates a ProvideXappHandleBadRequest with default headers values
func NewProvideXappHandleBadRequest() *ProvideXappHandleBadRequest {
	return &ProvideXappHandleBadRequest{}
}

/*
ProvideXappHandleBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type ProvideXappHandleBadRequest struct {
}

// IsSuccess returns true when this provide xapp handle bad request response has a 2xx status code
func (o *ProvideXappHandleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this provide xapp handle bad request response has a 3xx status code
func (o *ProvideXappHandleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provide xapp handle bad request response has a 4xx status code
func (o *ProvideXappHandleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this provide xapp handle bad request response has a 5xx status code
func (o *ProvideXappHandleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this provide xapp handle bad request response a status code equal to that given
func (o *ProvideXappHandleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the provide xapp handle bad request response
func (o *ProvideXappHandleBadRequest) Code() int {
	return 400
}

func (o *ProvideXappHandleBadRequest) Error() string {
	return fmt.Sprintf("[POST /handles/xapp-handle][%d] provideXappHandleBadRequest ", 400)
}

func (o *ProvideXappHandleBadRequest) String() string {
	return fmt.Sprintf("[POST /handles/xapp-handle][%d] provideXappHandleBadRequest ", 400)
}

func (o *ProvideXappHandleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
