// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProvideXappSubscriptionHandleReader is a Reader for the ProvideXappSubscriptionHandle structure.
type ProvideXappSubscriptionHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProvideXappSubscriptionHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProvideXappSubscriptionHandleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewProvideXappSubscriptionHandleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /handles/xapp-subscription-handle] provide_xapp_subscription_handle", response, response.Code())
	}
}

// NewProvideXappSubscriptionHandleCreated creates a ProvideXappSubscriptionHandleCreated with default headers values
func NewProvideXappSubscriptionHandleCreated() *ProvideXappSubscriptionHandleCreated {
	return &ProvideXappSubscriptionHandleCreated{}
}

/*
ProvideXappSubscriptionHandleCreated describes a response with status code 201, with default header values.

Xapp Subscription data received
*/
type ProvideXappSubscriptionHandleCreated struct {
}

// IsSuccess returns true when this provide xapp subscription handle created response has a 2xx status code
func (o *ProvideXappSubscriptionHandleCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this provide xapp subscription handle created response has a 3xx status code
func (o *ProvideXappSubscriptionHandleCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provide xapp subscription handle created response has a 4xx status code
func (o *ProvideXappSubscriptionHandleCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this provide xapp subscription handle created response has a 5xx status code
func (o *ProvideXappSubscriptionHandleCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this provide xapp subscription handle created response a status code equal to that given
func (o *ProvideXappSubscriptionHandleCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the provide xapp subscription handle created response
func (o *ProvideXappSubscriptionHandleCreated) Code() int {
	return 201
}

func (o *ProvideXappSubscriptionHandleCreated) Error() string {
	return fmt.Sprintf("[POST /handles/xapp-subscription-handle][%d] provideXappSubscriptionHandleCreated ", 201)
}

func (o *ProvideXappSubscriptionHandleCreated) String() string {
	return fmt.Sprintf("[POST /handles/xapp-subscription-handle][%d] provideXappSubscriptionHandleCreated ", 201)
}

func (o *ProvideXappSubscriptionHandleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProvideXappSubscriptionHandleBadRequest creates a ProvideXappSubscriptionHandleBadRequest with default headers values
func NewProvideXappSubscriptionHandleBadRequest() *ProvideXappSubscriptionHandleBadRequest {
	return &ProvideXappSubscriptionHandleBadRequest{}
}

/*
ProvideXappSubscriptionHandleBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type ProvideXappSubscriptionHandleBadRequest struct {
}

// IsSuccess returns true when this provide xapp subscription handle bad request response has a 2xx status code
func (o *ProvideXappSubscriptionHandleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this provide xapp subscription handle bad request response has a 3xx status code
func (o *ProvideXappSubscriptionHandleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provide xapp subscription handle bad request response has a 4xx status code
func (o *ProvideXappSubscriptionHandleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this provide xapp subscription handle bad request response has a 5xx status code
func (o *ProvideXappSubscriptionHandleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this provide xapp subscription handle bad request response a status code equal to that given
func (o *ProvideXappSubscriptionHandleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the provide xapp subscription handle bad request response
func (o *ProvideXappSubscriptionHandleBadRequest) Code() int {
	return 400
}

func (o *ProvideXappSubscriptionHandleBadRequest) Error() string {
	return fmt.Sprintf("[POST /handles/xapp-subscription-handle][%d] provideXappSubscriptionHandleBadRequest ", 400)
}

func (o *ProvideXappSubscriptionHandleBadRequest) String() string {
	return fmt.Sprintf("[POST /handles/xapp-subscription-handle][%d] provideXappSubscriptionHandleBadRequest ", 400)
}

func (o *ProvideXappSubscriptionHandleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
