// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// NewUpdateXappSubscriptionHandleParams creates a new UpdateXappSubscriptionHandleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateXappSubscriptionHandleParams() *UpdateXappSubscriptionHandleParams {
	return &UpdateXappSubscriptionHandleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateXappSubscriptionHandleParamsWithTimeout creates a new UpdateXappSubscriptionHandleParams object
// with the ability to set a timeout on a request.
func NewUpdateXappSubscriptionHandleParamsWithTimeout(timeout time.Duration) *UpdateXappSubscriptionHandleParams {
	return &UpdateXappSubscriptionHandleParams{
		timeout: timeout,
	}
}

// NewUpdateXappSubscriptionHandleParamsWithContext creates a new UpdateXappSubscriptionHandleParams object
// with the ability to set a context for a request.
func NewUpdateXappSubscriptionHandleParamsWithContext(ctx context.Context) *UpdateXappSubscriptionHandleParams {
	return &UpdateXappSubscriptionHandleParams{
		Context: ctx,
	}
}

// NewUpdateXappSubscriptionHandleParamsWithHTTPClient creates a new UpdateXappSubscriptionHandleParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateXappSubscriptionHandleParamsWithHTTPClient(client *http.Client) *UpdateXappSubscriptionHandleParams {
	return &UpdateXappSubscriptionHandleParams{
		HTTPClient: client,
	}
}

/*
UpdateXappSubscriptionHandleParams contains all the parameters to send to the API endpoint

	for the update xapp subscription handle operation.

	Typically these are written to a http.Request.
*/
type UpdateXappSubscriptionHandleParams struct {

	/* SubscriptionID.

	   Subscription ID

	   Format: uint16
	*/
	SubscriptionID uint16

	/* XappList.

	   xApp list
	*/
	XappList rtmgr_models.XappList

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update xapp subscription handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateXappSubscriptionHandleParams) WithDefaults() *UpdateXappSubscriptionHandleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update xapp subscription handle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateXappSubscriptionHandleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) WithTimeout(timeout time.Duration) *UpdateXappSubscriptionHandleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) WithContext(ctx context.Context) *UpdateXappSubscriptionHandleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) WithHTTPClient(client *http.Client) *UpdateXappSubscriptionHandleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriptionID adds the subscriptionID to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) WithSubscriptionID(subscriptionID uint16) *UpdateXappSubscriptionHandleParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) SetSubscriptionID(subscriptionID uint16) {
	o.SubscriptionID = subscriptionID
}

// WithXappList adds the xappList to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) WithXappList(xappList rtmgr_models.XappList) *UpdateXappSubscriptionHandleParams {
	o.SetXappList(xappList)
	return o
}

// SetXappList adds the xappList to the update xapp subscription handle params
func (o *UpdateXappSubscriptionHandleParams) SetXappList(xappList rtmgr_models.XappList) {
	o.XappList = xappList
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateXappSubscriptionHandleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subscription_id
	if err := r.SetPathParam("subscription_id", swag.FormatUint16(o.SubscriptionID)); err != nil {
		return err
	}
	if o.XappList != nil {
		if err := r.SetBodyParam(o.XappList); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
