// Code generated by go-swagger; DO NOT EDIT.

package handle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateXappSubscriptionHandleReader is a Reader for the UpdateXappSubscriptionHandle structure.
type UpdateXappSubscriptionHandleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateXappSubscriptionHandleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateXappSubscriptionHandleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateXappSubscriptionHandleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /handles/xapp-subscription-handle/{subscription_id}] update_xapp_subscription_handle", response, response.Code())
	}
}

// NewUpdateXappSubscriptionHandleCreated creates a UpdateXappSubscriptionHandleCreated with default headers values
func NewUpdateXappSubscriptionHandleCreated() *UpdateXappSubscriptionHandleCreated {
	return &UpdateXappSubscriptionHandleCreated{}
}

/*
UpdateXappSubscriptionHandleCreated describes a response with status code 201, with default header values.

Xapp list received
*/
type UpdateXappSubscriptionHandleCreated struct {
}

// IsSuccess returns true when this update xapp subscription handle created response has a 2xx status code
func (o *UpdateXappSubscriptionHandleCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update xapp subscription handle created response has a 3xx status code
func (o *UpdateXappSubscriptionHandleCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update xapp subscription handle created response has a 4xx status code
func (o *UpdateXappSubscriptionHandleCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update xapp subscription handle created response has a 5xx status code
func (o *UpdateXappSubscriptionHandleCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update xapp subscription handle created response a status code equal to that given
func (o *UpdateXappSubscriptionHandleCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update xapp subscription handle created response
func (o *UpdateXappSubscriptionHandleCreated) Code() int {
	return 201
}

func (o *UpdateXappSubscriptionHandleCreated) Error() string {
	return fmt.Sprintf("[PUT /handles/xapp-subscription-handle/{subscription_id}][%d] updateXappSubscriptionHandleCreated ", 201)
}

func (o *UpdateXappSubscriptionHandleCreated) String() string {
	return fmt.Sprintf("[PUT /handles/xapp-subscription-handle/{subscription_id}][%d] updateXappSubscriptionHandleCreated ", 201)
}

func (o *UpdateXappSubscriptionHandleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateXappSubscriptionHandleBadRequest creates a UpdateXappSubscriptionHandleBadRequest with default headers values
func NewUpdateXappSubscriptionHandleBadRequest() *UpdateXappSubscriptionHandleBadRequest {
	return &UpdateXappSubscriptionHandleBadRequest{}
}

/*
UpdateXappSubscriptionHandleBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type UpdateXappSubscriptionHandleBadRequest struct {
}

// IsSuccess returns true when this update xapp subscription handle bad request response has a 2xx status code
func (o *UpdateXappSubscriptionHandleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update xapp subscription handle bad request response has a 3xx status code
func (o *UpdateXappSubscriptionHandleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update xapp subscription handle bad request response has a 4xx status code
func (o *UpdateXappSubscriptionHandleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update xapp subscription handle bad request response has a 5xx status code
func (o *UpdateXappSubscriptionHandleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update xapp subscription handle bad request response a status code equal to that given
func (o *UpdateXappSubscriptionHandleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update xapp subscription handle bad request response
func (o *UpdateXappSubscriptionHandleBadRequest) Code() int {
	return 400
}

func (o *UpdateXappSubscriptionHandleBadRequest) Error() string {
	return fmt.Sprintf("[PUT /handles/xapp-subscription-handle/{subscription_id}][%d] updateXappSubscriptionHandleBadRequest ", 400)
}

func (o *UpdateXappSubscriptionHandleBadRequest) String() string {
	return fmt.Sprintf("[PUT /handles/xapp-subscription-handle/{subscription_id}][%d] updateXappSubscriptionHandleBadRequest ", 400)
}

func (o *UpdateXappSubscriptionHandleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
