// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: e2_related_apis_common_ies_ver_1_2_0.proto

package ricapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------- Information Elements -----------------------------
// --------------E--------------
// From E2AP Clause 9.2.11
type E2ActionType int32

const (
	E2ActionType_E2ACTION_TYPE_REPORT E2ActionType = 0
	E2ActionType_E2ACTION_TYPE_INSERT E2ActionType = 1
	E2ActionType_E2ACTION_TYPE_POLICY E2ActionType = 2
)

// Enum value maps for E2ActionType.
var (
	E2ActionType_name = map[int32]string{
		0: "E2ACTION_TYPE_REPORT",
		1: "E2ACTION_TYPE_INSERT",
		2: "E2ACTION_TYPE_POLICY",
	}
	E2ActionType_value = map[string]int32{
		"E2ACTION_TYPE_REPORT": 0,
		"E2ACTION_TYPE_INSERT": 1,
		"E2ACTION_TYPE_POLICY": 2,
	}
)

func (x E2ActionType) Enum() *E2ActionType {
	p := new(E2ActionType)
	*p = x
	return p
}

func (x E2ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E2ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[0].Descriptor()
}

func (E2ActionType) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[0]
}

func (x E2ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E2ActionType.Descriptor instead.
func (E2ActionType) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0}
}

// From E2AP Clause 9.2.21
type E2ControlAckRequest int32

const (
	E2ControlAckRequest_E2_CONTROL_ACK_REQUEST_NO_ACK E2ControlAckRequest = 0
	E2ControlAckRequest_E2_CONTROL_ACK_REQUEST_ACK    E2ControlAckRequest = 1
)

// Enum value maps for E2ControlAckRequest.
var (
	E2ControlAckRequest_name = map[int32]string{
		0: "E2_CONTROL_ACK_REQUEST_NO_ACK",
		1: "E2_CONTROL_ACK_REQUEST_ACK",
	}
	E2ControlAckRequest_value = map[string]int32{
		"E2_CONTROL_ACK_REQUEST_NO_ACK": 0,
		"E2_CONTROL_ACK_REQUEST_ACK":    1,
	}
)

func (x E2ControlAckRequest) Enum() *E2ControlAckRequest {
	p := new(E2ControlAckRequest)
	*p = x
	return p
}

func (x E2ControlAckRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E2ControlAckRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[1].Descriptor()
}

func (E2ControlAckRequest) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[1]
}

func (x E2ControlAckRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E2ControlAckRequest.Descriptor instead.
func (E2ControlAckRequest) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{1}
}

// From E2AP Clause 9.2.15
type E2IndicationType int32

const (
	E2IndicationType_E2_INDICATION_TYPE_REPORT E2IndicationType = 0
	E2IndicationType_E2_INDICATION_TYPE_INSERT E2IndicationType = 1
)

// Enum value maps for E2IndicationType.
var (
	E2IndicationType_name = map[int32]string{
		0: "E2_INDICATION_TYPE_REPORT",
		1: "E2_INDICATION_TYPE_INSERT",
	}
	E2IndicationType_value = map[string]int32{
		"E2_INDICATION_TYPE_REPORT": 0,
		"E2_INDICATION_TYPE_INSERT": 1,
	}
)

func (x E2IndicationType) Enum() *E2IndicationType {
	p := new(E2IndicationType)
	*p = x
	return p
}

func (x E2IndicationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E2IndicationType) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[2].Descriptor()
}

func (E2IndicationType) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[2]
}

func (x E2IndicationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E2IndicationType.Descriptor instead.
func (E2IndicationType) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{2}
}

type Cause_E2ApCause_E2Node int32

const (
	Cause_E2ApCause_E2NODE_COMPONENT_UNKNOWN Cause_E2ApCause_E2Node = 0
)

// Enum value maps for Cause_E2ApCause_E2Node.
var (
	Cause_E2ApCause_E2Node_name = map[int32]string{
		0: "E2NODE_COMPONENT_UNKNOWN",
	}
	Cause_E2ApCause_E2Node_value = map[string]int32{
		"E2NODE_COMPONENT_UNKNOWN": 0,
	}
)

func (x Cause_E2ApCause_E2Node) Enum() *Cause_E2ApCause_E2Node {
	p := new(Cause_E2ApCause_E2Node)
	*p = x
	return p
}

func (x Cause_E2ApCause_E2Node) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2ApCause_E2Node) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[3].Descriptor()
}

func (Cause_E2ApCause_E2Node) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[3]
}

func (x Cause_E2ApCause_E2Node) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2ApCause_E2Node.Descriptor instead.
func (Cause_E2ApCause_E2Node) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Cause_E2ApCause_Misc int32

const (
	Cause_E2ApCause_CONTROL_PROCESSING_OVERLOAD Cause_E2ApCause_Misc = 0
	Cause_E2ApCause_HARDWARE_FAILURE            Cause_E2ApCause_Misc = 1
	Cause_E2ApCause_OM_INTERVENTION             Cause_E2ApCause_Misc = 2
	Cause_E2ApCause_MISC_UNSPECIFIED            Cause_E2ApCause_Misc = 3
)

// Enum value maps for Cause_E2ApCause_Misc.
var (
	Cause_E2ApCause_Misc_name = map[int32]string{
		0: "CONTROL_PROCESSING_OVERLOAD",
		1: "HARDWARE_FAILURE",
		2: "OM_INTERVENTION",
		3: "MISC_UNSPECIFIED",
	}
	Cause_E2ApCause_Misc_value = map[string]int32{
		"CONTROL_PROCESSING_OVERLOAD": 0,
		"HARDWARE_FAILURE":            1,
		"OM_INTERVENTION":             2,
		"MISC_UNSPECIFIED":            3,
	}
)

func (x Cause_E2ApCause_Misc) Enum() *Cause_E2ApCause_Misc {
	p := new(Cause_E2ApCause_Misc)
	*p = x
	return p
}

func (x Cause_E2ApCause_Misc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2ApCause_Misc) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[4].Descriptor()
}

func (Cause_E2ApCause_Misc) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[4]
}

func (x Cause_E2ApCause_Misc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2ApCause_Misc.Descriptor instead.
func (Cause_E2ApCause_Misc) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0, 1}
}

type Cause_E2ApCause_Protocol int32

const (
	Cause_E2ApCause_TRANSFER_SYNTAX_ERROR                             Cause_E2ApCause_Protocol = 0
	Cause_E2ApCause_ABSTRACT_SYNTAX_ERROR_REJECT                      Cause_E2ApCause_Protocol = 1
	Cause_E2ApCause_ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY           Cause_E2ApCause_Protocol = 2
	Cause_E2ApCause_MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE        Cause_E2ApCause_Protocol = 3
	Cause_E2ApCause_SEMANTIC_ERROR                                    Cause_E2ApCause_Protocol = 4
	Cause_E2ApCause_ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE Cause_E2ApCause_Protocol = 5
	Cause_E2ApCause_PROTOCOL_UNSPECIFIED                              Cause_E2ApCause_Protocol = 6
)

// Enum value maps for Cause_E2ApCause_Protocol.
var (
	Cause_E2ApCause_Protocol_name = map[int32]string{
		0: "TRANSFER_SYNTAX_ERROR",
		1: "ABSTRACT_SYNTAX_ERROR_REJECT",
		2: "ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY",
		3: "MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE",
		4: "SEMANTIC_ERROR",
		5: "ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE",
		6: "PROTOCOL_UNSPECIFIED",
	}
	Cause_E2ApCause_Protocol_value = map[string]int32{
		"TRANSFER_SYNTAX_ERROR":                             0,
		"ABSTRACT_SYNTAX_ERROR_REJECT":                      1,
		"ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY":           2,
		"MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE":        3,
		"SEMANTIC_ERROR":                                    4,
		"ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE": 5,
		"PROTOCOL_UNSPECIFIED":                              6,
	}
)

func (x Cause_E2ApCause_Protocol) Enum() *Cause_E2ApCause_Protocol {
	p := new(Cause_E2ApCause_Protocol)
	*p = x
	return p
}

func (x Cause_E2ApCause_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2ApCause_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[5].Descriptor()
}

func (Cause_E2ApCause_Protocol) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[5]
}

func (x Cause_E2ApCause_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2ApCause_Protocol.Descriptor instead.
func (Cause_E2ApCause_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0, 2}
}

type Cause_E2ApCause_RicRequest int32

const (
	Cause_E2ApCause_RAN_FUNCTION_ID_INVALID                        Cause_E2ApCause_RicRequest = 0
	Cause_E2ApCause_ACTION_NOT_SUPPORTED                           Cause_E2ApCause_RicRequest = 1
	Cause_E2ApCause_EXCESSIVE_ACTIONS                              Cause_E2ApCause_RicRequest = 2
	Cause_E2ApCause_DUPLICATE_ACTION                               Cause_E2ApCause_RicRequest = 3
	Cause_E2ApCause_DUPLICATE_EVENT_TRIGGER                        Cause_E2ApCause_RicRequest = 4
	Cause_E2ApCause_FUNCTION_RESOURCE_LIMIT                        Cause_E2ApCause_RicRequest = 5
	Cause_E2ApCause_REQUEST_ID_UNKNOWN                             Cause_E2ApCause_RicRequest = 6
	Cause_E2ApCause_INCONSISTENT_ACTION_SUBSEQUENT_ACTION_SEQUENCE Cause_E2ApCause_RicRequest = 7
	Cause_E2ApCause_CONTROL_MESSAGE_INVALID                        Cause_E2ApCause_RicRequest = 8
	Cause_E2ApCause_RIC_CALL_PROCESS_ID_INVALID                    Cause_E2ApCause_RicRequest = 9
	Cause_E2ApCause_CONTROL_TIMER_EXPIRED                          Cause_E2ApCause_RicRequest = 10
	Cause_E2ApCause_CONTROL_FAILED_TO_EXECUTE                      Cause_E2ApCause_RicRequest = 11
	Cause_E2ApCause_SYSTEM_NOT_READY                               Cause_E2ApCause_RicRequest = 12
	Cause_E2ApCause_RIC_REQUEST_UNSPECIFIED                        Cause_E2ApCause_RicRequest = 13
)

// Enum value maps for Cause_E2ApCause_RicRequest.
var (
	Cause_E2ApCause_RicRequest_name = map[int32]string{
		0:  "RAN_FUNCTION_ID_INVALID",
		1:  "ACTION_NOT_SUPPORTED",
		2:  "EXCESSIVE_ACTIONS",
		3:  "DUPLICATE_ACTION",
		4:  "DUPLICATE_EVENT_TRIGGER",
		5:  "FUNCTION_RESOURCE_LIMIT",
		6:  "REQUEST_ID_UNKNOWN",
		7:  "INCONSISTENT_ACTION_SUBSEQUENT_ACTION_SEQUENCE",
		8:  "CONTROL_MESSAGE_INVALID",
		9:  "RIC_CALL_PROCESS_ID_INVALID",
		10: "CONTROL_TIMER_EXPIRED",
		11: "CONTROL_FAILED_TO_EXECUTE",
		12: "SYSTEM_NOT_READY",
		13: "RIC_REQUEST_UNSPECIFIED",
	}
	Cause_E2ApCause_RicRequest_value = map[string]int32{
		"RAN_FUNCTION_ID_INVALID":                        0,
		"ACTION_NOT_SUPPORTED":                           1,
		"EXCESSIVE_ACTIONS":                              2,
		"DUPLICATE_ACTION":                               3,
		"DUPLICATE_EVENT_TRIGGER":                        4,
		"FUNCTION_RESOURCE_LIMIT":                        5,
		"REQUEST_ID_UNKNOWN":                             6,
		"INCONSISTENT_ACTION_SUBSEQUENT_ACTION_SEQUENCE": 7,
		"CONTROL_MESSAGE_INVALID":                        8,
		"RIC_CALL_PROCESS_ID_INVALID":                    9,
		"CONTROL_TIMER_EXPIRED":                          10,
		"CONTROL_FAILED_TO_EXECUTE":                      11,
		"SYSTEM_NOT_READY":                               12,
		"RIC_REQUEST_UNSPECIFIED":                        13,
	}
)

func (x Cause_E2ApCause_RicRequest) Enum() *Cause_E2ApCause_RicRequest {
	p := new(Cause_E2ApCause_RicRequest)
	*p = x
	return p
}

func (x Cause_E2ApCause_RicRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2ApCause_RicRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[6].Descriptor()
}

func (Cause_E2ApCause_RicRequest) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[6]
}

func (x Cause_E2ApCause_RicRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2ApCause_RicRequest.Descriptor instead.
func (Cause_E2ApCause_RicRequest) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0, 3}
}

type Cause_E2ApCause_RicService int32

const (
	Cause_E2ApCause_RAN_FUNCTION_NOT_SUPPORTED Cause_E2ApCause_RicService = 0
	Cause_E2ApCause_EXCESSIVE_FUNCTIONS        Cause_E2ApCause_RicService = 1
	Cause_E2ApCause_RIC_RESOURCE_LIMIT         Cause_E2ApCause_RicService = 2
)

// Enum value maps for Cause_E2ApCause_RicService.
var (
	Cause_E2ApCause_RicService_name = map[int32]string{
		0: "RAN_FUNCTION_NOT_SUPPORTED",
		1: "EXCESSIVE_FUNCTIONS",
		2: "RIC_RESOURCE_LIMIT",
	}
	Cause_E2ApCause_RicService_value = map[string]int32{
		"RAN_FUNCTION_NOT_SUPPORTED": 0,
		"EXCESSIVE_FUNCTIONS":        1,
		"RIC_RESOURCE_LIMIT":         2,
	}
)

func (x Cause_E2ApCause_RicService) Enum() *Cause_E2ApCause_RicService {
	p := new(Cause_E2ApCause_RicService)
	*p = x
	return p
}

func (x Cause_E2ApCause_RicService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2ApCause_RicService) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[7].Descriptor()
}

func (Cause_E2ApCause_RicService) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[7]
}

func (x Cause_E2ApCause_RicService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2ApCause_RicService.Descriptor instead.
func (Cause_E2ApCause_RicService) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0, 4}
}

type Cause_E2ApCause_Transport int32

const (
	Cause_E2ApCause_TRANSPORT_UNSPECIFIED          Cause_E2ApCause_Transport = 0
	Cause_E2ApCause_TRANSPORT_RESOURCE_UNAVAILABLE Cause_E2ApCause_Transport = 1
)

// Enum value maps for Cause_E2ApCause_Transport.
var (
	Cause_E2ApCause_Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_RESOURCE_UNAVAILABLE",
	}
	Cause_E2ApCause_Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED":          0,
		"TRANSPORT_RESOURCE_UNAVAILABLE": 1,
	}
)

func (x Cause_E2ApCause_Transport) Enum() *Cause_E2ApCause_Transport {
	p := new(Cause_E2ApCause_Transport)
	*p = x
	return p
}

func (x Cause_E2ApCause_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2ApCause_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[8].Descriptor()
}

func (Cause_E2ApCause_Transport) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[8]
}

func (x Cause_E2ApCause_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2ApCause_Transport.Descriptor instead.
func (Cause_E2ApCause_Transport) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0, 5}
}

type Cause_E2RelatedApiCause_ApplicationLayer int32

const (
	Cause_E2RelatedApiCause_APPLICATION_LAYER_UNSPECIFIED Cause_E2RelatedApiCause_ApplicationLayer = 0
	Cause_E2RelatedApiCause_GLOBAL_E2_NODE_ID_INVALID     Cause_E2RelatedApiCause_ApplicationLayer = 1
	Cause_E2RelatedApiCause_E2_NODE_RESET_OR_DISCONNECTED Cause_E2RelatedApiCause_ApplicationLayer = 2
	Cause_E2RelatedApiCause_RAN_FUNCTION_ID_INVALID       Cause_E2RelatedApiCause_ApplicationLayer = 3
	Cause_E2RelatedApiCause_ACTION_NOT_SUPPORTED          Cause_E2RelatedApiCause_ApplicationLayer = 4
	Cause_E2RelatedApiCause_EXCESSIVE_ACTIONS             Cause_E2RelatedApiCause_ApplicationLayer = 5
	Cause_E2RelatedApiCause_DUPLICATE_ACTION              Cause_E2RelatedApiCause_ApplicationLayer = 6
	Cause_E2RelatedApiCause_E2_REQUEST_ID_UNKNOWN         Cause_E2RelatedApiCause_ApplicationLayer = 7
	Cause_E2RelatedApiCause_CONTROL_CONFLICT              Cause_E2RelatedApiCause_ApplicationLayer = 8
	Cause_E2RelatedApiCause_E2_INDICATION_UNKNOWN         Cause_E2RelatedApiCause_ApplicationLayer = 9
	Cause_E2RelatedApiCause_E2AP_PROCEDURE_TIMEOUT        Cause_E2RelatedApiCause_ApplicationLayer = 10
	Cause_E2RelatedApiCause_ESSENTIAL_FOR_OPERATION       Cause_E2RelatedApiCause_ApplicationLayer = 11
)

// Enum value maps for Cause_E2RelatedApiCause_ApplicationLayer.
var (
	Cause_E2RelatedApiCause_ApplicationLayer_name = map[int32]string{
		0:  "APPLICATION_LAYER_UNSPECIFIED",
		1:  "GLOBAL_E2_NODE_ID_INVALID",
		2:  "E2_NODE_RESET_OR_DISCONNECTED",
		3:  "RAN_FUNCTION_ID_INVALID",
		4:  "ACTION_NOT_SUPPORTED",
		5:  "EXCESSIVE_ACTIONS",
		6:  "DUPLICATE_ACTION",
		7:  "E2_REQUEST_ID_UNKNOWN",
		8:  "CONTROL_CONFLICT",
		9:  "E2_INDICATION_UNKNOWN",
		10: "E2AP_PROCEDURE_TIMEOUT",
		11: "ESSENTIAL_FOR_OPERATION",
	}
	Cause_E2RelatedApiCause_ApplicationLayer_value = map[string]int32{
		"APPLICATION_LAYER_UNSPECIFIED": 0,
		"GLOBAL_E2_NODE_ID_INVALID":     1,
		"E2_NODE_RESET_OR_DISCONNECTED": 2,
		"RAN_FUNCTION_ID_INVALID":       3,
		"ACTION_NOT_SUPPORTED":          4,
		"EXCESSIVE_ACTIONS":             5,
		"DUPLICATE_ACTION":              6,
		"E2_REQUEST_ID_UNKNOWN":         7,
		"CONTROL_CONFLICT":              8,
		"E2_INDICATION_UNKNOWN":         9,
		"E2AP_PROCEDURE_TIMEOUT":        10,
		"ESSENTIAL_FOR_OPERATION":       11,
	}
)

func (x Cause_E2RelatedApiCause_ApplicationLayer) Enum() *Cause_E2RelatedApiCause_ApplicationLayer {
	p := new(Cause_E2RelatedApiCause_ApplicationLayer)
	*p = x
	return p
}

func (x Cause_E2RelatedApiCause_ApplicationLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2RelatedApiCause_ApplicationLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[9].Descriptor()
}

func (Cause_E2RelatedApiCause_ApplicationLayer) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[9]
}

func (x Cause_E2RelatedApiCause_ApplicationLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2RelatedApiCause_ApplicationLayer.Descriptor instead.
func (Cause_E2RelatedApiCause_ApplicationLayer) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Cause_E2RelatedApiCause_Misc int32

const (
	Cause_E2RelatedApiCause_MISC_UNSPECIFIED            Cause_E2RelatedApiCause_Misc = 0
	Cause_E2RelatedApiCause_CONTROL_PROCESSING_OVERLOAD Cause_E2RelatedApiCause_Misc = 1
	Cause_E2RelatedApiCause_HARDWARE_FAILURE            Cause_E2RelatedApiCause_Misc = 2
	Cause_E2RelatedApiCause_OM_INTERVENTION             Cause_E2RelatedApiCause_Misc = 3
)

// Enum value maps for Cause_E2RelatedApiCause_Misc.
var (
	Cause_E2RelatedApiCause_Misc_name = map[int32]string{
		0: "MISC_UNSPECIFIED",
		1: "CONTROL_PROCESSING_OVERLOAD",
		2: "HARDWARE_FAILURE",
		3: "OM_INTERVENTION",
	}
	Cause_E2RelatedApiCause_Misc_value = map[string]int32{
		"MISC_UNSPECIFIED":            0,
		"CONTROL_PROCESSING_OVERLOAD": 1,
		"HARDWARE_FAILURE":            2,
		"OM_INTERVENTION":             3,
	}
)

func (x Cause_E2RelatedApiCause_Misc) Enum() *Cause_E2RelatedApiCause_Misc {
	p := new(Cause_E2RelatedApiCause_Misc)
	*p = x
	return p
}

func (x Cause_E2RelatedApiCause_Misc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2RelatedApiCause_Misc) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[10].Descriptor()
}

func (Cause_E2RelatedApiCause_Misc) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[10]
}

func (x Cause_E2RelatedApiCause_Misc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2RelatedApiCause_Misc.Descriptor instead.
func (Cause_E2RelatedApiCause_Misc) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 1, 1}
}

type Cause_E2RelatedApiCause_Protocol int32

const (
	Cause_E2RelatedApiCause_PROTOCOL_UNSPECIFIED                              Cause_E2RelatedApiCause_Protocol = 0
	Cause_E2RelatedApiCause_TRANSFER_SYNTAX_ERROR                             Cause_E2RelatedApiCause_Protocol = 1
	Cause_E2RelatedApiCause_ABSTRACT_SYNTAX_ERROR_REJECT                      Cause_E2RelatedApiCause_Protocol = 2
	Cause_E2RelatedApiCause_ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY           Cause_E2RelatedApiCause_Protocol = 3
	Cause_E2RelatedApiCause_MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE        Cause_E2RelatedApiCause_Protocol = 4
	Cause_E2RelatedApiCause_SEMANTIC_ERROR                                    Cause_E2RelatedApiCause_Protocol = 5
	Cause_E2RelatedApiCause_ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE Cause_E2RelatedApiCause_Protocol = 6
)

// Enum value maps for Cause_E2RelatedApiCause_Protocol.
var (
	Cause_E2RelatedApiCause_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "TRANSFER_SYNTAX_ERROR",
		2: "ABSTRACT_SYNTAX_ERROR_REJECT",
		3: "ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY",
		4: "MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE",
		5: "SEMANTIC_ERROR",
		6: "ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE",
	}
	Cause_E2RelatedApiCause_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":                              0,
		"TRANSFER_SYNTAX_ERROR":                             1,
		"ABSTRACT_SYNTAX_ERROR_REJECT":                      2,
		"ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY":           3,
		"MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE":        4,
		"SEMANTIC_ERROR":                                    5,
		"ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE": 6,
	}
)

func (x Cause_E2RelatedApiCause_Protocol) Enum() *Cause_E2RelatedApiCause_Protocol {
	p := new(Cause_E2RelatedApiCause_Protocol)
	*p = x
	return p
}

func (x Cause_E2RelatedApiCause_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2RelatedApiCause_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[11].Descriptor()
}

func (Cause_E2RelatedApiCause_Protocol) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[11]
}

func (x Cause_E2RelatedApiCause_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2RelatedApiCause_Protocol.Descriptor instead.
func (Cause_E2RelatedApiCause_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 1, 2}
}

type Cause_E2RelatedApiCause_Transport int32

const (
	Cause_E2RelatedApiCause_TRANSPORT_UNSPECIFIED          Cause_E2RelatedApiCause_Transport = 0
	Cause_E2RelatedApiCause_TRANSPORT_RESOURCE_UNAVAILABLE Cause_E2RelatedApiCause_Transport = 1
)

// Enum value maps for Cause_E2RelatedApiCause_Transport.
var (
	Cause_E2RelatedApiCause_Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_RESOURCE_UNAVAILABLE",
	}
	Cause_E2RelatedApiCause_Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED":          0,
		"TRANSPORT_RESOURCE_UNAVAILABLE": 1,
	}
)

func (x Cause_E2RelatedApiCause_Transport) Enum() *Cause_E2RelatedApiCause_Transport {
	p := new(Cause_E2RelatedApiCause_Transport)
	*p = x
	return p
}

func (x Cause_E2RelatedApiCause_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause_E2RelatedApiCause_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[12].Descriptor()
}

func (Cause_E2RelatedApiCause_Transport) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[12]
}

func (x Cause_E2RelatedApiCause_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause_E2RelatedApiCause_Transport.Descriptor instead.
func (Cause_E2RelatedApiCause_Transport) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 1, 3}
}

type CriticalityDiagnostics_IeCriticality int32

const (
	CriticalityDiagnostics_IE_CRITICALITY_REJECT CriticalityDiagnostics_IeCriticality = 0
	CriticalityDiagnostics_IE_CRITICALITY_IGNORE CriticalityDiagnostics_IeCriticality = 1
	CriticalityDiagnostics_IE_CRITICALITY_NOTIFY CriticalityDiagnostics_IeCriticality = 2
)

// Enum value maps for CriticalityDiagnostics_IeCriticality.
var (
	CriticalityDiagnostics_IeCriticality_name = map[int32]string{
		0: "IE_CRITICALITY_REJECT",
		1: "IE_CRITICALITY_IGNORE",
		2: "IE_CRITICALITY_NOTIFY",
	}
	CriticalityDiagnostics_IeCriticality_value = map[string]int32{
		"IE_CRITICALITY_REJECT": 0,
		"IE_CRITICALITY_IGNORE": 1,
		"IE_CRITICALITY_NOTIFY": 2,
	}
)

func (x CriticalityDiagnostics_IeCriticality) Enum() *CriticalityDiagnostics_IeCriticality {
	p := new(CriticalityDiagnostics_IeCriticality)
	*p = x
	return p
}

func (x CriticalityDiagnostics_IeCriticality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CriticalityDiagnostics_IeCriticality) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[13].Descriptor()
}

func (CriticalityDiagnostics_IeCriticality) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[13]
}

func (x CriticalityDiagnostics_IeCriticality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CriticalityDiagnostics_IeCriticality.Descriptor instead.
func (CriticalityDiagnostics_IeCriticality) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{1, 0}
}

type CriticalityDiagnostics_IeId int32

const (
	CriticalityDiagnostics_IE_ID_CAUSE                        CriticalityDiagnostics_IeId = 0
	CriticalityDiagnostics_IE_ID_CRITICALITY_DIAGNOSTICS      CriticalityDiagnostics_IeId = 1
	CriticalityDiagnostics_IE_ID_E2_ACTION_ID                 CriticalityDiagnostics_IeId = 2
	CriticalityDiagnostics_IE_ID_E2_ACTIONS_ADMITTED_LIST     CriticalityDiagnostics_IeId = 3
	CriticalityDiagnostics_IE_ID_E2_ACTIONS_NOT_ADMITTED_LIST CriticalityDiagnostics_IeId = 4
	CriticalityDiagnostics_IE_ID_E2_CALL_PROCESS_ID           CriticalityDiagnostics_IeId = 5
	CriticalityDiagnostics_IE_ID_E2_CONTROL_ACK_REQUEST       CriticalityDiagnostics_IeId = 6
	CriticalityDiagnostics_IE_ID_E2_CONTROL_HEADER            CriticalityDiagnostics_IeId = 7
	CriticalityDiagnostics_IE_ID_E2_CONTROL_MESSAGE           CriticalityDiagnostics_IeId = 8
	CriticalityDiagnostics_IE_ID_E2_CONTROL_OUTCOME           CriticalityDiagnostics_IeId = 9
	CriticalityDiagnostics_IE_ID_E2_CONTROL_TIMER             CriticalityDiagnostics_IeId = 10
	CriticalityDiagnostics_IE_ID_E2_INDICATION_HEADER         CriticalityDiagnostics_IeId = 11
	CriticalityDiagnostics_IE_ID_E2_INDICATION_MESSAGE        CriticalityDiagnostics_IeId = 12
	CriticalityDiagnostics_IE_ID_E2_INDICATION_SN             CriticalityDiagnostics_IeId = 13
	CriticalityDiagnostics_IE_ID_E2_INDICATION_TYPE           CriticalityDiagnostics_IeId = 14
	CriticalityDiagnostics_IE_ID_E2_REQUEST_ID                CriticalityDiagnostics_IeId = 15
	CriticalityDiagnostics_IE_ID_E2_SUBSCRIPTION_DETAILS      CriticalityDiagnostics_IeId = 16
	CriticalityDiagnostics_IE_ID_GLOBAL_E2_NODE_ID            CriticalityDiagnostics_IeId = 17
	CriticalityDiagnostics_IE_ID_PROCEDURE_TRANSACTION_ID     CriticalityDiagnostics_IeId = 18
	CriticalityDiagnostics_IE_ID_RAN_FUNCTION_ID              CriticalityDiagnostics_IeId = 19
	CriticalityDiagnostics_IE_ID_SEQUENCE_OF_ACTIONS          CriticalityDiagnostics_IeId = 20
	CriticalityDiagnostics_IE_ID_E2_SUBSCRIPTION_TIMER        CriticalityDiagnostics_IeId = 21
	CriticalityDiagnostics_IE_ID_E2_SUBSCRIPTION_DELETE_TIMER CriticalityDiagnostics_IeId = 22
)

// Enum value maps for CriticalityDiagnostics_IeId.
var (
	CriticalityDiagnostics_IeId_name = map[int32]string{
		0:  "IE_ID_CAUSE",
		1:  "IE_ID_CRITICALITY_DIAGNOSTICS",
		2:  "IE_ID_E2_ACTION_ID",
		3:  "IE_ID_E2_ACTIONS_ADMITTED_LIST",
		4:  "IE_ID_E2_ACTIONS_NOT_ADMITTED_LIST",
		5:  "IE_ID_E2_CALL_PROCESS_ID",
		6:  "IE_ID_E2_CONTROL_ACK_REQUEST",
		7:  "IE_ID_E2_CONTROL_HEADER",
		8:  "IE_ID_E2_CONTROL_MESSAGE",
		9:  "IE_ID_E2_CONTROL_OUTCOME",
		10: "IE_ID_E2_CONTROL_TIMER",
		11: "IE_ID_E2_INDICATION_HEADER",
		12: "IE_ID_E2_INDICATION_MESSAGE",
		13: "IE_ID_E2_INDICATION_SN",
		14: "IE_ID_E2_INDICATION_TYPE",
		15: "IE_ID_E2_REQUEST_ID",
		16: "IE_ID_E2_SUBSCRIPTION_DETAILS",
		17: "IE_ID_GLOBAL_E2_NODE_ID",
		18: "IE_ID_PROCEDURE_TRANSACTION_ID",
		19: "IE_ID_RAN_FUNCTION_ID",
		20: "IE_ID_SEQUENCE_OF_ACTIONS",
		21: "IE_ID_E2_SUBSCRIPTION_TIMER",
		22: "IE_ID_E2_SUBSCRIPTION_DELETE_TIMER",
	}
	CriticalityDiagnostics_IeId_value = map[string]int32{
		"IE_ID_CAUSE":                        0,
		"IE_ID_CRITICALITY_DIAGNOSTICS":      1,
		"IE_ID_E2_ACTION_ID":                 2,
		"IE_ID_E2_ACTIONS_ADMITTED_LIST":     3,
		"IE_ID_E2_ACTIONS_NOT_ADMITTED_LIST": 4,
		"IE_ID_E2_CALL_PROCESS_ID":           5,
		"IE_ID_E2_CONTROL_ACK_REQUEST":       6,
		"IE_ID_E2_CONTROL_HEADER":            7,
		"IE_ID_E2_CONTROL_MESSAGE":           8,
		"IE_ID_E2_CONTROL_OUTCOME":           9,
		"IE_ID_E2_CONTROL_TIMER":             10,
		"IE_ID_E2_INDICATION_HEADER":         11,
		"IE_ID_E2_INDICATION_MESSAGE":        12,
		"IE_ID_E2_INDICATION_SN":             13,
		"IE_ID_E2_INDICATION_TYPE":           14,
		"IE_ID_E2_REQUEST_ID":                15,
		"IE_ID_E2_SUBSCRIPTION_DETAILS":      16,
		"IE_ID_GLOBAL_E2_NODE_ID":            17,
		"IE_ID_PROCEDURE_TRANSACTION_ID":     18,
		"IE_ID_RAN_FUNCTION_ID":              19,
		"IE_ID_SEQUENCE_OF_ACTIONS":          20,
		"IE_ID_E2_SUBSCRIPTION_TIMER":        21,
		"IE_ID_E2_SUBSCRIPTION_DELETE_TIMER": 22,
	}
)

func (x CriticalityDiagnostics_IeId) Enum() *CriticalityDiagnostics_IeId {
	p := new(CriticalityDiagnostics_IeId)
	*p = x
	return p
}

func (x CriticalityDiagnostics_IeId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CriticalityDiagnostics_IeId) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[14].Descriptor()
}

func (CriticalityDiagnostics_IeId) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[14]
}

func (x CriticalityDiagnostics_IeId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CriticalityDiagnostics_IeId.Descriptor instead.
func (CriticalityDiagnostics_IeId) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{1, 1}
}

type CriticalityDiagnostics_TypeOfError int32

const (
	CriticalityDiagnostics_TYPE_OF_ERROR_NOT_UNDERSTOOD CriticalityDiagnostics_TypeOfError = 0
	CriticalityDiagnostics_TYPE_OF_ERROR_MISSING        CriticalityDiagnostics_TypeOfError = 1
)

// Enum value maps for CriticalityDiagnostics_TypeOfError.
var (
	CriticalityDiagnostics_TypeOfError_name = map[int32]string{
		0: "TYPE_OF_ERROR_NOT_UNDERSTOOD",
		1: "TYPE_OF_ERROR_MISSING",
	}
	CriticalityDiagnostics_TypeOfError_value = map[string]int32{
		"TYPE_OF_ERROR_NOT_UNDERSTOOD": 0,
		"TYPE_OF_ERROR_MISSING":        1,
	}
)

func (x CriticalityDiagnostics_TypeOfError) Enum() *CriticalityDiagnostics_TypeOfError {
	p := new(CriticalityDiagnostics_TypeOfError)
	*p = x
	return p
}

func (x CriticalityDiagnostics_TypeOfError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CriticalityDiagnostics_TypeOfError) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[15].Descriptor()
}

func (CriticalityDiagnostics_TypeOfError) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[15]
}

func (x CriticalityDiagnostics_TypeOfError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CriticalityDiagnostics_TypeOfError.Descriptor instead.
func (CriticalityDiagnostics_TypeOfError) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{1, 2}
}

type E2SubsequentAction_SubsequentActionType int32

const (
	E2SubsequentAction_SUBSEQUENT_ACTION_TYPE_CONTINUE E2SubsequentAction_SubsequentActionType = 0
	E2SubsequentAction_SUBSEQUENT_ACTION_TYPE_WAIT     E2SubsequentAction_SubsequentActionType = 1
)

// Enum value maps for E2SubsequentAction_SubsequentActionType.
var (
	E2SubsequentAction_SubsequentActionType_name = map[int32]string{
		0: "SUBSEQUENT_ACTION_TYPE_CONTINUE",
		1: "SUBSEQUENT_ACTION_TYPE_WAIT",
	}
	E2SubsequentAction_SubsequentActionType_value = map[string]int32{
		"SUBSEQUENT_ACTION_TYPE_CONTINUE": 0,
		"SUBSEQUENT_ACTION_TYPE_WAIT":     1,
	}
)

func (x E2SubsequentAction_SubsequentActionType) Enum() *E2SubsequentAction_SubsequentActionType {
	p := new(E2SubsequentAction_SubsequentActionType)
	*p = x
	return p
}

func (x E2SubsequentAction_SubsequentActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E2SubsequentAction_SubsequentActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[16].Descriptor()
}

func (E2SubsequentAction_SubsequentActionType) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[16]
}

func (x E2SubsequentAction_SubsequentActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E2SubsequentAction_SubsequentActionType.Descriptor instead.
func (E2SubsequentAction_SubsequentActionType) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{16, 0}
}

type E2SubsequentAction_TimeToWait int32

const (
	E2SubsequentAction_TIME_TO_WAIT_W1MS   E2SubsequentAction_TimeToWait = 0
	E2SubsequentAction_TIME_TO_WAIT_W2MS   E2SubsequentAction_TimeToWait = 1
	E2SubsequentAction_TIME_TO_WAIT_W5MS   E2SubsequentAction_TimeToWait = 2
	E2SubsequentAction_TIME_TO_WAIT_W10MS  E2SubsequentAction_TimeToWait = 3
	E2SubsequentAction_TIME_TO_WAIT_W20MS  E2SubsequentAction_TimeToWait = 4
	E2SubsequentAction_TIME_TO_WAIT_W30MS  E2SubsequentAction_TimeToWait = 5
	E2SubsequentAction_TIME_TO_WAIT_W40MS  E2SubsequentAction_TimeToWait = 6
	E2SubsequentAction_TIME_TO_WAIT_W50MS  E2SubsequentAction_TimeToWait = 7
	E2SubsequentAction_TIME_TO_WAIT_W100MS E2SubsequentAction_TimeToWait = 8
	E2SubsequentAction_TIME_TO_WAIT_W200MS E2SubsequentAction_TimeToWait = 9
	E2SubsequentAction_TIME_TO_WAIT_W500MS E2SubsequentAction_TimeToWait = 10
	E2SubsequentAction_TIME_TO_WAIT_W1S    E2SubsequentAction_TimeToWait = 11
	E2SubsequentAction_TIME_TO_WAIT_W2S    E2SubsequentAction_TimeToWait = 12
	E2SubsequentAction_TIME_TO_WAIT_W5S    E2SubsequentAction_TimeToWait = 13
	E2SubsequentAction_TIME_TO_WAIT_W10S   E2SubsequentAction_TimeToWait = 14
	E2SubsequentAction_TIME_TO_WAIT_W20S   E2SubsequentAction_TimeToWait = 15
	E2SubsequentAction_TIME_TO_WAIT_W60S   E2SubsequentAction_TimeToWait = 16
)

// Enum value maps for E2SubsequentAction_TimeToWait.
var (
	E2SubsequentAction_TimeToWait_name = map[int32]string{
		0:  "TIME_TO_WAIT_W1MS",
		1:  "TIME_TO_WAIT_W2MS",
		2:  "TIME_TO_WAIT_W5MS",
		3:  "TIME_TO_WAIT_W10MS",
		4:  "TIME_TO_WAIT_W20MS",
		5:  "TIME_TO_WAIT_W30MS",
		6:  "TIME_TO_WAIT_W40MS",
		7:  "TIME_TO_WAIT_W50MS",
		8:  "TIME_TO_WAIT_W100MS",
		9:  "TIME_TO_WAIT_W200MS",
		10: "TIME_TO_WAIT_W500MS",
		11: "TIME_TO_WAIT_W1S",
		12: "TIME_TO_WAIT_W2S",
		13: "TIME_TO_WAIT_W5S",
		14: "TIME_TO_WAIT_W10S",
		15: "TIME_TO_WAIT_W20S",
		16: "TIME_TO_WAIT_W60S",
	}
	E2SubsequentAction_TimeToWait_value = map[string]int32{
		"TIME_TO_WAIT_W1MS":   0,
		"TIME_TO_WAIT_W2MS":   1,
		"TIME_TO_WAIT_W5MS":   2,
		"TIME_TO_WAIT_W10MS":  3,
		"TIME_TO_WAIT_W20MS":  4,
		"TIME_TO_WAIT_W30MS":  5,
		"TIME_TO_WAIT_W40MS":  6,
		"TIME_TO_WAIT_W50MS":  7,
		"TIME_TO_WAIT_W100MS": 8,
		"TIME_TO_WAIT_W200MS": 9,
		"TIME_TO_WAIT_W500MS": 10,
		"TIME_TO_WAIT_W1S":    11,
		"TIME_TO_WAIT_W2S":    12,
		"TIME_TO_WAIT_W5S":    13,
		"TIME_TO_WAIT_W10S":   14,
		"TIME_TO_WAIT_W20S":   15,
		"TIME_TO_WAIT_W60S":   16,
	}
)

func (x E2SubsequentAction_TimeToWait) Enum() *E2SubsequentAction_TimeToWait {
	p := new(E2SubsequentAction_TimeToWait)
	*p = x
	return p
}

func (x E2SubsequentAction_TimeToWait) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E2SubsequentAction_TimeToWait) Descriptor() protoreflect.EnumDescriptor {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[17].Descriptor()
}

func (E2SubsequentAction_TimeToWait) Type() protoreflect.EnumType {
	return &file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes[17]
}

func (x E2SubsequentAction_TimeToWait) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E2SubsequentAction_TimeToWait.Descriptor instead.
func (E2SubsequentAction_TimeToWait) EnumDescriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{16, 1}
}

// --------------C--------------
type Cause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CauseGroup:
	//
	//	*Cause_E2RelatedApiCause_
	//	*Cause_E2ApCause_
	CauseGroup    isCause_CauseGroup `protobuf_oneof:"cause_group"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cause) Reset() {
	*x = Cause{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cause) ProtoMessage() {}

func (x *Cause) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cause.ProtoReflect.Descriptor instead.
func (*Cause) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0}
}

func (x *Cause) GetCauseGroup() isCause_CauseGroup {
	if x != nil {
		return x.CauseGroup
	}
	return nil
}

func (x *Cause) GetE2RelatedApiCause() *Cause_E2RelatedApiCause {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2RelatedApiCause_); ok {
			return x.E2RelatedApiCause
		}
	}
	return nil
}

func (x *Cause) GetE2ApCause() *Cause_E2ApCause {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_); ok {
			return x.E2ApCause
		}
	}
	return nil
}

type isCause_CauseGroup interface {
	isCause_CauseGroup()
}

type Cause_E2RelatedApiCause_ struct {
	E2RelatedApiCause *Cause_E2RelatedApiCause `protobuf:"bytes,1,opt,name=e2_related_api_cause,json=e2RelatedApiCause,proto3,oneof"`
}

type Cause_E2ApCause_ struct {
	E2ApCause *Cause_E2ApCause `protobuf:"bytes,2,opt,name=e2ap_cause,json=e2apCause,proto3,oneof"`
}

func (*Cause_E2RelatedApiCause_) isCause_CauseGroup() {}

func (*Cause_E2ApCause_) isCause_CauseGroup() {}

type CriticalityDiagnostics struct {
	state                        protoimpl.MessageState                                 `protogen:"open.v1"`
	IeCriticalityDiagnosticsList []*CriticalityDiagnostics_IeCriticalityDiagnosticsItem `protobuf:"bytes,1,rep,name=ie_criticality_diagnostics_list,json=ieCriticalityDiagnosticsList,proto3" json:"ie_criticality_diagnostics_list,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CriticalityDiagnostics) Reset() {
	*x = CriticalityDiagnostics{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalityDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalityDiagnostics) ProtoMessage() {}

func (x *CriticalityDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalityDiagnostics.ProtoReflect.Descriptor instead.
func (*CriticalityDiagnostics) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{1}
}

func (x *CriticalityDiagnostics) GetIeCriticalityDiagnosticsList() []*CriticalityDiagnostics_IeCriticalityDiagnosticsItem {
	if x != nil {
		return x.IeCriticalityDiagnosticsList
	}
	return nil
}

// --------------E--------------
type E2ActionDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2ActionDefinition) Reset() {
	*x = E2ActionDefinition{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ActionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ActionDefinition) ProtoMessage() {}

func (x *E2ActionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ActionDefinition.ProtoReflect.Descriptor instead.
func (*E2ActionDefinition) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{2}
}

func (x *E2ActionDefinition) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2ActionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2ActionId) Reset() {
	*x = E2ActionId{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ActionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ActionId) ProtoMessage() {}

func (x *E2ActionId) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ActionId.ProtoReflect.Descriptor instead.
func (*E2ActionId) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{3}
}

func (x *E2ActionId) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type E2CallProcessId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2CallProcessId) Reset() {
	*x = E2CallProcessId{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2CallProcessId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2CallProcessId) ProtoMessage() {}

func (x *E2CallProcessId) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2CallProcessId.ProtoReflect.Descriptor instead.
func (*E2CallProcessId) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{4}
}

func (x *E2CallProcessId) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2ControlHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2ControlHeader) Reset() {
	*x = E2ControlHeader{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ControlHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ControlHeader) ProtoMessage() {}

func (x *E2ControlHeader) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ControlHeader.ProtoReflect.Descriptor instead.
func (*E2ControlHeader) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{5}
}

func (x *E2ControlHeader) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2ControlMessage) Reset() {
	*x = E2ControlMessage{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ControlMessage) ProtoMessage() {}

func (x *E2ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ControlMessage.ProtoReflect.Descriptor instead.
func (*E2ControlMessage) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{6}
}

func (x *E2ControlMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2ControlOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2ControlOutcome) Reset() {
	*x = E2ControlOutcome{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2ControlOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2ControlOutcome) ProtoMessage() {}

func (x *E2ControlOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2ControlOutcome.ProtoReflect.Descriptor instead.
func (*E2ControlOutcome) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{7}
}

func (x *E2ControlOutcome) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2EventTriggerDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2EventTriggerDefinition) Reset() {
	*x = E2EventTriggerDefinition{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2EventTriggerDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2EventTriggerDefinition) ProtoMessage() {}

func (x *E2EventTriggerDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2EventTriggerDefinition.ProtoReflect.Descriptor instead.
func (*E2EventTriggerDefinition) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{8}
}

func (x *E2EventTriggerDefinition) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2IndicationHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2IndicationHeader) Reset() {
	*x = E2IndicationHeader{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2IndicationHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2IndicationHeader) ProtoMessage() {}

func (x *E2IndicationHeader) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2IndicationHeader.ProtoReflect.Descriptor instead.
func (*E2IndicationHeader) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{9}
}

func (x *E2IndicationHeader) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2IndicationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2IndicationMessage) Reset() {
	*x = E2IndicationMessage{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2IndicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2IndicationMessage) ProtoMessage() {}

func (x *E2IndicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2IndicationMessage.ProtoReflect.Descriptor instead.
func (*E2IndicationMessage) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{10}
}

func (x *E2IndicationMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2IndicationSN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2IndicationSN) Reset() {
	*x = E2IndicationSN{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2IndicationSN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2IndicationSN) ProtoMessage() {}

func (x *E2IndicationSN) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2IndicationSN.ProtoReflect.Descriptor instead.
func (*E2IndicationSN) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{11}
}

func (x *E2IndicationSN) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type E2RequestId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2RequestId) Reset() {
	*x = E2RequestId{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2RequestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2RequestId) ProtoMessage() {}

func (x *E2RequestId) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2RequestId.ProtoReflect.Descriptor instead.
func (*E2RequestId) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{12}
}

func (x *E2RequestId) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type E2QueryHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2QueryHeader) Reset() {
	*x = E2QueryHeader{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2QueryHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2QueryHeader) ProtoMessage() {}

func (x *E2QueryHeader) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2QueryHeader.ProtoReflect.Descriptor instead.
func (*E2QueryHeader) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{13}
}

func (x *E2QueryHeader) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2QueryDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2QueryDefinition) Reset() {
	*x = E2QueryDefinition{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2QueryDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2QueryDefinition) ProtoMessage() {}

func (x *E2QueryDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2QueryDefinition.ProtoReflect.Descriptor instead.
func (*E2QueryDefinition) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{14}
}

func (x *E2QueryDefinition) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type E2QueryOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *E2QueryOutcome) Reset() {
	*x = E2QueryOutcome{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2QueryOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2QueryOutcome) ProtoMessage() {}

func (x *E2QueryOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2QueryOutcome.ProtoReflect.Descriptor instead.
func (*E2QueryOutcome) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{15}
}

func (x *E2QueryOutcome) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// From E2AP Clause 9.2.13
type E2SubsequentAction struct {
	state                protoimpl.MessageState                   `protogen:"open.v1"`
	SubsequentActionType *E2SubsequentAction_SubsequentActionType `protobuf:"varint,1,opt,name=subsequent_action_type,json=subsequentActionType,proto3,enum=ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction_SubsequentActionType,oneof" json:"subsequent_action_type,omitempty"`
	E2TimeToWait         *E2SubsequentAction_TimeToWait           `protobuf:"varint,2,opt,name=e2_time_to_wait,json=e2TimeToWait,proto3,enum=ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction_TimeToWait,oneof" json:"e2_time_to_wait,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *E2SubsequentAction) Reset() {
	*x = E2SubsequentAction{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *E2SubsequentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SubsequentAction) ProtoMessage() {}

func (x *E2SubsequentAction) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SubsequentAction.ProtoReflect.Descriptor instead.
func (*E2SubsequentAction) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{16}
}

func (x *E2SubsequentAction) GetSubsequentActionType() E2SubsequentAction_SubsequentActionType {
	if x != nil && x.SubsequentActionType != nil {
		return *x.SubsequentActionType
	}
	return E2SubsequentAction_SUBSEQUENT_ACTION_TYPE_CONTINUE
}

func (x *E2SubsequentAction) GetE2TimeToWait() E2SubsequentAction_TimeToWait {
	if x != nil && x.E2TimeToWait != nil {
		return *x.E2TimeToWait
	}
	return E2SubsequentAction_TIME_TO_WAIT_W1MS
}

type Cause_E2ApCause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CauseGroup:
	//
	//	*Cause_E2ApCause_RicRequest_
	//	*Cause_E2ApCause_RicService_
	//	*Cause_E2ApCause_E2Node_
	//	*Cause_E2ApCause_Transport_
	//	*Cause_E2ApCause_Protocol_
	//	*Cause_E2ApCause_Misc_
	CauseGroup    isCause_E2ApCause_CauseGroup `protobuf_oneof:"cause_group"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cause_E2ApCause) Reset() {
	*x = Cause_E2ApCause{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cause_E2ApCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cause_E2ApCause) ProtoMessage() {}

func (x *Cause_E2ApCause) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cause_E2ApCause.ProtoReflect.Descriptor instead.
func (*Cause_E2ApCause) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Cause_E2ApCause) GetCauseGroup() isCause_E2ApCause_CauseGroup {
	if x != nil {
		return x.CauseGroup
	}
	return nil
}

func (x *Cause_E2ApCause) GetRicRequest() Cause_E2ApCause_RicRequest {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_RicRequest_); ok {
			return x.RicRequest
		}
	}
	return Cause_E2ApCause_RAN_FUNCTION_ID_INVALID
}

func (x *Cause_E2ApCause) GetRicService() Cause_E2ApCause_RicService {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_RicService_); ok {
			return x.RicService
		}
	}
	return Cause_E2ApCause_RAN_FUNCTION_NOT_SUPPORTED
}

func (x *Cause_E2ApCause) GetE2Node() Cause_E2ApCause_E2Node {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_E2Node_); ok {
			return x.E2Node
		}
	}
	return Cause_E2ApCause_E2NODE_COMPONENT_UNKNOWN
}

func (x *Cause_E2ApCause) GetTransport() Cause_E2ApCause_Transport {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_Transport_); ok {
			return x.Transport
		}
	}
	return Cause_E2ApCause_TRANSPORT_UNSPECIFIED
}

func (x *Cause_E2ApCause) GetProtocol() Cause_E2ApCause_Protocol {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_Protocol_); ok {
			return x.Protocol
		}
	}
	return Cause_E2ApCause_TRANSFER_SYNTAX_ERROR
}

func (x *Cause_E2ApCause) GetMisc() Cause_E2ApCause_Misc {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2ApCause_Misc_); ok {
			return x.Misc
		}
	}
	return Cause_E2ApCause_CONTROL_PROCESSING_OVERLOAD
}

type isCause_E2ApCause_CauseGroup interface {
	isCause_E2ApCause_CauseGroup()
}

type Cause_E2ApCause_RicRequest_ struct {
	RicRequest Cause_E2ApCause_RicRequest `protobuf:"varint,1,opt,name=ric_request,json=ricRequest,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2ApCause_RicRequest,oneof"`
}

type Cause_E2ApCause_RicService_ struct {
	RicService Cause_E2ApCause_RicService `protobuf:"varint,2,opt,name=ric_service,json=ricService,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2ApCause_RicService,oneof"`
}

type Cause_E2ApCause_E2Node_ struct {
	E2Node Cause_E2ApCause_E2Node `protobuf:"varint,3,opt,name=e2_node,json=e2Node,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2ApCause_E2Node,oneof"`
}

type Cause_E2ApCause_Transport_ struct {
	Transport Cause_E2ApCause_Transport `protobuf:"varint,4,opt,name=transport,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2ApCause_Transport,oneof"`
}

type Cause_E2ApCause_Protocol_ struct {
	Protocol Cause_E2ApCause_Protocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2ApCause_Protocol,oneof"`
}

type Cause_E2ApCause_Misc_ struct {
	Misc Cause_E2ApCause_Misc `protobuf:"varint,6,opt,name=misc,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2ApCause_Misc,oneof"`
}

func (*Cause_E2ApCause_RicRequest_) isCause_E2ApCause_CauseGroup() {}

func (*Cause_E2ApCause_RicService_) isCause_E2ApCause_CauseGroup() {}

func (*Cause_E2ApCause_E2Node_) isCause_E2ApCause_CauseGroup() {}

func (*Cause_E2ApCause_Transport_) isCause_E2ApCause_CauseGroup() {}

func (*Cause_E2ApCause_Protocol_) isCause_E2ApCause_CauseGroup() {}

func (*Cause_E2ApCause_Misc_) isCause_E2ApCause_CauseGroup() {}

type Cause_E2RelatedApiCause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CauseGroup:
	//
	//	*Cause_E2RelatedApiCause_ApplicationLayer_
	//	*Cause_E2RelatedApiCause_Transport_
	//	*Cause_E2RelatedApiCause_Protocol_
	//	*Cause_E2RelatedApiCause_Misc_
	CauseGroup    isCause_E2RelatedApiCause_CauseGroup `protobuf_oneof:"cause_group"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cause_E2RelatedApiCause) Reset() {
	*x = Cause_E2RelatedApiCause{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cause_E2RelatedApiCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cause_E2RelatedApiCause) ProtoMessage() {}

func (x *Cause_E2RelatedApiCause) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cause_E2RelatedApiCause.ProtoReflect.Descriptor instead.
func (*Cause_E2RelatedApiCause) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Cause_E2RelatedApiCause) GetCauseGroup() isCause_E2RelatedApiCause_CauseGroup {
	if x != nil {
		return x.CauseGroup
	}
	return nil
}

func (x *Cause_E2RelatedApiCause) GetApplicationLayer() Cause_E2RelatedApiCause_ApplicationLayer {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2RelatedApiCause_ApplicationLayer_); ok {
			return x.ApplicationLayer
		}
	}
	return Cause_E2RelatedApiCause_APPLICATION_LAYER_UNSPECIFIED
}

func (x *Cause_E2RelatedApiCause) GetTransport() Cause_E2RelatedApiCause_Transport {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2RelatedApiCause_Transport_); ok {
			return x.Transport
		}
	}
	return Cause_E2RelatedApiCause_TRANSPORT_UNSPECIFIED
}

func (x *Cause_E2RelatedApiCause) GetProtocol() Cause_E2RelatedApiCause_Protocol {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2RelatedApiCause_Protocol_); ok {
			return x.Protocol
		}
	}
	return Cause_E2RelatedApiCause_PROTOCOL_UNSPECIFIED
}

func (x *Cause_E2RelatedApiCause) GetMisc() Cause_E2RelatedApiCause_Misc {
	if x != nil {
		if x, ok := x.CauseGroup.(*Cause_E2RelatedApiCause_Misc_); ok {
			return x.Misc
		}
	}
	return Cause_E2RelatedApiCause_MISC_UNSPECIFIED
}

type isCause_E2RelatedApiCause_CauseGroup interface {
	isCause_E2RelatedApiCause_CauseGroup()
}

type Cause_E2RelatedApiCause_ApplicationLayer_ struct {
	ApplicationLayer Cause_E2RelatedApiCause_ApplicationLayer `protobuf:"varint,1,opt,name=application_layer,json=applicationLayer,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2RelatedApiCause_ApplicationLayer,oneof"`
}

type Cause_E2RelatedApiCause_Transport_ struct {
	Transport Cause_E2RelatedApiCause_Transport `protobuf:"varint,2,opt,name=transport,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2RelatedApiCause_Transport,oneof"`
}

type Cause_E2RelatedApiCause_Protocol_ struct {
	Protocol Cause_E2RelatedApiCause_Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2RelatedApiCause_Protocol,oneof"`
}

type Cause_E2RelatedApiCause_Misc_ struct {
	Misc Cause_E2RelatedApiCause_Misc `protobuf:"varint,4,opt,name=misc,proto3,enum=ricapi.e2_related_apis_common_ies.v1.Cause_E2RelatedApiCause_Misc,oneof"`
}

func (*Cause_E2RelatedApiCause_ApplicationLayer_) isCause_E2RelatedApiCause_CauseGroup() {}

func (*Cause_E2RelatedApiCause_Transport_) isCause_E2RelatedApiCause_CauseGroup() {}

func (*Cause_E2RelatedApiCause_Protocol_) isCause_E2RelatedApiCause_CauseGroup() {}

func (*Cause_E2RelatedApiCause_Misc_) isCause_E2RelatedApiCause_CauseGroup() {}

type CriticalityDiagnostics_IeCriticalityDiagnosticsItem struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	IeCriticality *CriticalityDiagnostics_IeCriticality `protobuf:"varint,1,opt,name=ie_criticality,json=ieCriticality,proto3,enum=ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics_IeCriticality,oneof" json:"ie_criticality,omitempty"`
	IeId          *CriticalityDiagnostics_IeId          `protobuf:"varint,2,opt,name=ie_id,json=ieId,proto3,enum=ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics_IeId,oneof" json:"ie_id,omitempty"`
	TypeOfError   *CriticalityDiagnostics_TypeOfError   `protobuf:"varint,3,opt,name=type_of_error,json=typeOfError,proto3,enum=ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics_TypeOfError,oneof" json:"type_of_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalityDiagnostics_IeCriticalityDiagnosticsItem) Reset() {
	*x = CriticalityDiagnostics_IeCriticalityDiagnosticsItem{}
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalityDiagnostics_IeCriticalityDiagnosticsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalityDiagnostics_IeCriticalityDiagnosticsItem) ProtoMessage() {}

func (x *CriticalityDiagnostics_IeCriticalityDiagnosticsItem) ProtoReflect() protoreflect.Message {
	mi := &file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalityDiagnostics_IeCriticalityDiagnosticsItem.ProtoReflect.Descriptor instead.
func (*CriticalityDiagnostics_IeCriticalityDiagnosticsItem) Descriptor() ([]byte, []int) {
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CriticalityDiagnostics_IeCriticalityDiagnosticsItem) GetIeCriticality() CriticalityDiagnostics_IeCriticality {
	if x != nil && x.IeCriticality != nil {
		return *x.IeCriticality
	}
	return CriticalityDiagnostics_IE_CRITICALITY_REJECT
}

func (x *CriticalityDiagnostics_IeCriticalityDiagnosticsItem) GetIeId() CriticalityDiagnostics_IeId {
	if x != nil && x.IeId != nil {
		return *x.IeId
	}
	return CriticalityDiagnostics_IE_ID_CAUSE
}

func (x *CriticalityDiagnostics_IeCriticalityDiagnosticsItem) GetTypeOfError() CriticalityDiagnostics_TypeOfError {
	if x != nil && x.TypeOfError != nil {
		return *x.TypeOfError
	}
	return CriticalityDiagnostics_TYPE_OF_ERROR_NOT_UNDERSTOOD
}

var File_e2_related_apis_common_ies_ver_1_2_0_proto protoreflect.FileDescriptor

const file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDesc = "" +
	"\n" +
	"*e2_related_apis_common_ies_ver_1_2_0.proto\x12$ricapi.e2_related_apis_common_ies.v1\x1a+near_rt_ric_apis_common_ies_ver_3_0_0.proto\"\x90\x18\n" +
	"\x05Cause\x12p\n" +
	"\x14e2_related_api_cause\x18\x01 \x01(\v2=.ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCauseH\x00R\x11e2RelatedApiCause\x12V\n" +
	"\n" +
	"e2ap_cause\x18\x02 \x01(\v25.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCauseH\x00R\te2apCause\x1a\xbb\f\n" +
	"\tE2apCause\x12c\n" +
	"\vric_request\x18\x01 \x01(\x0e2@.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.RicRequestH\x00R\n" +
	"ricRequest\x12c\n" +
	"\vric_service\x18\x02 \x01(\x0e2@.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.RicServiceH\x00R\n" +
	"ricService\x12W\n" +
	"\ae2_node\x18\x03 \x01(\x0e2<.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.E2NodeH\x00R\x06e2Node\x12_\n" +
	"\ttransport\x18\x04 \x01(\x0e2?.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.TransportH\x00R\ttransport\x12\\\n" +
	"\bprotocol\x18\x05 \x01(\x0e2>.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.ProtocolH\x00R\bprotocol\x12P\n" +
	"\x04misc\x18\x06 \x01(\x0e2:.ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.MiscH\x00R\x04misc\"&\n" +
	"\x06E2Node\x12\x1c\n" +
	"\x18E2NODE_COMPONENT_UNKNOWN\x10\x00\"h\n" +
	"\x04Misc\x12\x1f\n" +
	"\x1bCONTROL_PROCESSING_OVERLOAD\x10\x00\x12\x14\n" +
	"\x10HARDWARE_FAILURE\x10\x01\x12\x13\n" +
	"\x0fOM_INTERVENTION\x10\x02\x12\x14\n" +
	"\x10MISC_UNSPECIFIED\x10\x03\"\x89\x02\n" +
	"\bProtocol\x12\x19\n" +
	"\x15TRANSFER_SYNTAX_ERROR\x10\x00\x12 \n" +
	"\x1cABSTRACT_SYNTAX_ERROR_REJECT\x10\x01\x12+\n" +
	"'ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY\x10\x02\x12.\n" +
	"*MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE\x10\x03\x12\x12\n" +
	"\x0eSEMANTIC_ERROR\x10\x04\x125\n" +
	"1ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE\x10\x05\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x06\"\xa1\x03\n" +
	"\n" +
	"RicRequest\x12\x1b\n" +
	"\x17RAN_FUNCTION_ID_INVALID\x10\x00\x12\x18\n" +
	"\x14ACTION_NOT_SUPPORTED\x10\x01\x12\x15\n" +
	"\x11EXCESSIVE_ACTIONS\x10\x02\x12\x14\n" +
	"\x10DUPLICATE_ACTION\x10\x03\x12\x1b\n" +
	"\x17DUPLICATE_EVENT_TRIGGER\x10\x04\x12\x1b\n" +
	"\x17FUNCTION_RESOURCE_LIMIT\x10\x05\x12\x16\n" +
	"\x12REQUEST_ID_UNKNOWN\x10\x06\x122\n" +
	".INCONSISTENT_ACTION_SUBSEQUENT_ACTION_SEQUENCE\x10\a\x12\x1b\n" +
	"\x17CONTROL_MESSAGE_INVALID\x10\b\x12\x1f\n" +
	"\x1bRIC_CALL_PROCESS_ID_INVALID\x10\t\x12\x19\n" +
	"\x15CONTROL_TIMER_EXPIRED\x10\n" +
	"\x12\x1d\n" +
	"\x19CONTROL_FAILED_TO_EXECUTE\x10\v\x12\x14\n" +
	"\x10SYSTEM_NOT_READY\x10\f\x12\x1b\n" +
	"\x17RIC_REQUEST_UNSPECIFIED\x10\r\"]\n" +
	"\n" +
	"RicService\x12\x1e\n" +
	"\x1aRAN_FUNCTION_NOT_SUPPORTED\x10\x00\x12\x17\n" +
	"\x13EXCESSIVE_FUNCTIONS\x10\x01\x12\x16\n" +
	"\x12RIC_RESOURCE_LIMIT\x10\x02\"J\n" +
	"\tTransport\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTRANSPORT_RESOURCE_UNAVAILABLE\x10\x01B\r\n" +
	"\vcause_group\x1a\xef\t\n" +
	"\x11E2RelatedApiCause\x12}\n" +
	"\x11application_layer\x18\x01 \x01(\x0e2N.ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.ApplicationLayerH\x00R\x10applicationLayer\x12g\n" +
	"\ttransport\x18\x02 \x01(\x0e2G.ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.TransportH\x00R\ttransport\x12d\n" +
	"\bprotocol\x18\x03 \x01(\x0e2F.ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.ProtocolH\x00R\bprotocol\x12X\n" +
	"\x04misc\x18\x04 \x01(\x0e2B.ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.MiscH\x00R\x04misc\"\xe0\x02\n" +
	"\x10ApplicationLayer\x12!\n" +
	"\x1dAPPLICATION_LAYER_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GLOBAL_E2_NODE_ID_INVALID\x10\x01\x12!\n" +
	"\x1dE2_NODE_RESET_OR_DISCONNECTED\x10\x02\x12\x1b\n" +
	"\x17RAN_FUNCTION_ID_INVALID\x10\x03\x12\x18\n" +
	"\x14ACTION_NOT_SUPPORTED\x10\x04\x12\x15\n" +
	"\x11EXCESSIVE_ACTIONS\x10\x05\x12\x14\n" +
	"\x10DUPLICATE_ACTION\x10\x06\x12\x19\n" +
	"\x15E2_REQUEST_ID_UNKNOWN\x10\a\x12\x14\n" +
	"\x10CONTROL_CONFLICT\x10\b\x12\x19\n" +
	"\x15E2_INDICATION_UNKNOWN\x10\t\x12\x1a\n" +
	"\x16E2AP_PROCEDURE_TIMEOUT\x10\n" +
	"\x12\x1b\n" +
	"\x17ESSENTIAL_FOR_OPERATION\x10\v\"h\n" +
	"\x04Misc\x12\x14\n" +
	"\x10MISC_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONTROL_PROCESSING_OVERLOAD\x10\x01\x12\x14\n" +
	"\x10HARDWARE_FAILURE\x10\x02\x12\x13\n" +
	"\x0fOM_INTERVENTION\x10\x03\"\x89\x02\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRANSFER_SYNTAX_ERROR\x10\x01\x12 \n" +
	"\x1cABSTRACT_SYNTAX_ERROR_REJECT\x10\x02\x12+\n" +
	"'ABSTRACT_SYNTAX_ERROR_IGNORE_AND_NOTIFY\x10\x03\x12.\n" +
	"*MESSAGE_NOT_COMPATIBLE_WITH_RECEIVER_STATE\x10\x04\x12\x12\n" +
	"\x0eSEMANTIC_ERROR\x10\x05\x125\n" +
	"1ABSTRACT_SYNTAX_ERROR_FALSELY_CONSTRUCTED_MESSAGE\x10\x06\"J\n" +
	"\tTransport\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTRANSPORT_RESOURCE_UNAVAILABLE\x10\x01B\r\n" +
	"\vcause_groupB\r\n" +
	"\vcause_group\"\xd2\v\n" +
	"\x16CriticalityDiagnostics\x12\xa0\x01\n" +
	"\x1fie_criticality_diagnostics_list\x18\x01 \x03(\v2Y.ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityDiagnosticsItemR\x1cieCriticalityDiagnosticsList\x1a\x95\x03\n" +
	"\x1cIeCriticalityDiagnosticsItem\x12v\n" +
	"\x0eie_criticality\x18\x01 \x01(\x0e2J.ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityH\x00R\rieCriticality\x88\x01\x01\x12[\n" +
	"\x05ie_id\x18\x02 \x01(\x0e2A.ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeIdH\x01R\x04ieId\x88\x01\x01\x12q\n" +
	"\rtype_of_error\x18\x03 \x01(\x0e2H.ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.TypeOfErrorH\x02R\vtypeOfError\x88\x01\x01B\x11\n" +
	"\x0f_ie_criticalityB\b\n" +
	"\x06_ie_idB\x10\n" +
	"\x0e_type_of_error\"`\n" +
	"\rIeCriticality\x12\x19\n" +
	"\x15IE_CRITICALITY_REJECT\x10\x00\x12\x19\n" +
	"\x15IE_CRITICALITY_IGNORE\x10\x01\x12\x19\n" +
	"\x15IE_CRITICALITY_NOTIFY\x10\x02\"\xce\x05\n" +
	"\x04IeId\x12\x0f\n" +
	"\vIE_ID_CAUSE\x10\x00\x12!\n" +
	"\x1dIE_ID_CRITICALITY_DIAGNOSTICS\x10\x01\x12\x16\n" +
	"\x12IE_ID_E2_ACTION_ID\x10\x02\x12\"\n" +
	"\x1eIE_ID_E2_ACTIONS_ADMITTED_LIST\x10\x03\x12&\n" +
	"\"IE_ID_E2_ACTIONS_NOT_ADMITTED_LIST\x10\x04\x12\x1c\n" +
	"\x18IE_ID_E2_CALL_PROCESS_ID\x10\x05\x12 \n" +
	"\x1cIE_ID_E2_CONTROL_ACK_REQUEST\x10\x06\x12\x1b\n" +
	"\x17IE_ID_E2_CONTROL_HEADER\x10\a\x12\x1c\n" +
	"\x18IE_ID_E2_CONTROL_MESSAGE\x10\b\x12\x1c\n" +
	"\x18IE_ID_E2_CONTROL_OUTCOME\x10\t\x12\x1a\n" +
	"\x16IE_ID_E2_CONTROL_TIMER\x10\n" +
	"\x12\x1e\n" +
	"\x1aIE_ID_E2_INDICATION_HEADER\x10\v\x12\x1f\n" +
	"\x1bIE_ID_E2_INDICATION_MESSAGE\x10\f\x12\x1a\n" +
	"\x16IE_ID_E2_INDICATION_SN\x10\r\x12\x1c\n" +
	"\x18IE_ID_E2_INDICATION_TYPE\x10\x0e\x12\x17\n" +
	"\x13IE_ID_E2_REQUEST_ID\x10\x0f\x12!\n" +
	"\x1dIE_ID_E2_SUBSCRIPTION_DETAILS\x10\x10\x12\x1b\n" +
	"\x17IE_ID_GLOBAL_E2_NODE_ID\x10\x11\x12\"\n" +
	"\x1eIE_ID_PROCEDURE_TRANSACTION_ID\x10\x12\x12\x19\n" +
	"\x15IE_ID_RAN_FUNCTION_ID\x10\x13\x12\x1d\n" +
	"\x19IE_ID_SEQUENCE_OF_ACTIONS\x10\x14\x12\x1f\n" +
	"\x1bIE_ID_E2_SUBSCRIPTION_TIMER\x10\x15\x12&\n" +
	"\"IE_ID_E2_SUBSCRIPTION_DELETE_TIMER\x10\x16\"J\n" +
	"\vTypeOfError\x12 \n" +
	"\x1cTYPE_OF_ERROR_NOT_UNDERSTOOD\x10\x00\x12\x19\n" +
	"\x15TYPE_OF_ERROR_MISSING\x10\x01\"9\n" +
	"\x12E2ActionDefinition\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"1\n" +
	"\n" +
	"E2ActionId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\rH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"6\n" +
	"\x0fE2CallProcessId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"6\n" +
	"\x0fE2ControlHeader\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"7\n" +
	"\x10E2ControlMessage\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"7\n" +
	"\x10E2ControlOutcome\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"?\n" +
	"\x18E2EventTriggerDefinition\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"9\n" +
	"\x12E2IndicationHeader\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\":\n" +
	"\x13E2IndicationMessage\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"5\n" +
	"\x0eE2IndicationSN\x12\x19\n" +
	"\x05value\x18\x01 \x01(\rH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"2\n" +
	"\vE2RequestId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\rH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"4\n" +
	"\rE2QueryHeader\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"8\n" +
	"\x11E2QueryDefinition\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"5\n" +
	"\x0eE2QueryOutcome\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xbb\x06\n" +
	"\x12E2SubsequentAction\x12\x88\x01\n" +
	"\x16subsequent_action_type\x18\x01 \x01(\x0e2M.ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.SubsequentActionTypeH\x00R\x14subsequentActionType\x88\x01\x01\x12o\n" +
	"\x0fe2_time_to_wait\x18\x02 \x01(\x0e2C.ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.TimeToWaitH\x01R\fe2TimeToWait\x88\x01\x01\"\\\n" +
	"\x14SubsequentActionType\x12#\n" +
	"\x1fSUBSEQUENT_ACTION_TYPE_CONTINUE\x10\x00\x12\x1f\n" +
	"\x1bSUBSEQUENT_ACTION_TYPE_WAIT\x10\x01\"\x9b\x03\n" +
	"\n" +
	"TimeToWait\x12\x15\n" +
	"\x11TIME_TO_WAIT_W1MS\x10\x00\x12\x15\n" +
	"\x11TIME_TO_WAIT_W2MS\x10\x01\x12\x15\n" +
	"\x11TIME_TO_WAIT_W5MS\x10\x02\x12\x16\n" +
	"\x12TIME_TO_WAIT_W10MS\x10\x03\x12\x16\n" +
	"\x12TIME_TO_WAIT_W20MS\x10\x04\x12\x16\n" +
	"\x12TIME_TO_WAIT_W30MS\x10\x05\x12\x16\n" +
	"\x12TIME_TO_WAIT_W40MS\x10\x06\x12\x16\n" +
	"\x12TIME_TO_WAIT_W50MS\x10\a\x12\x17\n" +
	"\x13TIME_TO_WAIT_W100MS\x10\b\x12\x17\n" +
	"\x13TIME_TO_WAIT_W200MS\x10\t\x12\x17\n" +
	"\x13TIME_TO_WAIT_W500MS\x10\n" +
	"\x12\x14\n" +
	"\x10TIME_TO_WAIT_W1S\x10\v\x12\x14\n" +
	"\x10TIME_TO_WAIT_W2S\x10\f\x12\x14\n" +
	"\x10TIME_TO_WAIT_W5S\x10\r\x12\x15\n" +
	"\x11TIME_TO_WAIT_W10S\x10\x0e\x12\x15\n" +
	"\x11TIME_TO_WAIT_W20S\x10\x0f\x12\x15\n" +
	"\x11TIME_TO_WAIT_W60S\x10\x10B\x19\n" +
	"\x17_subsequent_action_typeB\x12\n" +
	"\x10_e2_time_to_wait*\\\n" +
	"\fE2ActionType\x12\x18\n" +
	"\x14E2ACTION_TYPE_REPORT\x10\x00\x12\x18\n" +
	"\x14E2ACTION_TYPE_INSERT\x10\x01\x12\x18\n" +
	"\x14E2ACTION_TYPE_POLICY\x10\x02*X\n" +
	"\x13E2ControlAckRequest\x12!\n" +
	"\x1dE2_CONTROL_ACK_REQUEST_NO_ACK\x10\x00\x12\x1e\n" +
	"\x1aE2_CONTROL_ACK_REQUEST_ACK\x10\x01*P\n" +
	"\x10E2IndicationType\x12\x1d\n" +
	"\x19E2_INDICATION_TYPE_REPORT\x10\x00\x12\x1d\n" +
	"\x19E2_INDICATION_TYPE_INSERT\x10\x01B1Z/gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/ricapib\x06proto3"

var (
	file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescOnce sync.Once
	file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescData []byte
)

func file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescGZIP() []byte {
	file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescOnce.Do(func() {
		file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDesc), len(file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDesc)))
	})
	return file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDescData
}

var file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes = make([]protoimpl.EnumInfo, 18)
var file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_e2_related_apis_common_ies_ver_1_2_0_proto_goTypes = []any{
	(E2ActionType)(0),                                           // 0: ricapi.e2_related_apis_common_ies.v1.E2ActionType
	(E2ControlAckRequest)(0),                                    // 1: ricapi.e2_related_apis_common_ies.v1.E2ControlAckRequest
	(E2IndicationType)(0),                                       // 2: ricapi.e2_related_apis_common_ies.v1.E2IndicationType
	(Cause_E2ApCause_E2Node)(0),                                 // 3: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.E2Node
	(Cause_E2ApCause_Misc)(0),                                   // 4: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.Misc
	(Cause_E2ApCause_Protocol)(0),                               // 5: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.Protocol
	(Cause_E2ApCause_RicRequest)(0),                             // 6: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.RicRequest
	(Cause_E2ApCause_RicService)(0),                             // 7: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.RicService
	(Cause_E2ApCause_Transport)(0),                              // 8: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.Transport
	(Cause_E2RelatedApiCause_ApplicationLayer)(0),               // 9: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.ApplicationLayer
	(Cause_E2RelatedApiCause_Misc)(0),                           // 10: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.Misc
	(Cause_E2RelatedApiCause_Protocol)(0),                       // 11: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.Protocol
	(Cause_E2RelatedApiCause_Transport)(0),                      // 12: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.Transport
	(CriticalityDiagnostics_IeCriticality)(0),                   // 13: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticality
	(CriticalityDiagnostics_IeId)(0),                            // 14: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeId
	(CriticalityDiagnostics_TypeOfError)(0),                     // 15: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.TypeOfError
	(E2SubsequentAction_SubsequentActionType)(0),                // 16: ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.SubsequentActionType
	(E2SubsequentAction_TimeToWait)(0),                          // 17: ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.TimeToWait
	(*Cause)(nil),                                               // 18: ricapi.e2_related_apis_common_ies.v1.Cause
	(*CriticalityDiagnostics)(nil),                              // 19: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics
	(*E2ActionDefinition)(nil),                                  // 20: ricapi.e2_related_apis_common_ies.v1.E2ActionDefinition
	(*E2ActionId)(nil),                                          // 21: ricapi.e2_related_apis_common_ies.v1.E2ActionId
	(*E2CallProcessId)(nil),                                     // 22: ricapi.e2_related_apis_common_ies.v1.E2CallProcessId
	(*E2ControlHeader)(nil),                                     // 23: ricapi.e2_related_apis_common_ies.v1.E2ControlHeader
	(*E2ControlMessage)(nil),                                    // 24: ricapi.e2_related_apis_common_ies.v1.E2ControlMessage
	(*E2ControlOutcome)(nil),                                    // 25: ricapi.e2_related_apis_common_ies.v1.E2ControlOutcome
	(*E2EventTriggerDefinition)(nil),                            // 26: ricapi.e2_related_apis_common_ies.v1.E2EventTriggerDefinition
	(*E2IndicationHeader)(nil),                                  // 27: ricapi.e2_related_apis_common_ies.v1.E2IndicationHeader
	(*E2IndicationMessage)(nil),                                 // 28: ricapi.e2_related_apis_common_ies.v1.E2IndicationMessage
	(*E2IndicationSN)(nil),                                      // 29: ricapi.e2_related_apis_common_ies.v1.E2IndicationSN
	(*E2RequestId)(nil),                                         // 30: ricapi.e2_related_apis_common_ies.v1.E2RequestId
	(*E2QueryHeader)(nil),                                       // 31: ricapi.e2_related_apis_common_ies.v1.E2QueryHeader
	(*E2QueryDefinition)(nil),                                   // 32: ricapi.e2_related_apis_common_ies.v1.E2QueryDefinition
	(*E2QueryOutcome)(nil),                                      // 33: ricapi.e2_related_apis_common_ies.v1.E2QueryOutcome
	(*E2SubsequentAction)(nil),                                  // 34: ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction
	(*Cause_E2ApCause)(nil),                                     // 35: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause
	(*Cause_E2RelatedApiCause)(nil),                             // 36: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause
	(*CriticalityDiagnostics_IeCriticalityDiagnosticsItem)(nil), // 37: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityDiagnosticsItem
}
var file_e2_related_apis_common_ies_ver_1_2_0_proto_depIdxs = []int32{
	36, // 0: ricapi.e2_related_apis_common_ies.v1.Cause.e2_related_api_cause:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause
	35, // 1: ricapi.e2_related_apis_common_ies.v1.Cause.e2ap_cause:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause
	37, // 2: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.ie_criticality_diagnostics_list:type_name -> ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityDiagnosticsItem
	16, // 3: ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.subsequent_action_type:type_name -> ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.SubsequentActionType
	17, // 4: ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.e2_time_to_wait:type_name -> ricapi.e2_related_apis_common_ies.v1.E2SubsequentAction.TimeToWait
	6,  // 5: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.ric_request:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.RicRequest
	7,  // 6: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.ric_service:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.RicService
	3,  // 7: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.e2_node:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.E2Node
	8,  // 8: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.transport:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.Transport
	5,  // 9: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.protocol:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.Protocol
	4,  // 10: ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.misc:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2apCause.Misc
	9,  // 11: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.application_layer:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.ApplicationLayer
	12, // 12: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.transport:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.Transport
	11, // 13: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.protocol:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.Protocol
	10, // 14: ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.misc:type_name -> ricapi.e2_related_apis_common_ies.v1.Cause.E2RelatedApiCause.Misc
	13, // 15: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityDiagnosticsItem.ie_criticality:type_name -> ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticality
	14, // 16: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityDiagnosticsItem.ie_id:type_name -> ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeId
	15, // 17: ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.IeCriticalityDiagnosticsItem.type_of_error:type_name -> ricapi.e2_related_apis_common_ies.v1.CriticalityDiagnostics.TypeOfError
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_e2_related_apis_common_ies_ver_1_2_0_proto_init() }
func file_e2_related_apis_common_ies_ver_1_2_0_proto_init() {
	if File_e2_related_apis_common_ies_ver_1_2_0_proto != nil {
		return
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_init()
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[0].OneofWrappers = []any{
		(*Cause_E2RelatedApiCause_)(nil),
		(*Cause_E2ApCause_)(nil),
	}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[2].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[3].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[4].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[5].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[6].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[7].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[8].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[9].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[10].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[11].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[12].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[13].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[14].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[15].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[16].OneofWrappers = []any{}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[17].OneofWrappers = []any{
		(*Cause_E2ApCause_RicRequest_)(nil),
		(*Cause_E2ApCause_RicService_)(nil),
		(*Cause_E2ApCause_E2Node_)(nil),
		(*Cause_E2ApCause_Transport_)(nil),
		(*Cause_E2ApCause_Protocol_)(nil),
		(*Cause_E2ApCause_Misc_)(nil),
	}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[18].OneofWrappers = []any{
		(*Cause_E2RelatedApiCause_ApplicationLayer_)(nil),
		(*Cause_E2RelatedApiCause_Transport_)(nil),
		(*Cause_E2RelatedApiCause_Protocol_)(nil),
		(*Cause_E2RelatedApiCause_Misc_)(nil),
	}
	file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDesc), len(file_e2_related_apis_common_ies_ver_1_2_0_proto_rawDesc)),
			NumEnums:      18,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_e2_related_apis_common_ies_ver_1_2_0_proto_goTypes,
		DependencyIndexes: file_e2_related_apis_common_ies_ver_1_2_0_proto_depIdxs,
		EnumInfos:         file_e2_related_apis_common_ies_ver_1_2_0_proto_enumTypes,
		MessageInfos:      file_e2_related_apis_common_ies_ver_1_2_0_proto_msgTypes,
	}.Build()
	File_e2_related_apis_common_ies_ver_1_2_0_proto = out.File
	file_e2_related_apis_common_ies_ver_1_2_0_proto_goTypes = nil
	file_e2_related_apis_common_ies_ver_1_2_0_proto_depIdxs = nil
}
