// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: e2_subscription_api.proto

package ricapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	E2_Subscription_API_E2SubscriptionProc_FullMethodName             = "/ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API/E2SubscriptionProc"
	E2_Subscription_API_E2SubscriptionDeleteProc_FullMethodName       = "/ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API/E2SubscriptionDeleteProc"
	E2_Subscription_API_E2SubscriptionModificationProc_FullMethodName = "/ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API/E2SubscriptionModificationProc"
)

// E2_Subscription_APIClient is the client API for E2_Subscription_API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service and rpc definition
type E2_Subscription_APIClient interface {
	E2SubscriptionProc(ctx context.Context, in *E2SubscriptionInitMsg, opts ...grpc.CallOption) (*E2SubscriptionOutMsg, error)
	E2SubscriptionDeleteProc(ctx context.Context, in *E2SubscriptionDeleteInitMsg, opts ...grpc.CallOption) (*E2SubscriptionDeleteOutMsg, error)
	E2SubscriptionModificationProc(ctx context.Context, in *E2SubscriptionModificationInitMsg, opts ...grpc.CallOption) (*E2SubscriptionModificationOutMsg, error)
}

type e2_Subscription_APIClient struct {
	cc grpc.ClientConnInterface
}

func NewE2_Subscription_APIClient(cc grpc.ClientConnInterface) E2_Subscription_APIClient {
	return &e2_Subscription_APIClient{cc}
}

func (c *e2_Subscription_APIClient) E2SubscriptionProc(ctx context.Context, in *E2SubscriptionInitMsg, opts ...grpc.CallOption) (*E2SubscriptionOutMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(E2SubscriptionOutMsg)
	err := c.cc.Invoke(ctx, E2_Subscription_API_E2SubscriptionProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2_Subscription_APIClient) E2SubscriptionDeleteProc(ctx context.Context, in *E2SubscriptionDeleteInitMsg, opts ...grpc.CallOption) (*E2SubscriptionDeleteOutMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(E2SubscriptionDeleteOutMsg)
	err := c.cc.Invoke(ctx, E2_Subscription_API_E2SubscriptionDeleteProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2_Subscription_APIClient) E2SubscriptionModificationProc(ctx context.Context, in *E2SubscriptionModificationInitMsg, opts ...grpc.CallOption) (*E2SubscriptionModificationOutMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(E2SubscriptionModificationOutMsg)
	err := c.cc.Invoke(ctx, E2_Subscription_API_E2SubscriptionModificationProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// E2_Subscription_APIServer is the server API for E2_Subscription_API service.
// All implementations must embed UnimplementedE2_Subscription_APIServer
// for forward compatibility.
//
// gRPC service and rpc definition
type E2_Subscription_APIServer interface {
	E2SubscriptionProc(context.Context, *E2SubscriptionInitMsg) (*E2SubscriptionOutMsg, error)
	E2SubscriptionDeleteProc(context.Context, *E2SubscriptionDeleteInitMsg) (*E2SubscriptionDeleteOutMsg, error)
	E2SubscriptionModificationProc(context.Context, *E2SubscriptionModificationInitMsg) (*E2SubscriptionModificationOutMsg, error)
	mustEmbedUnimplementedE2_Subscription_APIServer()
}

// UnimplementedE2_Subscription_APIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedE2_Subscription_APIServer struct{}

func (UnimplementedE2_Subscription_APIServer) E2SubscriptionProc(context.Context, *E2SubscriptionInitMsg) (*E2SubscriptionOutMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method E2SubscriptionProc not implemented")
}
func (UnimplementedE2_Subscription_APIServer) E2SubscriptionDeleteProc(context.Context, *E2SubscriptionDeleteInitMsg) (*E2SubscriptionDeleteOutMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method E2SubscriptionDeleteProc not implemented")
}
func (UnimplementedE2_Subscription_APIServer) E2SubscriptionModificationProc(context.Context, *E2SubscriptionModificationInitMsg) (*E2SubscriptionModificationOutMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method E2SubscriptionModificationProc not implemented")
}
func (UnimplementedE2_Subscription_APIServer) mustEmbedUnimplementedE2_Subscription_APIServer() {}
func (UnimplementedE2_Subscription_APIServer) testEmbeddedByValue()                             {}

// UnsafeE2_Subscription_APIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to E2_Subscription_APIServer will
// result in compilation errors.
type UnsafeE2_Subscription_APIServer interface {
	mustEmbedUnimplementedE2_Subscription_APIServer()
}

func RegisterE2_Subscription_APIServer(s grpc.ServiceRegistrar, srv E2_Subscription_APIServer) {
	// If the following call panics, it indicates UnimplementedE2_Subscription_APIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&E2_Subscription_API_ServiceDesc, srv)
}

func _E2_Subscription_API_E2SubscriptionProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(E2SubscriptionInitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2_Subscription_APIServer).E2SubscriptionProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2_Subscription_API_E2SubscriptionProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2_Subscription_APIServer).E2SubscriptionProc(ctx, req.(*E2SubscriptionInitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2_Subscription_API_E2SubscriptionDeleteProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(E2SubscriptionDeleteInitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2_Subscription_APIServer).E2SubscriptionDeleteProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2_Subscription_API_E2SubscriptionDeleteProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2_Subscription_APIServer).E2SubscriptionDeleteProc(ctx, req.(*E2SubscriptionDeleteInitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2_Subscription_API_E2SubscriptionModificationProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(E2SubscriptionModificationInitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2_Subscription_APIServer).E2SubscriptionModificationProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2_Subscription_API_E2SubscriptionModificationProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2_Subscription_APIServer).E2SubscriptionModificationProc(ctx, req.(*E2SubscriptionModificationInitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// E2_Subscription_API_ServiceDesc is the grpc.ServiceDesc for E2_Subscription_API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var E2_Subscription_API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API",
	HandlerType: (*E2_Subscription_APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "E2SubscriptionProc",
			Handler:    _E2_Subscription_API_E2SubscriptionProc_Handler,
		},
		{
			MethodName: "E2SubscriptionDeleteProc",
			Handler:    _E2_Subscription_API_E2SubscriptionDeleteProc_Handler,
		},
		{
			MethodName: "E2SubscriptionModificationProc",
			Handler:    _E2_Subscription_API_E2SubscriptionModificationProc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2_subscription_api.proto",
}

const (
	E2_Subscription_API_Callback_E2SubscriptionDeleteQueryProc_FullMethodName        = "/ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API_Callback/E2SubscriptionDeleteQueryProc"
	E2_Subscription_API_Callback_E2SubscriptionDeleteNotificationProc_FullMethodName = "/ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API_Callback/E2SubscriptionDeleteNotificationProc"
)

// E2_Subscription_API_CallbackClient is the client API for E2_Subscription_API_Callback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type E2_Subscription_API_CallbackClient interface {
	E2SubscriptionDeleteQueryProc(ctx context.Context, in *E2SubscriptionDeleteQueryInitMsg, opts ...grpc.CallOption) (*E2SubscriptionDeleteQueryOutMsg, error)
	E2SubscriptionDeleteNotificationProc(ctx context.Context, in *E2SubscriptionDeleteNotificationInitMsg, opts ...grpc.CallOption) (*E2SubscriptionDeleteNotificationOutMsg, error)
}

type e2_Subscription_API_CallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewE2_Subscription_API_CallbackClient(cc grpc.ClientConnInterface) E2_Subscription_API_CallbackClient {
	return &e2_Subscription_API_CallbackClient{cc}
}

func (c *e2_Subscription_API_CallbackClient) E2SubscriptionDeleteQueryProc(ctx context.Context, in *E2SubscriptionDeleteQueryInitMsg, opts ...grpc.CallOption) (*E2SubscriptionDeleteQueryOutMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(E2SubscriptionDeleteQueryOutMsg)
	err := c.cc.Invoke(ctx, E2_Subscription_API_Callback_E2SubscriptionDeleteQueryProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2_Subscription_API_CallbackClient) E2SubscriptionDeleteNotificationProc(ctx context.Context, in *E2SubscriptionDeleteNotificationInitMsg, opts ...grpc.CallOption) (*E2SubscriptionDeleteNotificationOutMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(E2SubscriptionDeleteNotificationOutMsg)
	err := c.cc.Invoke(ctx, E2_Subscription_API_Callback_E2SubscriptionDeleteNotificationProc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// E2_Subscription_API_CallbackServer is the server API for E2_Subscription_API_Callback service.
// All implementations must embed UnimplementedE2_Subscription_API_CallbackServer
// for forward compatibility.
type E2_Subscription_API_CallbackServer interface {
	E2SubscriptionDeleteQueryProc(context.Context, *E2SubscriptionDeleteQueryInitMsg) (*E2SubscriptionDeleteQueryOutMsg, error)
	E2SubscriptionDeleteNotificationProc(context.Context, *E2SubscriptionDeleteNotificationInitMsg) (*E2SubscriptionDeleteNotificationOutMsg, error)
	mustEmbedUnimplementedE2_Subscription_API_CallbackServer()
}

// UnimplementedE2_Subscription_API_CallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedE2_Subscription_API_CallbackServer struct{}

func (UnimplementedE2_Subscription_API_CallbackServer) E2SubscriptionDeleteQueryProc(context.Context, *E2SubscriptionDeleteQueryInitMsg) (*E2SubscriptionDeleteQueryOutMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method E2SubscriptionDeleteQueryProc not implemented")
}
func (UnimplementedE2_Subscription_API_CallbackServer) E2SubscriptionDeleteNotificationProc(context.Context, *E2SubscriptionDeleteNotificationInitMsg) (*E2SubscriptionDeleteNotificationOutMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method E2SubscriptionDeleteNotificationProc not implemented")
}
func (UnimplementedE2_Subscription_API_CallbackServer) mustEmbedUnimplementedE2_Subscription_API_CallbackServer() {
}
func (UnimplementedE2_Subscription_API_CallbackServer) testEmbeddedByValue() {}

// UnsafeE2_Subscription_API_CallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to E2_Subscription_API_CallbackServer will
// result in compilation errors.
type UnsafeE2_Subscription_API_CallbackServer interface {
	mustEmbedUnimplementedE2_Subscription_API_CallbackServer()
}

func RegisterE2_Subscription_API_CallbackServer(s grpc.ServiceRegistrar, srv E2_Subscription_API_CallbackServer) {
	// If the following call panics, it indicates UnimplementedE2_Subscription_API_CallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&E2_Subscription_API_Callback_ServiceDesc, srv)
}

func _E2_Subscription_API_Callback_E2SubscriptionDeleteQueryProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(E2SubscriptionDeleteQueryInitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2_Subscription_API_CallbackServer).E2SubscriptionDeleteQueryProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2_Subscription_API_Callback_E2SubscriptionDeleteQueryProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2_Subscription_API_CallbackServer).E2SubscriptionDeleteQueryProc(ctx, req.(*E2SubscriptionDeleteQueryInitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2_Subscription_API_Callback_E2SubscriptionDeleteNotificationProc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(E2SubscriptionDeleteNotificationInitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2_Subscription_API_CallbackServer).E2SubscriptionDeleteNotificationProc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2_Subscription_API_Callback_E2SubscriptionDeleteNotificationProc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2_Subscription_API_CallbackServer).E2SubscriptionDeleteNotificationProc(ctx, req.(*E2SubscriptionDeleteNotificationInitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// E2_Subscription_API_Callback_ServiceDesc is the grpc.ServiceDesc for E2_Subscription_API_Callback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var E2_Subscription_API_Callback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricapi.e2_subscription_api_grpc.v1.E2_Subscription_API_Callback",
	HandlerType: (*E2_Subscription_API_CallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "E2SubscriptionDeleteQueryProc",
			Handler:    _E2_Subscription_API_Callback_E2SubscriptionDeleteQueryProc_Handler,
		},
		{
			MethodName: "E2SubscriptionDeleteNotificationProc",
			Handler:    _E2_Subscription_API_Callback_E2SubscriptionDeleteNotificationProc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2_subscription_api.proto",
}
