// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: near_rt_ric_apis_common_ies_ver_3_0_0.proto

package ricapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiName int32

const (
	ApiName_APINAME_E2_SUBSCRIPTION_API   ApiName = 0
	ApiName_APINAME_E2_INDICATION_API     ApiName = 1
	ApiName_APINAME_E2_CONTROL_API        ApiName = 2
	ApiName_APINAME_E2_GUIDANCE_API       ApiName = 3
	ApiName_APINAME_A1_POLICY_API         ApiName = 4
	ApiName_APINAME_A1_EI_API             ApiName = 5
	ApiName_APINAME_SDL_INFORMATION_API   ApiName = 6
	ApiName_APINAME_XAPP_DATA_SHARING_API ApiName = 7
)

// Enum value maps for ApiName.
var (
	ApiName_name = map[int32]string{
		0: "APINAME_E2_SUBSCRIPTION_API",
		1: "APINAME_E2_INDICATION_API",
		2: "APINAME_E2_CONTROL_API",
		3: "APINAME_E2_GUIDANCE_API",
		4: "APINAME_A1_POLICY_API",
		5: "APINAME_A1_EI_API",
		6: "APINAME_SDL_INFORMATION_API",
		7: "APINAME_XAPP_DATA_SHARING_API",
	}
	ApiName_value = map[string]int32{
		"APINAME_E2_SUBSCRIPTION_API":   0,
		"APINAME_E2_INDICATION_API":     1,
		"APINAME_E2_CONTROL_API":        2,
		"APINAME_E2_GUIDANCE_API":       3,
		"APINAME_A1_POLICY_API":         4,
		"APINAME_A1_EI_API":             5,
		"APINAME_SDL_INFORMATION_API":   6,
		"APINAME_XAPP_DATA_SHARING_API": 7,
	}
)

func (x ApiName) Enum() *ApiName {
	p := new(ApiName)
	*p = x
	return p
}

func (x ApiName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiName) Descriptor() protoreflect.EnumDescriptor {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_enumTypes[0].Descriptor()
}

func (ApiName) Type() protoreflect.EnumType {
	return &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_enumTypes[0]
}

func (x ApiName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiName.Descriptor instead.
func (ApiName) EnumDescriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{0}
}

// ----------------------------- Information Elements -----------------------------
// --------------A--------------
// From A1TD Clause 5.2
type A1PolicyTypeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A1PolicyTypeId) Reset() {
	*x = A1PolicyTypeId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A1PolicyTypeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A1PolicyTypeId) ProtoMessage() {}

func (x *A1PolicyTypeId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A1PolicyTypeId.ProtoReflect.Descriptor instead.
func (*A1PolicyTypeId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{0}
}

func (x *A1PolicyTypeId) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type ApiVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiVersion) Reset() {
	*x = ApiVersion{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiVersion) ProtoMessage() {}

func (x *ApiVersion) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiVersion.ProtoReflect.Descriptor instead.
func (*ApiVersion) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{1}
}

func (x *ApiVersion) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// --------------B--------------
// BitString definition
type BitString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Len           *uint32                `protobuf:"varint,2,opt,name=len,proto3,oneof" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitString) Reset() {
	*x = BitString{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitString) ProtoMessage() {}

func (x *BitString) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitString.ProtoReflect.Descriptor instead.
func (*BitString) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{2}
}

func (x *BitString) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BitString) GetLen() uint32 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

// --------------E--------------
type EndpointInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainName    *string                `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3,oneof" json:"domain_name,omitempty"`
	Ipv4Address   *string                `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address,proto3,oneof" json:"ipv4_address,omitempty"`
	Ipv6Address   *string                `protobuf:"bytes,3,opt,name=ipv6_address,json=ipv6Address,proto3,oneof" json:"ipv6_address,omitempty"`
	Port          *uint32                `protobuf:"varint,4,opt,name=port,proto3,oneof" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointInformation) Reset() {
	*x = EndpointInformation{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointInformation) ProtoMessage() {}

func (x *EndpointInformation) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointInformation.ProtoReflect.Descriptor instead.
func (*EndpointInformation) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointInformation) GetDomainName() string {
	if x != nil && x.DomainName != nil {
		return *x.DomainName
	}
	return ""
}

func (x *EndpointInformation) GetIpv4Address() string {
	if x != nil && x.Ipv4Address != nil {
		return *x.Ipv4Address
	}
	return ""
}

func (x *EndpointInformation) GetIpv6Address() string {
	if x != nil && x.Ipv6Address != nil {
		return *x.Ipv6Address
	}
	return ""
}

func (x *EndpointInformation) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

// --------------G--------------
// From E2AP Clause 9.2.6, "Global E2 Node ID"
type GlobalE2NodeId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to NodeType:
	//
	//	*GlobalE2NodeId_Gnb
	//	*GlobalE2NodeId_EnGnb
	//	*GlobalE2NodeId_NgEnb
	//	*GlobalE2NodeId_Enb
	NodeType      isGlobalE2NodeId_NodeType `protobuf_oneof:"node_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalE2NodeId) Reset() {
	*x = GlobalE2NodeId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalE2NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalE2NodeId) ProtoMessage() {}

func (x *GlobalE2NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalE2NodeId.ProtoReflect.Descriptor instead.
func (*GlobalE2NodeId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalE2NodeId) GetNodeType() isGlobalE2NodeId_NodeType {
	if x != nil {
		return x.NodeType
	}
	return nil
}

func (x *GlobalE2NodeId) GetGnb() *GlobalE2NodeId_GlobalE2NodeGnbId {
	if x != nil {
		if x, ok := x.NodeType.(*GlobalE2NodeId_Gnb); ok {
			return x.Gnb
		}
	}
	return nil
}

func (x *GlobalE2NodeId) GetEnGnb() *GlobalE2NodeId_GlobalE2NodeEnGnbId {
	if x != nil {
		if x, ok := x.NodeType.(*GlobalE2NodeId_EnGnb); ok {
			return x.EnGnb
		}
	}
	return nil
}

func (x *GlobalE2NodeId) GetNgEnb() *GlobalE2NodeId_GlobalE2NodeNgEnbId {
	if x != nil {
		if x, ok := x.NodeType.(*GlobalE2NodeId_NgEnb); ok {
			return x.NgEnb
		}
	}
	return nil
}

func (x *GlobalE2NodeId) GetEnb() *GlobalE2NodeId_GlobalE2NodeEnbId {
	if x != nil {
		if x, ok := x.NodeType.(*GlobalE2NodeId_Enb); ok {
			return x.Enb
		}
	}
	return nil
}

type isGlobalE2NodeId_NodeType interface {
	isGlobalE2NodeId_NodeType()
}

type GlobalE2NodeId_Gnb struct {
	Gnb *GlobalE2NodeId_GlobalE2NodeGnbId `protobuf:"bytes,1,opt,name=gnb,proto3,oneof"`
}

type GlobalE2NodeId_EnGnb struct {
	EnGnb *GlobalE2NodeId_GlobalE2NodeEnGnbId `protobuf:"bytes,2,opt,name=en_gnb,json=enGnb,proto3,oneof"`
}

type GlobalE2NodeId_NgEnb struct {
	NgEnb *GlobalE2NodeId_GlobalE2NodeNgEnbId `protobuf:"bytes,3,opt,name=ng_enb,json=ngEnb,proto3,oneof"`
}

type GlobalE2NodeId_Enb struct {
	Enb *GlobalE2NodeId_GlobalE2NodeEnbId `protobuf:"bytes,4,opt,name=enb,proto3,oneof"`
}

func (*GlobalE2NodeId_Gnb) isGlobalE2NodeId_NodeType() {}

func (*GlobalE2NodeId_EnGnb) isGlobalE2NodeId_NodeType() {}

func (*GlobalE2NodeId_NgEnb) isGlobalE2NodeId_NodeType() {}

func (*GlobalE2NodeId_Enb) isGlobalE2NodeId_NodeType() {}

// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type GlobalEnbId struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PlmnIdentity *PlmnIdentity          `protobuf:"bytes,1,opt,name=plmn_identity,json=plmnIdentity,proto3,oneof" json:"plmn_identity,omitempty"`
	// Types that are valid to be assigned to EnbIdChoice:
	//
	//	*GlobalEnbId_MacroEnbId
	//	*GlobalEnbId_HomeEnbId
	//	*GlobalEnbId_ShortMacroEnbId
	//	*GlobalEnbId_LongMacroEnbId
	EnbIdChoice   isGlobalEnbId_EnbIdChoice `protobuf_oneof:"enb_id_choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalEnbId) Reset() {
	*x = GlobalEnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalEnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalEnbId) ProtoMessage() {}

func (x *GlobalEnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalEnbId.ProtoReflect.Descriptor instead.
func (*GlobalEnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{5}
}

func (x *GlobalEnbId) GetPlmnIdentity() *PlmnIdentity {
	if x != nil {
		return x.PlmnIdentity
	}
	return nil
}

func (x *GlobalEnbId) GetEnbIdChoice() isGlobalEnbId_EnbIdChoice {
	if x != nil {
		return x.EnbIdChoice
	}
	return nil
}

func (x *GlobalEnbId) GetMacroEnbId() *BitString {
	if x != nil {
		if x, ok := x.EnbIdChoice.(*GlobalEnbId_MacroEnbId); ok {
			return x.MacroEnbId
		}
	}
	return nil
}

func (x *GlobalEnbId) GetHomeEnbId() *BitString {
	if x != nil {
		if x, ok := x.EnbIdChoice.(*GlobalEnbId_HomeEnbId); ok {
			return x.HomeEnbId
		}
	}
	return nil
}

func (x *GlobalEnbId) GetShortMacroEnbId() *BitString {
	if x != nil {
		if x, ok := x.EnbIdChoice.(*GlobalEnbId_ShortMacroEnbId); ok {
			return x.ShortMacroEnbId
		}
	}
	return nil
}

func (x *GlobalEnbId) GetLongMacroEnbId() *BitString {
	if x != nil {
		if x, ok := x.EnbIdChoice.(*GlobalEnbId_LongMacroEnbId); ok {
			return x.LongMacroEnbId
		}
	}
	return nil
}

type isGlobalEnbId_EnbIdChoice interface {
	isGlobalEnbId_EnbIdChoice()
}

type GlobalEnbId_MacroEnbId struct {
	MacroEnbId *BitString `protobuf:"bytes,2,opt,name=macro_enb_id,json=macroEnbId,proto3,oneof"`
}

type GlobalEnbId_HomeEnbId struct {
	HomeEnbId *BitString `protobuf:"bytes,3,opt,name=home_enb_id,json=homeEnbId,proto3,oneof"`
}

type GlobalEnbId_ShortMacroEnbId struct {
	ShortMacroEnbId *BitString `protobuf:"bytes,4,opt,name=short_macro_enb_id,json=shortMacroEnbId,proto3,oneof"`
}

type GlobalEnbId_LongMacroEnbId struct {
	LongMacroEnbId *BitString `protobuf:"bytes,5,opt,name=long_macro_enb_id,json=longMacroEnbId,proto3,oneof"`
}

func (*GlobalEnbId_MacroEnbId) isGlobalEnbId_EnbIdChoice() {}

func (*GlobalEnbId_HomeEnbId) isGlobalEnbId_EnbIdChoice() {}

func (*GlobalEnbId_ShortMacroEnbId) isGlobalEnbId_EnbIdChoice() {}

func (*GlobalEnbId_LongMacroEnbId) isGlobalEnbId_EnbIdChoice() {}

// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type GlobalEnGnbId struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PlmnIdentity *PlmnIdentity          `protobuf:"bytes,1,opt,name=plmn_identity,json=plmnIdentity,proto3,oneof" json:"plmn_identity,omitempty"`
	// Types that are valid to be assigned to EnGnbIdChoice:
	//
	//	*GlobalEnGnbId_EnGnbId
	EnGnbIdChoice isGlobalEnGnbId_EnGnbIdChoice `protobuf_oneof:"en_gnb_id_choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalEnGnbId) Reset() {
	*x = GlobalEnGnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalEnGnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalEnGnbId) ProtoMessage() {}

func (x *GlobalEnGnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalEnGnbId.ProtoReflect.Descriptor instead.
func (*GlobalEnGnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{6}
}

func (x *GlobalEnGnbId) GetPlmnIdentity() *PlmnIdentity {
	if x != nil {
		return x.PlmnIdentity
	}
	return nil
}

func (x *GlobalEnGnbId) GetEnGnbIdChoice() isGlobalEnGnbId_EnGnbIdChoice {
	if x != nil {
		return x.EnGnbIdChoice
	}
	return nil
}

func (x *GlobalEnGnbId) GetEnGnbId() *BitString {
	if x != nil {
		if x, ok := x.EnGnbIdChoice.(*GlobalEnGnbId_EnGnbId); ok {
			return x.EnGnbId
		}
	}
	return nil
}

type isGlobalEnGnbId_EnGnbIdChoice interface {
	isGlobalEnGnbId_EnGnbIdChoice()
}

type GlobalEnGnbId_EnGnbId struct {
	EnGnbId *BitString `protobuf:"bytes,2,opt,name=en_gnb_id,json=enGnbId,proto3,oneof"`
}

func (*GlobalEnGnbId_EnGnbId) isGlobalEnGnbId_EnGnbIdChoice() {}

// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type GlobalGnbId struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PlmnIdentity *PlmnIdentity          `protobuf:"bytes,1,opt,name=plmn_identity,json=plmnIdentity,proto3,oneof" json:"plmn_identity,omitempty"`
	// Types that are valid to be assigned to GnbIdChoice:
	//
	//	*GlobalGnbId_GnbId
	GnbIdChoice   isGlobalGnbId_GnbIdChoice `protobuf_oneof:"gnb_id_choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalGnbId) Reset() {
	*x = GlobalGnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalGnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalGnbId) ProtoMessage() {}

func (x *GlobalGnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalGnbId.ProtoReflect.Descriptor instead.
func (*GlobalGnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalGnbId) GetPlmnIdentity() *PlmnIdentity {
	if x != nil {
		return x.PlmnIdentity
	}
	return nil
}

func (x *GlobalGnbId) GetGnbIdChoice() isGlobalGnbId_GnbIdChoice {
	if x != nil {
		return x.GnbIdChoice
	}
	return nil
}

func (x *GlobalGnbId) GetGnbId() *BitString {
	if x != nil {
		if x, ok := x.GnbIdChoice.(*GlobalGnbId_GnbId); ok {
			return x.GnbId
		}
	}
	return nil
}

type isGlobalGnbId_GnbIdChoice interface {
	isGlobalGnbId_GnbIdChoice()
}

type GlobalGnbId_GnbId struct {
	GnbId *BitString `protobuf:"bytes,2,opt,name=gnb_id,json=gnbId,proto3,oneof"`
}

func (*GlobalGnbId_GnbId) isGlobalGnbId_GnbIdChoice() {}

// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type GlobalNgEnbId struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PlmnIdentity *PlmnIdentity          `protobuf:"bytes,1,opt,name=plmn_identity,json=plmnIdentity,proto3,oneof" json:"plmn_identity,omitempty"`
	// Types that are valid to be assigned to NgEnbIdChoice:
	//
	//	*GlobalNgEnbId_MacroNgEnbId
	//	*GlobalNgEnbId_ShortMacroNgEnbId
	//	*GlobalNgEnbId_LongMacroNgEnbId
	NgEnbIdChoice isGlobalNgEnbId_NgEnbIdChoice `protobuf_oneof:"ng_enb_id_choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalNgEnbId) Reset() {
	*x = GlobalNgEnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalNgEnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalNgEnbId) ProtoMessage() {}

func (x *GlobalNgEnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalNgEnbId.ProtoReflect.Descriptor instead.
func (*GlobalNgEnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{8}
}

func (x *GlobalNgEnbId) GetPlmnIdentity() *PlmnIdentity {
	if x != nil {
		return x.PlmnIdentity
	}
	return nil
}

func (x *GlobalNgEnbId) GetNgEnbIdChoice() isGlobalNgEnbId_NgEnbIdChoice {
	if x != nil {
		return x.NgEnbIdChoice
	}
	return nil
}

func (x *GlobalNgEnbId) GetMacroNgEnbId() *BitString {
	if x != nil {
		if x, ok := x.NgEnbIdChoice.(*GlobalNgEnbId_MacroNgEnbId); ok {
			return x.MacroNgEnbId
		}
	}
	return nil
}

func (x *GlobalNgEnbId) GetShortMacroNgEnbId() *BitString {
	if x != nil {
		if x, ok := x.NgEnbIdChoice.(*GlobalNgEnbId_ShortMacroNgEnbId); ok {
			return x.ShortMacroNgEnbId
		}
	}
	return nil
}

func (x *GlobalNgEnbId) GetLongMacroNgEnbId() *BitString {
	if x != nil {
		if x, ok := x.NgEnbIdChoice.(*GlobalNgEnbId_LongMacroNgEnbId); ok {
			return x.LongMacroNgEnbId
		}
	}
	return nil
}

type isGlobalNgEnbId_NgEnbIdChoice interface {
	isGlobalNgEnbId_NgEnbIdChoice()
}

type GlobalNgEnbId_MacroNgEnbId struct {
	MacroNgEnbId *BitString `protobuf:"bytes,2,opt,name=macro_ng_enb_id,json=macroNgEnbId,proto3,oneof"`
}

type GlobalNgEnbId_ShortMacroNgEnbId struct {
	ShortMacroNgEnbId *BitString `protobuf:"bytes,3,opt,name=short_macro_ng_enb_id,json=shortMacroNgEnbId,proto3,oneof"`
}

type GlobalNgEnbId_LongMacroNgEnbId struct {
	LongMacroNgEnbId *BitString `protobuf:"bytes,4,opt,name=long_macro_ng_enb_id,json=longMacroNgEnbId,proto3,oneof"`
}

func (*GlobalNgEnbId_MacroNgEnbId) isGlobalNgEnbId_NgEnbIdChoice() {}

func (*GlobalNgEnbId_ShortMacroNgEnbId) isGlobalNgEnbId_NgEnbIdChoice() {}

func (*GlobalNgEnbId_LongMacroNgEnbId) isGlobalNgEnbId_NgEnbIdChoice() {}

// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type GnbCuUpId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint64                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnbCuUpId) Reset() {
	*x = GnbCuUpId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnbCuUpId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnbCuUpId) ProtoMessage() {}

func (x *GnbCuUpId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnbCuUpId.ProtoReflect.Descriptor instead.
func (*GnbCuUpId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{9}
}

func (x *GnbCuUpId) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type GnbDuId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint64                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnbDuId) Reset() {
	*x = GnbDuId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnbDuId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnbDuId) ProtoMessage() {}

func (x *GnbDuId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnbDuId.ProtoReflect.Descriptor instead.
func (*GnbDuId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{10}
}

func (x *GnbDuId) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// --------------N--------------
// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type NgEnbDuId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint64                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NgEnbDuId) Reset() {
	*x = NgEnbDuId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NgEnbDuId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NgEnbDuId) ProtoMessage() {}

func (x *NgEnbDuId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NgEnbDuId.ProtoReflect.Descriptor instead.
func (*NgEnbDuId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{11}
}

func (x *NgEnbDuId) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// --------------P--------------
// From E2AP Clause 9.2.6, as part of "Global E2 Node ID"
type PlmnIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlmnIdentity) Reset() {
	*x = PlmnIdentity{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlmnIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlmnIdentity) ProtoMessage() {}

func (x *PlmnIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlmnIdentity.ProtoReflect.Descriptor instead.
func (*PlmnIdentity) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{12}
}

func (x *PlmnIdentity) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProcedureTransactionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureTransactionId) Reset() {
	*x = ProcedureTransactionId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureTransactionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureTransactionId) ProtoMessage() {}

func (x *ProcedureTransactionId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureTransactionId.ProtoReflect.Descriptor instead.
func (*ProcedureTransactionId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{13}
}

func (x *ProcedureTransactionId) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// --------------R--------------
// From E2AP Clause 9.2.8, "RAN Function ID"
type RanFunctionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RanFunctionId) Reset() {
	*x = RanFunctionId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RanFunctionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RanFunctionId) ProtoMessage() {}

func (x *RanFunctionId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RanFunctionId.ProtoReflect.Descriptor instead.
func (*RanFunctionId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{14}
}

func (x *RanFunctionId) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// --------------X--------------
type XappId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XappId) Reset() {
	*x = XappId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XappId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XappId) ProtoMessage() {}

func (x *XappId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XappId.ProtoReflect.Descriptor instead.
func (*XappId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{15}
}

func (x *XappId) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type GlobalE2NodeId_GlobalE2NodeGnbId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalGnbId   *GlobalGnbId           `protobuf:"bytes,1,opt,name=global_gnb_id,json=globalGnbId,proto3,oneof" json:"global_gnb_id,omitempty"`
	GlobalEnGnbId *GlobalEnGnbId         `protobuf:"bytes,2,opt,name=global_en_gnb_id,json=globalEnGnbId,proto3,oneof" json:"global_en_gnb_id,omitempty"`
	GnbCuUpId     *GnbCuUpId             `protobuf:"bytes,3,opt,name=gnb_cu_up_id,json=gnbCuUpId,proto3,oneof" json:"gnb_cu_up_id,omitempty"`
	GnbDuId       *GnbDuId               `protobuf:"bytes,4,opt,name=gnb_du_id,json=gnbDuId,proto3,oneof" json:"gnb_du_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) Reset() {
	*x = GlobalE2NodeId_GlobalE2NodeGnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalE2NodeId_GlobalE2NodeGnbId) ProtoMessage() {}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalE2NodeId_GlobalE2NodeGnbId.ProtoReflect.Descriptor instead.
func (*GlobalE2NodeId_GlobalE2NodeGnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) GetGlobalGnbId() *GlobalGnbId {
	if x != nil {
		return x.GlobalGnbId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) GetGlobalEnGnbId() *GlobalEnGnbId {
	if x != nil {
		return x.GlobalEnGnbId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) GetGnbCuUpId() *GnbCuUpId {
	if x != nil {
		return x.GnbCuUpId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeGnbId) GetGnbDuId() *GnbDuId {
	if x != nil {
		return x.GnbDuId
	}
	return nil
}

type GlobalE2NodeId_GlobalE2NodeEnGnbId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalEnGnbId *GlobalEnGnbId         `protobuf:"bytes,1,opt,name=global_en_gnb_id,json=globalEnGnbId,proto3,oneof" json:"global_en_gnb_id,omitempty"`
	EnGnbCuUpId   *GnbCuUpId             `protobuf:"bytes,2,opt,name=en_gnb_cu_up_id,json=enGnbCuUpId,proto3,oneof" json:"en_gnb_cu_up_id,omitempty"`
	EnGnbDuId     *GnbDuId               `protobuf:"bytes,3,opt,name=en_gnb_du_id,json=enGnbDuId,proto3,oneof" json:"en_gnb_du_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalE2NodeId_GlobalE2NodeEnGnbId) Reset() {
	*x = GlobalE2NodeId_GlobalE2NodeEnGnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalE2NodeId_GlobalE2NodeEnGnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalE2NodeId_GlobalE2NodeEnGnbId) ProtoMessage() {}

func (x *GlobalE2NodeId_GlobalE2NodeEnGnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalE2NodeId_GlobalE2NodeEnGnbId.ProtoReflect.Descriptor instead.
func (*GlobalE2NodeId_GlobalE2NodeEnGnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GlobalE2NodeId_GlobalE2NodeEnGnbId) GetGlobalEnGnbId() *GlobalEnGnbId {
	if x != nil {
		return x.GlobalEnGnbId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeEnGnbId) GetEnGnbCuUpId() *GnbCuUpId {
	if x != nil {
		return x.EnGnbCuUpId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeEnGnbId) GetEnGnbDuId() *GnbDuId {
	if x != nil {
		return x.EnGnbDuId
	}
	return nil
}

type GlobalE2NodeId_GlobalE2NodeNgEnbId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalNgEnbId *GlobalNgEnbId         `protobuf:"bytes,1,opt,name=global_ng_enb_id,json=globalNgEnbId,proto3,oneof" json:"global_ng_enb_id,omitempty"`
	GlobalEnbId   *GlobalEnbId           `protobuf:"bytes,2,opt,name=global_enb_id,json=globalEnbId,proto3,oneof" json:"global_enb_id,omitempty"`
	NgEnbDuId     *NgEnbDuId             `protobuf:"bytes,3,opt,name=ng_enb_du_id,json=ngEnbDuId,proto3,oneof" json:"ng_enb_du_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalE2NodeId_GlobalE2NodeNgEnbId) Reset() {
	*x = GlobalE2NodeId_GlobalE2NodeNgEnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalE2NodeId_GlobalE2NodeNgEnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalE2NodeId_GlobalE2NodeNgEnbId) ProtoMessage() {}

func (x *GlobalE2NodeId_GlobalE2NodeNgEnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalE2NodeId_GlobalE2NodeNgEnbId.ProtoReflect.Descriptor instead.
func (*GlobalE2NodeId_GlobalE2NodeNgEnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{4, 2}
}

func (x *GlobalE2NodeId_GlobalE2NodeNgEnbId) GetGlobalNgEnbId() *GlobalNgEnbId {
	if x != nil {
		return x.GlobalNgEnbId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeNgEnbId) GetGlobalEnbId() *GlobalEnbId {
	if x != nil {
		return x.GlobalEnbId
	}
	return nil
}

func (x *GlobalE2NodeId_GlobalE2NodeNgEnbId) GetNgEnbDuId() *NgEnbDuId {
	if x != nil {
		return x.NgEnbDuId
	}
	return nil
}

type GlobalE2NodeId_GlobalE2NodeEnbId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalEnbId   *GlobalEnbId           `protobuf:"bytes,1,opt,name=global_enb_id,json=globalEnbId,proto3,oneof" json:"global_enb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalE2NodeId_GlobalE2NodeEnbId) Reset() {
	*x = GlobalE2NodeId_GlobalE2NodeEnbId{}
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalE2NodeId_GlobalE2NodeEnbId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalE2NodeId_GlobalE2NodeEnbId) ProtoMessage() {}

func (x *GlobalE2NodeId_GlobalE2NodeEnbId) ProtoReflect() protoreflect.Message {
	mi := &file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalE2NodeId_GlobalE2NodeEnbId.ProtoReflect.Descriptor instead.
func (*GlobalE2NodeId_GlobalE2NodeEnbId) Descriptor() ([]byte, []int) {
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP(), []int{4, 3}
}

func (x *GlobalE2NodeId_GlobalE2NodeEnbId) GetGlobalEnbId() *GlobalEnbId {
	if x != nil {
		return x.GlobalEnbId
	}
	return nil
}

var File_near_rt_ric_apis_common_ies_ver_3_0_0_proto protoreflect.FileDescriptor

const file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDesc = "" +
	"\n" +
	"+near_rt_ric_apis_common_ies_ver_3_0_0.proto\x12%ricapi.near_rt_ric_apis_common_ies.v3\"5\n" +
	"\x0eA1PolicyTypeId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"1\n" +
	"\n" +
	"ApiVersion\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"O\n" +
	"\tBitString\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01\x12\x15\n" +
	"\x03len\x18\x02 \x01(\rH\x01R\x03len\x88\x01\x01B\b\n" +
	"\x06_valueB\x06\n" +
	"\x04_len\"\xdf\x01\n" +
	"\x13EndpointInformation\x12$\n" +
	"\vdomain_name\x18\x01 \x01(\tH\x00R\n" +
	"domainName\x88\x01\x01\x12&\n" +
	"\fipv4_address\x18\x02 \x01(\tH\x01R\vipv4Address\x88\x01\x01\x12&\n" +
	"\fipv6_address\x18\x03 \x01(\tH\x02R\vipv6Address\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x04 \x01(\rH\x03R\x04port\x88\x01\x01B\x0e\n" +
	"\f_domain_nameB\x0f\n" +
	"\r_ipv4_addressB\x0f\n" +
	"\r_ipv6_addressB\a\n" +
	"\x05_port\"\xbc\r\n" +
	"\x0eGlobalE2NodeId\x12[\n" +
	"\x03gnb\x18\x01 \x01(\v2G.ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbIdH\x00R\x03gnb\x12b\n" +
	"\x06en_gnb\x18\x02 \x01(\v2I.ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnGnbIdH\x00R\x05enGnb\x12b\n" +
	"\x06ng_enb\x18\x03 \x01(\v2I.ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeNgEnbIdH\x00R\x05ngEnb\x12[\n" +
	"\x03enb\x18\x04 \x01(\v2G.ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnbIdH\x00R\x03enb\x1a\xc3\x03\n" +
	"\x11GlobalE2NodeGnbId\x12[\n" +
	"\rglobal_gnb_id\x18\x01 \x01(\v22.ricapi.near_rt_ric_apis_common_ies.v3.GlobalGnbIdH\x00R\vglobalGnbId\x88\x01\x01\x12b\n" +
	"\x10global_en_gnb_id\x18\x02 \x01(\v24.ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbIdH\x01R\rglobalEnGnbId\x88\x01\x01\x12V\n" +
	"\fgnb_cu_up_id\x18\x03 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.GnbCuUpIdH\x02R\tgnbCuUpId\x88\x01\x01\x12O\n" +
	"\tgnb_du_id\x18\x04 \x01(\v2..ricapi.near_rt_ric_apis_common_ies.v3.GnbDuIdH\x03R\agnbDuId\x88\x01\x01B\x10\n" +
	"\x0e_global_gnb_idB\x13\n" +
	"\x11_global_en_gnb_idB\x0f\n" +
	"\r_gnb_cu_up_idB\f\n" +
	"\n" +
	"_gnb_du_id\x1a\xe6\x02\n" +
	"\x13GlobalE2NodeEnGnbId\x12b\n" +
	"\x10global_en_gnb_id\x18\x01 \x01(\v24.ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbIdH\x00R\rglobalEnGnbId\x88\x01\x01\x12[\n" +
	"\x0fen_gnb_cu_up_id\x18\x02 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.GnbCuUpIdH\x01R\venGnbCuUpId\x88\x01\x01\x12T\n" +
	"\fen_gnb_du_id\x18\x03 \x01(\v2..ricapi.near_rt_ric_apis_common_ies.v3.GnbDuIdH\x02R\tenGnbDuId\x88\x01\x01B\x13\n" +
	"\x11_global_en_gnb_idB\x12\n" +
	"\x10_en_gnb_cu_up_idB\x0f\n" +
	"\r_en_gnb_du_id\x1a\xe6\x02\n" +
	"\x13GlobalE2NodeNgEnbId\x12b\n" +
	"\x10global_ng_enb_id\x18\x01 \x01(\v24.ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbIdH\x00R\rglobalNgEnbId\x88\x01\x01\x12[\n" +
	"\rglobal_enb_id\x18\x02 \x01(\v22.ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbIdH\x01R\vglobalEnbId\x88\x01\x01\x12V\n" +
	"\fng_enb_du_id\x18\x03 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.NgEnbDuIdH\x02R\tngEnbDuId\x88\x01\x01B\x13\n" +
	"\x11_global_ng_enb_idB\x10\n" +
	"\x0e_global_enb_idB\x0f\n" +
	"\r_ng_enb_du_id\x1a\x82\x01\n" +
	"\x11GlobalE2NodeEnbId\x12[\n" +
	"\rglobal_enb_id\x18\x01 \x01(\v22.ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbIdH\x00R\vglobalEnbId\x88\x01\x01B\x10\n" +
	"\x0e_global_enb_idB\v\n" +
	"\tnode_type\"\xf9\x03\n" +
	"\vGlobalEnbId\x12]\n" +
	"\rplmn_identity\x18\x01 \x01(\v23.ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentityH\x01R\fplmnIdentity\x88\x01\x01\x12T\n" +
	"\fmacro_enb_id\x18\x02 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\n" +
	"macroEnbId\x12R\n" +
	"\vhome_enb_id\x18\x03 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\thomeEnbId\x12_\n" +
	"\x12short_macro_enb_id\x18\x04 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\x0fshortMacroEnbId\x12]\n" +
	"\x11long_macro_enb_id\x18\x05 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\x0elongMacroEnbIdB\x0f\n" +
	"\renb_id_choiceB\x10\n" +
	"\x0e_plmn_identity\"\xe4\x01\n" +
	"\rGlobalEnGnbId\x12]\n" +
	"\rplmn_identity\x18\x01 \x01(\v23.ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentityH\x01R\fplmnIdentity\x88\x01\x01\x12N\n" +
	"\ten_gnb_id\x18\x02 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\aenGnbIdB\x12\n" +
	"\x10en_gnb_id_choiceB\x10\n" +
	"\x0e_plmn_identity\"\xda\x01\n" +
	"\vGlobalGnbId\x12]\n" +
	"\rplmn_identity\x18\x01 \x01(\v23.ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentityH\x01R\fplmnIdentity\x88\x01\x01\x12I\n" +
	"\x06gnb_id\x18\x02 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\x05gnbIdB\x0f\n" +
	"\rgnb_id_choiceB\x10\n" +
	"\x0e_plmn_identity\"\xb9\x03\n" +
	"\rGlobalNgEnbId\x12]\n" +
	"\rplmn_identity\x18\x01 \x01(\v23.ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentityH\x01R\fplmnIdentity\x88\x01\x01\x12Y\n" +
	"\x0fmacro_ng_enb_id\x18\x02 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\fmacroNgEnbId\x12d\n" +
	"\x15short_macro_ng_enb_id\x18\x03 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\x11shortMacroNgEnbId\x12b\n" +
	"\x14long_macro_ng_enb_id\x18\x04 \x01(\v20.ricapi.near_rt_ric_apis_common_ies.v3.BitStringH\x00R\x10longMacroNgEnbIdB\x12\n" +
	"\x10ng_enb_id_choiceB\x10\n" +
	"\x0e_plmn_identity\"0\n" +
	"\tGnbCuUpId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x04H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\".\n" +
	"\aGnbDuId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x04H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"0\n" +
	"\tNgEnbDuId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x04H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"3\n" +
	"\fPlmnIdentity\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"=\n" +
	"\x16ProcedureTransactionId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\rH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"4\n" +
	"\rRanFunctionId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\rH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"-\n" +
	"\x06XappId\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value*\xf8\x01\n" +
	"\aApiName\x12\x1f\n" +
	"\x1bAPINAME_E2_SUBSCRIPTION_API\x10\x00\x12\x1d\n" +
	"\x19APINAME_E2_INDICATION_API\x10\x01\x12\x1a\n" +
	"\x16APINAME_E2_CONTROL_API\x10\x02\x12\x1b\n" +
	"\x17APINAME_E2_GUIDANCE_API\x10\x03\x12\x19\n" +
	"\x15APINAME_A1_POLICY_API\x10\x04\x12\x15\n" +
	"\x11APINAME_A1_EI_API\x10\x05\x12\x1f\n" +
	"\x1bAPINAME_SDL_INFORMATION_API\x10\x06\x12!\n" +
	"\x1dAPINAME_XAPP_DATA_SHARING_API\x10\aB1Z/gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/ricapib\x06proto3"

var (
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescOnce sync.Once
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescData []byte
)

func file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescGZIP() []byte {
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescOnce.Do(func() {
		file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDesc), len(file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDesc)))
	})
	return file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDescData
}

var file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_goTypes = []any{
	(ApiName)(0),                               // 0: ricapi.near_rt_ric_apis_common_ies.v3.ApiName
	(*A1PolicyTypeId)(nil),                     // 1: ricapi.near_rt_ric_apis_common_ies.v3.A1PolicyTypeId
	(*ApiVersion)(nil),                         // 2: ricapi.near_rt_ric_apis_common_ies.v3.ApiVersion
	(*BitString)(nil),                          // 3: ricapi.near_rt_ric_apis_common_ies.v3.BitString
	(*EndpointInformation)(nil),                // 4: ricapi.near_rt_ric_apis_common_ies.v3.EndpointInformation
	(*GlobalE2NodeId)(nil),                     // 5: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId
	(*GlobalEnbId)(nil),                        // 6: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId
	(*GlobalEnGnbId)(nil),                      // 7: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbId
	(*GlobalGnbId)(nil),                        // 8: ricapi.near_rt_ric_apis_common_ies.v3.GlobalGnbId
	(*GlobalNgEnbId)(nil),                      // 9: ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbId
	(*GnbCuUpId)(nil),                          // 10: ricapi.near_rt_ric_apis_common_ies.v3.GnbCuUpId
	(*GnbDuId)(nil),                            // 11: ricapi.near_rt_ric_apis_common_ies.v3.GnbDuId
	(*NgEnbDuId)(nil),                          // 12: ricapi.near_rt_ric_apis_common_ies.v3.NgEnbDuId
	(*PlmnIdentity)(nil),                       // 13: ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentity
	(*ProcedureTransactionId)(nil),             // 14: ricapi.near_rt_ric_apis_common_ies.v3.ProcedureTransactionId
	(*RanFunctionId)(nil),                      // 15: ricapi.near_rt_ric_apis_common_ies.v3.RanFunctionId
	(*XappId)(nil),                             // 16: ricapi.near_rt_ric_apis_common_ies.v3.XappId
	(*GlobalE2NodeId_GlobalE2NodeGnbId)(nil),   // 17: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbId
	(*GlobalE2NodeId_GlobalE2NodeEnGnbId)(nil), // 18: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnGnbId
	(*GlobalE2NodeId_GlobalE2NodeNgEnbId)(nil), // 19: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeNgEnbId
	(*GlobalE2NodeId_GlobalE2NodeEnbId)(nil),   // 20: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnbId
}
var file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_depIdxs = []int32{
	17, // 0: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.gnb:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbId
	18, // 1: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.en_gnb:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnGnbId
	19, // 2: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.ng_enb:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeNgEnbId
	20, // 3: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.enb:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnbId
	13, // 4: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId.plmn_identity:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentity
	3,  // 5: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId.macro_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	3,  // 6: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId.home_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	3,  // 7: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId.short_macro_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	3,  // 8: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId.long_macro_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	13, // 9: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbId.plmn_identity:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentity
	3,  // 10: ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbId.en_gnb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	13, // 11: ricapi.near_rt_ric_apis_common_ies.v3.GlobalGnbId.plmn_identity:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentity
	3,  // 12: ricapi.near_rt_ric_apis_common_ies.v3.GlobalGnbId.gnb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	13, // 13: ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbId.plmn_identity:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.PlmnIdentity
	3,  // 14: ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbId.macro_ng_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	3,  // 15: ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbId.short_macro_ng_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	3,  // 16: ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbId.long_macro_ng_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.BitString
	8,  // 17: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbId.global_gnb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalGnbId
	7,  // 18: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbId.global_en_gnb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbId
	10, // 19: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbId.gnb_cu_up_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GnbCuUpId
	11, // 20: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeGnbId.gnb_du_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GnbDuId
	7,  // 21: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnGnbId.global_en_gnb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnGnbId
	10, // 22: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnGnbId.en_gnb_cu_up_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GnbCuUpId
	11, // 23: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnGnbId.en_gnb_du_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GnbDuId
	9,  // 24: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeNgEnbId.global_ng_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalNgEnbId
	6,  // 25: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeNgEnbId.global_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId
	12, // 26: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeNgEnbId.ng_enb_du_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.NgEnbDuId
	6,  // 27: ricapi.near_rt_ric_apis_common_ies.v3.GlobalE2NodeId.GlobalE2NodeEnbId.global_enb_id:type_name -> ricapi.near_rt_ric_apis_common_ies.v3.GlobalEnbId
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_init() }
func file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_init() {
	if File_near_rt_ric_apis_common_ies_ver_3_0_0_proto != nil {
		return
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[0].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[1].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[2].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[3].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[4].OneofWrappers = []any{
		(*GlobalE2NodeId_Gnb)(nil),
		(*GlobalE2NodeId_EnGnb)(nil),
		(*GlobalE2NodeId_NgEnb)(nil),
		(*GlobalE2NodeId_Enb)(nil),
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[5].OneofWrappers = []any{
		(*GlobalEnbId_MacroEnbId)(nil),
		(*GlobalEnbId_HomeEnbId)(nil),
		(*GlobalEnbId_ShortMacroEnbId)(nil),
		(*GlobalEnbId_LongMacroEnbId)(nil),
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[6].OneofWrappers = []any{
		(*GlobalEnGnbId_EnGnbId)(nil),
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[7].OneofWrappers = []any{
		(*GlobalGnbId_GnbId)(nil),
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[8].OneofWrappers = []any{
		(*GlobalNgEnbId_MacroNgEnbId)(nil),
		(*GlobalNgEnbId_ShortMacroNgEnbId)(nil),
		(*GlobalNgEnbId_LongMacroNgEnbId)(nil),
	}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[9].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[10].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[11].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[12].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[13].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[14].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[15].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[16].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[17].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[18].OneofWrappers = []any{}
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDesc), len(file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_goTypes,
		DependencyIndexes: file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_depIdxs,
		EnumInfos:         file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_enumTypes,
		MessageInfos:      file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_msgTypes,
	}.Build()
	File_near_rt_ric_apis_common_ies_ver_3_0_0_proto = out.File
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_goTypes = nil
	file_near_rt_ric_apis_common_ies_ver_3_0_0_proto_depIdxs = nil
}
