// Code generated by go-swagger; DO NOT EDIT.

package debug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/submgr/pkg/rtmgr_models"
)

// GetDebuginfoReader is a Reader for the GetDebuginfo structure.
type GetDebuginfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDebuginfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDebuginfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewGetDebuginfoCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /getdebuginfo] get_debuginfo", response, response.Code())
	}
}

// NewGetDebuginfoOK creates a GetDebuginfoOK with default headers values
func NewGetDebuginfoOK() *GetDebuginfoOK {
	return &GetDebuginfoOK{}
}

/*
GetDebuginfoOK describes a response with status code 200, with default header values.

Debug Info from routing manager
*/
type GetDebuginfoOK struct {
	Payload *rtmgr_models.Debuginfo
}

// IsSuccess returns true when this get debuginfo o k response has a 2xx status code
func (o *GetDebuginfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get debuginfo o k response has a 3xx status code
func (o *GetDebuginfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get debuginfo o k response has a 4xx status code
func (o *GetDebuginfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get debuginfo o k response has a 5xx status code
func (o *GetDebuginfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get debuginfo o k response a status code equal to that given
func (o *GetDebuginfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get debuginfo o k response
func (o *GetDebuginfoOK) Code() int {
	return 200
}

func (o *GetDebuginfoOK) Error() string {
	return fmt.Sprintf("[GET /getdebuginfo][%d] getDebuginfoOK  %+v", 200, o.Payload)
}

func (o *GetDebuginfoOK) String() string {
	return fmt.Sprintf("[GET /getdebuginfo][%d] getDebuginfoOK  %+v", 200, o.Payload)
}

func (o *GetDebuginfoOK) GetPayload() *rtmgr_models.Debuginfo {
	return o.Payload
}

func (o *GetDebuginfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtmgr_models.Debuginfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDebuginfoCreated creates a GetDebuginfoCreated with default headers values
func NewGetDebuginfoCreated() *GetDebuginfoCreated {
	return &GetDebuginfoCreated{}
}

/*
GetDebuginfoCreated describes a response with status code 201, with default header values.

Error while fetching Debug data
*/
type GetDebuginfoCreated struct {
}

// IsSuccess returns true when this get debuginfo created response has a 2xx status code
func (o *GetDebuginfoCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get debuginfo created response has a 3xx status code
func (o *GetDebuginfoCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get debuginfo created response has a 4xx status code
func (o *GetDebuginfoCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this get debuginfo created response has a 5xx status code
func (o *GetDebuginfoCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this get debuginfo created response a status code equal to that given
func (o *GetDebuginfoCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the get debuginfo created response
func (o *GetDebuginfoCreated) Code() int {
	return 201
}

func (o *GetDebuginfoCreated) Error() string {
	return fmt.Sprintf("[GET /getdebuginfo][%d] getDebuginfoCreated ", 201)
}

func (o *GetDebuginfoCreated) String() string {
	return fmt.Sprintf("[GET /getdebuginfo][%d] getDebuginfoCreated ", 201)
}

func (o *GetDebuginfoCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
