// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddRmrRoute add rmr route
//
// swagger:model add-rmr-route
type AddRmrRoute struct {

	// message type
	// Required: true
	MessageType *uint32 `json:"MessageType"`

	// sender end point
	SenderEndPoint string `json:"SenderEndPoint,omitempty"`

	// subscription ID
	SubscriptionID int32 `json:"SubscriptionID,omitempty"`

	// target end point
	// Required: true
	TargetEndPoint *string `json:"TargetEndPoint"`
}

// Validate validates this add rmr route
func (m *AddRmrRoute) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessageType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetEndPoint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddRmrRoute) validateMessageType(formats strfmt.Registry) error {

	if err := validate.Required("MessageType", "body", m.MessageType); err != nil {
		return err
	}

	return nil
}

func (m *AddRmrRoute) validateTargetEndPoint(formats strfmt.Registry) error {

	if err := validate.Required("TargetEndPoint", "body", m.TargetEndPoint); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this add rmr route based on context it is used
func (m *AddRmrRoute) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddRmrRoute) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddRmrRoute) UnmarshalBinary(b []byte) error {
	var res AddRmrRoute
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
