// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Debuginfo debuginfo
//
// swagger:model debuginfo
type Debuginfo struct {

	// route configs
	RouteConfigs string `json:"RouteConfigs,omitempty"`

	// route table
	// Required: true
	RouteTable []string `json:"RouteTable"`
}

// Validate validates this debuginfo
func (m *Debuginfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRouteTable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Debuginfo) validateRouteTable(formats strfmt.Registry) error {

	if err := validate.Required("RouteTable", "body", m.RouteTable); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this debuginfo based on context it is used
func (m *Debuginfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Debuginfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Debuginfo) UnmarshalBinary(b []byte) error {
	var res Debuginfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
