// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// E2tDeleteData e2t delete data
//
// swagger:model e2t-delete-data
type E2tDeleteData struct {

	// e2 t address
	// Required: true
	E2TAddress *string `json:"E2TAddress"`

	// ran assoc list
	RanAssocList RanE2tMap `json:"ranAssocList,omitempty"`

	// ran namelist tobe dissociated
	RanNamelistTobeDissociated RanNamelist `json:"ranNamelistTobeDissociated,omitempty"`
}

// Validate validates this e2t delete data
func (m *E2tDeleteData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateE2TAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRanAssocList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRanNamelistTobeDissociated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *E2tDeleteData) validateE2TAddress(formats strfmt.Registry) error {

	if err := validate.Required("E2TAddress", "body", m.E2TAddress); err != nil {
		return err
	}

	return nil
}

func (m *E2tDeleteData) validateRanAssocList(formats strfmt.Registry) error {
	if swag.IsZero(m.RanAssocList) { // not required
		return nil
	}

	if err := m.RanAssocList.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ranAssocList")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ranAssocList")
		}
		return err
	}

	return nil
}

func (m *E2tDeleteData) validateRanNamelistTobeDissociated(formats strfmt.Registry) error {
	if swag.IsZero(m.RanNamelistTobeDissociated) { // not required
		return nil
	}

	if err := m.RanNamelistTobeDissociated.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ranNamelistTobeDissociated")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ranNamelistTobeDissociated")
		}
		return err
	}

	return nil
}

// ContextValidate validate this e2t delete data based on the context it is used
func (m *E2tDeleteData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRanAssocList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRanNamelistTobeDissociated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *E2tDeleteData) contextValidateRanAssocList(ctx context.Context, formats strfmt.Registry) error {

	if err := m.RanAssocList.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ranAssocList")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ranAssocList")
		}
		return err
	}

	return nil
}

func (m *E2tDeleteData) contextValidateRanNamelistTobeDissociated(ctx context.Context, formats strfmt.Registry) error {

	if err := m.RanNamelistTobeDissociated.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ranNamelistTobeDissociated")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ranNamelistTobeDissociated")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *E2tDeleteData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *E2tDeleteData) UnmarshalBinary(b []byte) error {
	var res E2tDeleteData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
