// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// E2tData e2t data
//
// swagger:model e2t-data
type E2tData struct {

	// e2 t address
	// Required: true
	E2TAddress *string `json:"E2TAddress"`

	// ran namelist
	RanNamelist RanNamelist `json:"ranNamelist,omitempty"`
}

// Validate validates this e2t data
func (m *E2tData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateE2TAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRanNamelist(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *E2tData) validateE2TAddress(formats strfmt.Registry) error {

	if err := validate.Required("E2TAddress", "body", m.E2TAddress); err != nil {
		return err
	}

	return nil
}

func (m *E2tData) validateRanNamelist(formats strfmt.Registry) error {
	if swag.IsZero(m.RanNamelist) { // not required
		return nil
	}

	if err := m.RanNamelist.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ranNamelist")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ranNamelist")
		}
		return err
	}

	return nil
}

// ContextValidate validate this e2t data based on the context it is used
func (m *E2tData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRanNamelist(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *E2tData) contextValidateRanNamelist(ctx context.Context, formats strfmt.Registry) error {

	if err := m.RanNamelist.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ranNamelist")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("ranNamelist")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *E2tData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *E2tData) UnmarshalBinary(b []byte) error {
	var res E2tData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
