// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Endpoint endpoint
//
// swagger:model endpoint
type Endpoint struct {

	// end point fqdn
	EndPointFqdn string `json:"EndPointFqdn,omitempty"`

	// end point name
	EndPointName string `json:"EndPointName,omitempty"`

	// end point port
	// Maximum: 65535
	// Minimum: 0
	EndPointPort *uint16 `json:"EndPointPort,omitempty"`
}

// Validate validates this endpoint
func (m *Endpoint) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndPointPort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Endpoint) validateEndPointPort(formats strfmt.Registry) error {
	if swag.IsZero(m.EndPointPort) { // not required
		return nil
	}

	if err := validate.MinimumUint("EndPointPort", "body", uint64(*m.EndPointPort), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumUint("EndPointPort", "body", uint64(*m.EndPointPort), 65535, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this endpoint based on context it is used
func (m *Endpoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Endpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Endpoint) UnmarshalBinary(b []byte) error {
	var res Endpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
