// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HealthStatus health status
//
// swagger:model health-status
type HealthStatus struct {

	// status
	// Enum: [healthy unhealthy]
	Status string `json:"status,omitempty"`
}

// Validate validates this health status
func (m *HealthStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var healthStatusTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["healthy","unhealthy"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		healthStatusTypeStatusPropEnum = append(healthStatusTypeStatusPropEnum, v)
	}
}

const (

	// HealthStatusStatusHealthy captures enum value "healthy"
	HealthStatusStatusHealthy string = "healthy"

	// HealthStatusStatusUnhealthy captures enum value "unhealthy"
	HealthStatusStatusUnhealthy string = "unhealthy"
)

// prop value enum
func (m *HealthStatus) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, healthStatusTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HealthStatus) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this health status based on context it is used
func (m *HealthStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthStatus) UnmarshalBinary(b []byte) error {
	var res HealthStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
