// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// RanNamelist ran namelist
//
// swagger:model ranNamelist
type RanNamelist []string

// Validate validates this ran namelist
func (m RanNamelist) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ran namelist based on context it is used
func (m RanNamelist) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
