// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// XappSubscriptionData xapp subscription data
//
// swagger:model xapp-subscription-data
type XappSubscriptionData struct {

	// address
	// Required: true
	Address *string `json:"address"`

	// port
	// Required: true
	// Maximum: 65535
	// Minimum: 0
	Port *uint16 `json:"port"`

	// subscription id
	// Required: true
	SubscriptionID *int32 `json:"subscription_id"`
}

// Validate validates this xapp subscription data
func (m *XappSubscriptionData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubscriptionID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *XappSubscriptionData) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *XappSubscriptionData) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	if err := validate.MinimumUint("port", "body", uint64(*m.Port), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumUint("port", "body", uint64(*m.Port), 65535, false); err != nil {
		return err
	}

	return nil
}

func (m *XappSubscriptionData) validateSubscriptionID(formats strfmt.Registry) error {

	if err := validate.Required("subscription_id", "body", m.SubscriptionID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this xapp subscription data based on context it is used
func (m *XappSubscriptionData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *XappSubscriptionData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XappSubscriptionData) UnmarshalBinary(b []byte) error {
	var res XappSubscriptionData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
