// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// XappElement xapp element
//
// swagger:model xapp-element
type XappElement struct {

	// address
	// Required: true
	Address *string `json:"address"`

	// port
	// Required: true
	// Maximum: 65535
	// Minimum: 0
	Port *uint16 `json:"port"`
}

// Validate validates this xapp element
func (m *XappElement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *XappElement) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *XappElement) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	if err := validate.MinimumUint("port", "body", uint64(*m.Port), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumUint("port", "body", uint64(*m.Port), 65535, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this xapp element based on context it is used
func (m *XappElement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *XappElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XappElement) UnmarshalBinary(b []byte) error {
	var res XappElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
