// Code generated by go-swagger; DO NOT EDIT.

package rtmgr_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// XappCallbackData xapp callback data
//
// swagger:model xapp-callback-data
type XappCallbackData struct {

	// event
	Event string `json:"event,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`

	// x apps
	XApps string `json:"xApps,omitempty"`
}

// Validate validates this xapp callback data
func (m *XappCallbackData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this xapp callback data based on context it is used
func (m *XappCallbackData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *XappCallbackData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XappCallbackData) UnmarshalBinary(b []byte) error {
	var res XappCallbackData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
