kind: Service
apiVersion: v1
metadata:
  name: {{ include "common.servicename.submgr.http" . }}
  namespace: {{ include "common.namespace.platform" . }}
  labels:
    app: {{ include "common.namespace.platform" . }}-{{ include "common.name.submgr" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "common.namespace.platform" . }}-{{ include "common.name.submgr" . }}
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
    - name: http
      port: {{ include "common.serviceport.submgr.http" . }}
      protocol: TCP
      targetPort: http
    - name: subscription
      port: 8088
      protocol: TCP
      targetPort: 8088